/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { FactifyError } from "./factifyerror.js";

/**
 * Invalid request parameters
 */
export type ErrorResponseData = {
  /**
   * ConnectRPC error code. Maps to HTTP status codes:
   *
   * @remarks
   * - invalid_argument, failed_precondition -> 400
   * - unauthenticated -> 401
   * - permission_denied -> 403
   * - not_found -> 404
   * - already_exists -> 409
   * - resource_exhausted -> 429
   * - deadline_exceeded -> 408
   * - canceled -> 499
   * - internal, unknown -> 500 (unknown may appear as 400 for malformed JSON requests)
   * - unimplemented -> 501
   * - unavailable -> 503
   */
  code: components.ErrorResponseCode;
  /**
   * Structured error details for programmatic handling
   */
  details?: Array<components.ErrorDetail> | undefined;
  /**
   * Human-readable error message
   */
  message: string;
  httpMeta: components.HTTPMetadata;
};

/**
 * Invalid request parameters
 */
export class ErrorResponse extends FactifyError {
  /**
   * ConnectRPC error code. Maps to HTTP status codes:
   *
   * @remarks
   * - invalid_argument, failed_precondition -> 400
   * - unauthenticated -> 401
   * - permission_denied -> 403
   * - not_found -> 404
   * - already_exists -> 409
   * - resource_exhausted -> 429
   * - deadline_exceeded -> 408
   * - canceled -> 499
   * - internal, unknown -> 500 (unknown may appear as 400 for malformed JSON requests)
   * - unimplemented -> 501
   * - unavailable -> 503
   */
  code: components.ErrorResponseCode;
  /**
   * Structured error details for programmatic handling
   */
  details?: Array<components.ErrorDetail> | undefined;

  /** The original data that was passed to this error instance. */
  data$: ErrorResponseData;

  constructor(
    err: ErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.details != null) this.details = err.details;

    this.name = "ErrorResponse";
  }
}

/** @internal */
export const ErrorResponse$inboundSchema: z.ZodMiniType<
  ErrorResponse,
  unknown
> = z.pipe(
  z.object({
    code: components.ErrorResponseCode$inboundSchema,
    details: types.optional(z.array(components.ErrorDetail$inboundSchema)),
    message: types.string(),
    HttpMeta: components.HTTPMetadata$inboundSchema,
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "HttpMeta": "httpMeta",
    });

    return new ErrorResponse(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
