/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accessRequestsApprove } from "../funcs/accessRequestsApprove.js";
import { accessRequestsCheckStatus } from "../funcs/accessRequestsCheckStatus.js";
import { accessRequestsCreate } from "../funcs/accessRequestsCreate.js";
import { accessRequestsDeny } from "../funcs/accessRequestsDeny.js";
import { accessRequestsInspect } from "../funcs/accessRequestsInspect.js";
import { accessRequestsList } from "../funcs/accessRequestsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class AccessRequests extends ClientSDK {
  /**
   * List access requests
   *
   * @remarks
   * Lists pending access requests for the specified document.
   */
  async list(
    request: operations.ListAccessRequestsRequest,
    options?: RequestOptions,
  ): Promise<operations.ListAccessRequestsResponse> {
    return unwrapAsync(accessRequestsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create an access request
   *
   * @remarks
   * Creates a new access request for the specified document.
   */
  async create(
    request: operations.CreateAccessRequestRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateAccessRequestResponse> {
    return unwrapAsync(accessRequestsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Check access request status
   *
   * @remarks
   * Returns whether the caller has a pending access request for the document.
   */
  async checkStatus(
    request: operations.CheckAccessRequestStatusRequest,
    options?: RequestOptions,
  ): Promise<operations.CheckAccessRequestStatusResponse> {
    return unwrapAsync(accessRequestsCheckStatus(
      this,
      request,
      options,
    ));
  }

  /**
   * Approve an access request
   *
   * @remarks
   * Approve an access request.
   */
  async approve(
    request: operations.ApproveAccessRequestRequest,
    options?: RequestOptions,
  ): Promise<operations.ApproveAccessRequestResponse> {
    return unwrapAsync(accessRequestsApprove(
      this,
      request,
      options,
    ));
  }

  /**
   * Deny an access request
   *
   * @remarks
   * Deny an access request.
   */
  async deny(
    request: operations.DenyAccessRequestRequest,
    options?: RequestOptions,
  ): Promise<operations.DenyAccessRequestResponse> {
    return unwrapAsync(accessRequestsDeny(
      this,
      request,
      options,
    ));
  }

  /**
   * Inspect document access
   *
   * @remarks
   * Returns the caller's permissions and any access policies on a document.
   */
  async inspect(
    request: operations.InspectDocumentAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.InspectDocumentAccessResponse> {
    return unwrapAsync(accessRequestsInspect(
      this,
      request,
      options,
    ));
  }
}
