/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accessRequestsApproveAccessRequest } from "../funcs/accessRequestsApproveAccessRequest.js";
import { accessRequestsCheckAccessRequestStatus } from "../funcs/accessRequestsCheckAccessRequestStatus.js";
import { accessRequestsCreateAccessRequest } from "../funcs/accessRequestsCreateAccessRequest.js";
import { accessRequestsDenyAccessRequest } from "../funcs/accessRequestsDenyAccessRequest.js";
import { accessRequestsInspectDocumentAccess } from "../funcs/accessRequestsInspectDocumentAccess.js";
import { accessRequestsListAccessRequests } from "../funcs/accessRequestsListAccessRequests.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class AccessRequests extends ClientSDK {
  /**
   * Inspect document access
   *
   * @remarks
   * Returns the caller's permissions and any access policies on a document.
   */
  async inspectDocumentAccess(
    request: operations.InspectDocumentAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.InspectDocumentAccessResponse> {
    return unwrapAsync(accessRequestsInspectDocumentAccess(
      this,
      request,
      options,
    ));
  }

  /**
   * List access requests
   *
   * @remarks
   * Lists pending access requests for the specified document.
   */
  async listAccessRequests(
    request: operations.ListAccessRequestsRequest,
    options?: RequestOptions,
  ): Promise<operations.ListAccessRequestsResponse> {
    return unwrapAsync(accessRequestsListAccessRequests(
      this,
      request,
      options,
    ));
  }

  /**
   * Create an access request
   *
   * @remarks
   * Creates a new access request for the specified document.
   */
  async createAccessRequest(
    request: operations.CreateAccessRequestRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateAccessRequestResponse> {
    return unwrapAsync(accessRequestsCreateAccessRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Check access request status
   *
   * @remarks
   * Returns whether the caller has a pending access request for the document.
   */
  async checkAccessRequestStatus(
    request: operations.CheckAccessRequestStatusRequest,
    options?: RequestOptions,
  ): Promise<operations.CheckAccessRequestStatusResponse> {
    return unwrapAsync(accessRequestsCheckAccessRequestStatus(
      this,
      request,
      options,
    ));
  }

  /**
   * Approve an access request
   *
   * @remarks
   * Approve an access request.
   */
  async approveAccessRequest(
    request: operations.ApproveAccessRequestRequest,
    options?: RequestOptions,
  ): Promise<operations.ApproveAccessRequestResponse> {
    return unwrapAsync(accessRequestsApproveAccessRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Deny an access request
   *
   * @remarks
   * Deny an access request.
   */
  async denyAccessRequest(
    request: operations.DenyAccessRequestRequest,
    options?: RequestOptions,
  ): Promise<operations.DenyAccessRequestResponse> {
    return unwrapAsync(accessRequestsDenyAccessRequest(
      this,
      request,
      options,
    ));
  }
}
