/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sharingAndDistributionGenerateDocumentEntryPage } from "../funcs/sharingAndDistributionGenerateDocumentEntryPage.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class EntryPageService extends ClientSDK {
  /**
   * Generate entry page
   *
   * @remarks
   * Generate and return a temporary downloadable URL for the document entry page PDF.
   */
  async generateDocumentEntryPage(
    request: operations.GenerateDocumentEntryPageRequest,
    options?: RequestOptions,
  ): Promise<operations.GenerateDocumentEntryPageResponse> {
    return unwrapAsync(sharingAndDistributionGenerateDocumentEntryPage(
      this,
      request,
      options,
    ));
  }
}
