/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiKeysCreateAPIKey } from "../funcs/apiKeysCreateAPIKey.js";
import { apiKeysListAPIKeys } from "../funcs/apiKeysListAPIKeys.js";
import { apiKeysRevokeAPIKey } from "../funcs/apiKeysRevokeAPIKey.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class IdentityService extends ClientSDK {
  /**
   * List API keys
   *
   * @remarks
   * Lists API keys for an organization.
   */
  async listApiKeys(
    request: operations.ListApiKeysRequest,
    options?: RequestOptions,
  ): Promise<operations.ListApiKeysResponse> {
    return unwrapAsync(apiKeysListAPIKeys(
      this,
      request,
      options,
    ));
  }

  /**
   * Create an API key
   *
   * @remarks
   * Creates a new API key for the specified organization. The secret is only returned once in the response and cannot be retrieved later.
   */
  async createApiKey(
    request: components.FactifyApiV1betaCreateApiKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateApiKeyResponse> {
    return unwrapAsync(apiKeysCreateAPIKey(
      this,
      request,
      options,
    ));
  }

  /**
   * Revoke an API key
   *
   * @remarks
   * Revokes an API key, immediately preventing it from being used for authentication.
   */
  async revokeApiKey(
    request: operations.RevokeApiKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.RevokeApiKeyResponse> {
    return unwrapAsync(apiKeysRevokeAPIKey(
      this,
      request,
      options,
    ));
  }
}
