/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationsInvitesCreate } from "../funcs/organizationsInvitesCreate.js";
import { organizationsInvitesList } from "../funcs/organizationsInvitesList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Invites extends ClientSDK {
  /**
   * List organization invitations
   *
   * @remarks
   * List invitations for an organization. Requires permission to invite organization members.
   */
  async list(
    request: operations.ListOrganizationInvitesRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListOrganizationInvitesResponse, { cursor: string }>
  > {
    return unwrapResultIterator(organizationsInvitesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Invite a user to join an organization
   *
   * @remarks
   * Creates an invitation and sends an email to the specified address. Returns FAILED_PRECONDITION if the email belongs to an existing organization member. Idempotency: If a PENDING invitation already exists for this email, the existing invitation is resent with a new token and refreshed expiration. Expired or revoked invitations are ignored - a new invitation is created.
   */
  async create(
    request: operations.CreateOrganizationInviteRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateOrganizationInviteResponse> {
    return unwrapAsync(organizationsInvitesCreate(
      this,
      request,
      options,
    ));
  }
}
