/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invitesAcceptOrganizationInvite } from "../funcs/invitesAcceptOrganizationInvite.js";
import { invitesResendOrganizationInvite } from "../funcs/invitesResendOrganizationInvite.js";
import { invitesRevokeOrganizationInvite } from "../funcs/invitesRevokeOrganizationInvite.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Invites extends ClientSDK {
  /**
   * Accept an invitation
   *
   * @remarks
   * Accepts the invitation and adds the authenticated user as a member of the organization. The authenticated user's verified email must match the invitation email (case-insensitive). Returns PERMISSION_DENIED if emails don't match, FAILED_PRECONDITION if the user is already a member, or NOT_FOUND if the invitation is invalid/expired.
   */
  async acceptOrganizationInvite(
    request: operations.AcceptOrganizationInviteRequest,
    options?: RequestOptions,
  ): Promise<operations.AcceptOrganizationInviteResponse> {
    return unwrapAsync(invitesAcceptOrganizationInvite(
      this,
      request,
      options,
    ));
  }

  /**
   * Resend an invitation email
   *
   * @remarks
   * Resend an invitation email to the recipient. Useful if the original email was lost or expired. Requires permission to invite organization members.
   */
  async resendOrganizationInvite(
    request: operations.ResendOrganizationInviteRequest,
    options?: RequestOptions,
  ): Promise<operations.ResendOrganizationInviteResponse> {
    return unwrapAsync(invitesResendOrganizationInvite(
      this,
      request,
      options,
    ));
  }

  /**
   * Revoke an invitation
   *
   * @remarks
   * Revoke a pending invitation, preventing the recipient from joining. Requires permission to manage organization members.
   */
  async revokeOrganizationInvite(
    request: operations.RevokeOrganizationInviteRequest,
    options?: RequestOptions,
  ): Promise<operations.RevokeOrganizationInviteResponse> {
    return unwrapAsync(invitesRevokeOrganizationInvite(
      this,
      request,
      options,
    ));
  }
}
