/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationsMembersAdd } from "../funcs/organizationsMembersAdd.js";
import { organizationsMembersList } from "../funcs/organizationsMembersList.js";
import { organizationsMembersRemove } from "../funcs/organizationsMembersRemove.js";
import { organizationsMembersUpdate } from "../funcs/organizationsMembersUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Members extends ClientSDK {
  /**
   * List organization members
   *
   * @remarks
   * List members of an organization. Requires organization membership.
   */
  async list(
    request: operations.ListOrganizationMembersRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListOrganizationMembersResponse, { cursor: string }>
  > {
    return unwrapResultIterator(organizationsMembersList(
      this,
      request,
      options,
    ));
  }

  /**
   * Add a member to an organization
   *
   * @remarks
   * Directly adds a user as a member of an organization. Requires manage permission (owner or admin).
   */
  async add(
    request: operations.AddOrganizationMemberRequest,
    options?: RequestOptions,
  ): Promise<operations.AddOrganizationMemberResponse> {
    return unwrapAsync(organizationsMembersAdd(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove an organization member
   *
   * @remarks
   * Remove a member from an organization. Requires manage permission, or the member can remove themselves. The organization owner cannot be removed.
   */
  async remove(
    request: operations.RemoveOrganizationMemberRequest,
    options?: RequestOptions,
  ): Promise<operations.RemoveOrganizationMemberResponse> {
    return unwrapAsync(organizationsMembersRemove(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an organization member
   *
   * @remarks
   * Update a member's role within an organization. Requires manage permission (owner or admin). The organization owner's role cannot be changed.
   */
  async update(
    request: operations.UpdateOrganizationMemberRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateOrganizationMemberResponse> {
    return unwrapAsync(organizationsMembersUpdate(
      this,
      request,
      options,
    ));
  }
}
