/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationsCreateOrganization } from "../funcs/organizationsCreateOrganization.js";
import { organizationsGetOrganization } from "../funcs/organizationsGetOrganization.js";
import { organizationsListOrganizations } from "../funcs/organizationsListOrganizations.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Organizations extends ClientSDK {
  /**
   * List organizations
   *
   * @remarks
   * List organizations the caller has access to.
   */
  async listOrganizations(
    request?: operations.ListOrganizationsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListOrganizationsResponse> {
    return unwrapAsync(organizationsListOrganizations(
      this,
      request,
      options,
    ));
  }

  /**
   * Create an organization
   *
   * @remarks
   * Creates a new organization. The authenticated user becomes the organization owner.
   */
  async createOrganization(
    request: components.CreateOrganizationRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateOrganizationResponse> {
    return unwrapAsync(organizationsCreateOrganization(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve an organization
   *
   * @remarks
   * Retrieve an organization by ID.
   */
  async getOrganization(
    request: operations.GetOrganizationRequest,
    options?: RequestOptions,
  ): Promise<operations.GetOrganizationResponse> {
    return unwrapAsync(organizationsGetOrganization(
      this,
      request,
      options,
    ));
  }
}
