/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationsGet } from "../funcs/organizationsGet.js";
import { organizationsList } from "../funcs/organizationsList.js";
import { organizationsUpdateOrganization } from "../funcs/organizationsUpdateOrganization.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";
import { OrganizationsInvites } from "./organizationsinvites.js";

export class Organizations extends ClientSDK {
  private _invites?: OrganizationsInvites;
  get invites(): OrganizationsInvites {
    return (this._invites ??= new OrganizationsInvites(this._options));
  }

  /**
   * List organizations
   *
   * @remarks
   * List organizations the caller has access to.
   */
  async list(
    request?: operations.ListOrganizationsRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListOrganizationsResponse, { cursor: string }>
  > {
    return unwrapResultIterator(organizationsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve an organization
   *
   * @remarks
   * Retrieve an organization by ID.
   */
  async get(
    request: operations.GetOrganizationRequest,
    options?: RequestOptions,
  ): Promise<operations.GetOrganizationResponse> {
    return unwrapAsync(organizationsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an organization
   *
   * @remarks
   * Update an organization's display name.
   *  Authorization: Requires organization#administer permission (owner or admin).
   */
  async updateOrganization(
    request: operations.UpdateOrganizationRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateOrganizationResponse> {
    return unwrapAsync(organizationsUpdateOrganization(
      this,
      request,
      options,
    ));
  }
}
