/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { policiesAttach } from "../funcs/policiesAttach.js";
import { policiesDetach } from "../funcs/policiesDetach.js";
import { policiesList } from "../funcs/policiesList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Policies extends ClientSDK {
  /**
   * List document policies
   *
   * @remarks
   * List policies attached to a document.
   */
  async list(
    request: operations.ListDocumentPoliciesRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListDocumentPoliciesResponse, { cursor: string }>
  > {
    return unwrapResultIterator(policiesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Attach a policy
   *
   * @remarks
   * Attach a policy to a document.
   */
  async attach(
    request: operations.AttachDocumentPolicyRequest,
    options?: RequestOptions,
  ): Promise<operations.AttachDocumentPolicyResponse> {
    return unwrapAsync(policiesAttach(
      this,
      request,
      options,
    ));
  }

  /**
   * Detach a policy
   *
   * @remarks
   * Detach a policy from a document.
   */
  async detach(
    request: operations.DetachDocumentPolicyRequest,
    options?: RequestOptions,
  ): Promise<operations.DetachDocumentPolicyResponse> {
    return unwrapAsync(policiesDetach(
      this,
      request,
      options,
    ));
  }
}
