/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { quotasQuotaServiceDeleteOrganizationQuota } from "../funcs/quotasQuotaServiceDeleteOrganizationQuota.js";
import { quotasQuotaServiceSetOrganizationQuota } from "../funcs/quotasQuotaServiceSetOrganizationQuota.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Quotas extends ClientSDK {
  /**
   * DeleteOrganizationQuota removes quota configuration for an organization.  The organization will fall back to default free tier limits.  Requires platform admin permission. ConnectRPC only (not exposed via REST).
   *
   * @remarks
   * DeleteOrganizationQuota removes quota configuration for an organization.
   *  The organization will fall back to default free tier limits.
   *  Requires platform admin permission. ConnectRPC only (not exposed via REST).
   */
  async quotaServiceDeleteOrganizationQuota(
    request: operations.QuotaServiceDeleteOrganizationQuotaRequest,
    options?: RequestOptions,
  ): Promise<operations.QuotaServiceDeleteOrganizationQuotaResponse> {
    return unwrapAsync(quotasQuotaServiceDeleteOrganizationQuota(
      this,
      request,
      options,
    ));
  }

  /**
   * SetOrganizationQuota creates or updates quota configuration for an organization.  Requires platform admin permission. ConnectRPC only (not exposed via REST).
   *
   * @remarks
   * SetOrganizationQuota creates or updates quota configuration for an organization.
   *  Requires platform admin permission. ConnectRPC only (not exposed via REST).
   */
  async quotaServiceSetOrganizationQuota(
    request: operations.QuotaServiceSetOrganizationQuotaRequest,
    options?: RequestOptions,
  ): Promise<operations.QuotaServiceSetOrganizationQuotaResponse> {
    return unwrapAsync(quotasQuotaServiceSetOrganizationQuota(
      this,
      request,
      options,
    ));
  }
}
