/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { quotaGetOrganizationQuota } from "../funcs/quotaGetOrganizationQuota.js";
import { quotaGetUsageHistory } from "../funcs/quotaGetUsageHistory.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Quota extends ClientSDK {
  /**
   * Get organization quota status
   *
   * @remarks
   * Returns the current quota status for an organization including usage, limits, tier, and reset date.
   */
  async getOrganizationQuota(
    request?: operations.GetOrganizationQuotaRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetOrganizationQuotaResponse> {
    return unwrapAsync(quotaGetOrganizationQuota(
      this,
      request,
      options,
    ));
  }

  /**
   * Get usage history
   *
   * @remarks
   * Returns daily usage records for an organization within a specified date range.
   */
  async getUsageHistory(
    request?: operations.GetUsageHistoryRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetUsageHistoryResponse> {
    return unwrapAsync(quotaGetUsageHistory(
      this,
      request,
      options,
    ));
  }
}
