/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { recordsGet } from "../funcs/recordsGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Records extends ClientSDK {
  /**
   * Retrieve a record
   *
   * @remarks
   * Retrieves the processed document content record for a given version. Returns the full document and layout data.
   */
  async get(
    request: operations.GetRecordRequest,
    options?: RequestOptions,
  ): Promise<operations.GetRecordResponse> {
    return unwrapAsync(recordsGet(
      this,
      request,
      options,
    ));
  }
}
