/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { APIKeys } from "./apikeys.js";
import { DocumentService } from "./documentservice.js";
import { EntryPageService } from "./entrypageservice.js";
import { IdentityService } from "./identityservice.js";
import { Organizations } from "./organizations.js";
import { OrganizationService } from "./organizationservice.js";
import { PolicyService } from "./policyservice.js";
import { SharingAndDistribution } from "./sharinganddistribution.js";
import { VersionService } from "./versionservice.js";

export class Factify extends ClientSDK {
  private _apiKeys?: APIKeys;
  get apiKeys(): APIKeys {
    return (this._apiKeys ??= new APIKeys(this._options));
  }

  private _identityService?: IdentityService;
  get identityService(): IdentityService {
    return (this._identityService ??= new IdentityService(this._options));
  }

  private _documentService?: DocumentService;
  get documentService(): DocumentService {
    return (this._documentService ??= new DocumentService(this._options));
  }

  private _sharingAndDistribution?: SharingAndDistribution;
  get sharingAndDistribution(): SharingAndDistribution {
    return (this._sharingAndDistribution ??= new SharingAndDistribution(
      this._options,
    ));
  }

  private _entryPageService?: EntryPageService;
  get entryPageService(): EntryPageService {
    return (this._entryPageService ??= new EntryPageService(this._options));
  }

  private _policyService?: PolicyService;
  get policyService(): PolicyService {
    return (this._policyService ??= new PolicyService(this._options));
  }

  private _versionService?: VersionService;
  get versionService(): VersionService {
    return (this._versionService ??= new VersionService(this._options));
  }

  private _organizations?: Organizations;
  get organizations(): Organizations {
    return (this._organizations ??= new Organizations(this._options));
  }

  private _organizationService?: OrganizationService;
  get organizationService(): OrganizationService {
    return (this._organizationService ??= new OrganizationService(
      this._options,
    ));
  }
}
