/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Documents } from "./documents.js";
import { EntryPages } from "./entrypages.js";
import { Policies } from "./policies.js";
import { Versions } from "./versions.js";

export class Factify extends ClientSDK {
  private _documents?: Documents;
  get documents(): Documents {
    return (this._documents ??= new Documents(this._options));
  }

  private _entryPages?: EntryPages;
  get entryPages(): EntryPages {
    return (this._entryPages ??= new EntryPages(this._options));
  }

  private _policies?: Policies;
  get policies(): Policies {
    return (this._policies ??= new Policies(this._options));
  }

  private _versions?: Versions;
  get versions(): Versions {
    return (this._versions ??= new Versions(this._options));
  }
}
