/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sharingCreateShareLink } from "../funcs/sharingCreateShareLink.js";
import { sharingGetGeneralAccess } from "../funcs/sharingGetGeneralAccess.js";
import { sharingGrant } from "../funcs/sharingGrant.js";
import { sharingList } from "../funcs/sharingList.js";
import { sharingRevoke } from "../funcs/sharingRevoke.js";
import { sharingSetGeneralAccess } from "../funcs/sharingSetGeneralAccess.js";
import { sharingUpdate } from "../funcs/sharingUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Sharing extends ClientSDK {
  /**
   * Get general access
   *
   * @remarks
   * Get general access level for a document.
   */
  async getGeneralAccess(
    request: operations.GetGeneralAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.GetGeneralAccessResponse> {
    return unwrapAsync(sharingGetGeneralAccess(
      this,
      request,
      options,
    ));
  }

  /**
   * Set general access
   *
   * @remarks
   * Set general access level for a document.
   */
  async setGeneralAccess(
    request: operations.SetGeneralAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.SetGeneralAccessResponse> {
    return unwrapAsync(sharingSetGeneralAccess(
      this,
      request,
      options,
    ));
  }

  /**
   * List document access
   *
   * @remarks
   * List all recipients with access to a document.
   */
  async list(
    request: operations.ListDocumentAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.ListDocumentAccessResponse> {
    return unwrapAsync(sharingList(
      this,
      request,
      options,
    ));
  }

  /**
   * Grant document access
   *
   * @remarks
   * Grant access to one or more recipients.
   */
  async grant(
    request: operations.GrantDocumentAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.GrantDocumentAccessResponse> {
    return unwrapAsync(sharingGrant(
      this,
      request,
      options,
    ));
  }

  /**
   * Create share link
   *
   * @remarks
   * Create a share link for a document.
   */
  async createShareLink(
    request: operations.CreateShareLinkRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateShareLinkResponse> {
    return unwrapAsync(sharingCreateShareLink(
      this,
      request,
      options,
    ));
  }

  /**
   * Revoke document access
   *
   * @remarks
   * Revoke access from a recipient.
   */
  async revoke(
    request: operations.RevokeDocumentAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.RevokeDocumentAccessResponse> {
    return unwrapAsync(sharingRevoke(
      this,
      request,
      options,
    ));
  }

  /**
   * Update document access
   *
   * @remarks
   * Update a recipient's role.
   */
  async update(
    request: operations.UpdateDocumentAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateDocumentAccessResponse> {
    return unwrapAsync(sharingUpdate(
      this,
      request,
      options,
    ));
  }
}
