/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usageDeleteKeyQuota } from "../funcs/usageDeleteKeyQuota.js";
import { usageGet } from "../funcs/usageGet.js";
import { usageGetHistory } from "../funcs/usageGetHistory.js";
import { usageListKeyQuotas } from "../funcs/usageListKeyQuotas.js";
import { usageSetKeyQuota } from "../funcs/usageSetKeyQuota.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Usage extends ClientSDK {
  /**
   * Get organization quota status
   *
   * @remarks
   * Returns the current quota status for an organization including usage, limits, tier, and reset date.
   */
  async get(
    request?: operations.GetOrganizationQuotaRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetOrganizationQuotaResponse> {
    return unwrapAsync(usageGet(
      this,
      request,
      options,
    ));
  }

  /**
   * List API key quotas
   *
   * @remarks
   * Returns all per-key quota configurations and current usage for an organization.
   */
  async listKeyQuotas(
    request?: operations.ListAPIKeyQuotasRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListAPIKeyQuotasResponse> {
    return unwrapAsync(usageListKeyQuotas(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete API key quota
   *
   * @remarks
   * Removes the per-key quota limit. The key will only be subject to the organization-level quota.
   */
  async deleteKeyQuota(
    request: operations.DeleteAPIKeyQuotaRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteAPIKeyQuotaResponse> {
    return unwrapAsync(usageDeleteKeyQuota(
      this,
      request,
      options,
    ));
  }

  /**
   * Set API key quota
   *
   * @remarks
   * Creates or updates a per-key quota limit. The key will be enforced independently of the organization quota.
   */
  async setKeyQuota(
    request: operations.SetAPIKeyQuotaRequest,
    options?: RequestOptions,
  ): Promise<operations.SetAPIKeyQuotaResponse> {
    return unwrapAsync(usageSetKeyQuota(
      this,
      request,
      options,
    ));
  }

  /**
   * Get usage history
   *
   * @remarks
   * Returns daily usage records for an organization within a specified date range.
   */
  async getHistory(
    request?: operations.GetUsageHistoryRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetUsageHistoryResponse> {
    return unwrapAsync(usageGetHistory(
      this,
      request,
      options,
    ));
  }
}
