/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userPreferencesGet } from "../funcs/userPreferencesGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class UserPreferences extends ClientSDK {
  /**
   * Get user preferences
   *
   * @remarks
   * Returns the authenticated user's onboarding preferences. Only available for user accounts, not API keys.
   */
  async get(
    options?: RequestOptions,
  ): Promise<operations.GetUserPreferencesResponse> {
    return unwrapAsync(userPreferencesGet(
      this,
      options,
    ));
  }
}
