/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { versionServiceCreateDocumentVersion } from "../funcs/versionServiceCreateDocumentVersion.js";
import { versionServiceGetVersion } from "../funcs/versionServiceGetVersion.js";
import { versionServiceListDocumentVersions } from "../funcs/versionServiceListDocumentVersions.js";
import { versionServiceUpdateVersion } from "../funcs/versionServiceUpdateVersion.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class VersionService extends ClientSDK {
  /**
   * List document versions
   *
   * @remarks
   * List versions for a document with cursor-based pagination.
   */
  async listDocumentVersions(
    request: operations.ListDocumentVersionsRequest,
    options?: RequestOptions,
  ): Promise<operations.ListDocumentVersionsResponse> {
    return unwrapAsync(versionServiceListDocumentVersions(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new version
   *
   * @remarks
   * Creates a new version by uploading a PDF file.
   */
  async createDocumentVersion(
    request: operations.CreateDocumentVersionRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateDocumentVersionResponse> {
    return unwrapAsync(versionServiceCreateDocumentVersion(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a version
   *
   * @remarks
   * Retrieve a specific version by ID.
   */
  async getVersion(
    request: operations.GetVersionRequest,
    options?: RequestOptions,
  ): Promise<operations.GetVersionResponse> {
    return unwrapAsync(versionServiceGetVersion(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a version
   *
   * @remarks
   * Update version title and description.
   */
  async updateVersion(
    request: operations.UpdateVersionRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateVersionResponse> {
    return unwrapAsync(versionServiceUpdateVersion(
      this,
      request,
      options,
    ));
  }
}
