/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @factify/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx apiKeysListAPIKeys.example.ts
 */

import { Factify } from "@factify/sdk";

const factify = new Factify({
  bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
});

async function main() {
  const result = await factify.apiKeys.listApiKeys({
    organizationId: "<id>",
  });

  console.log(result);
}

main().catch(console.error);
