/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @factify/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx documentsList.example.ts
 */

import { Factify } from "@factify/sdk";

const factify = new Factify({
  bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
});

async function main() {
  const result = await factify.documents.list({
    pageToken:
      "eyJpZCI6ImRvY18wMWgyeGNlanF0ZjJuYnJleHgzdnFqaHA0MSIsImQiOiJuZXh0In0",
  });

  for await (const page of result) {
    console.log(page);
  }
}

main().catch(console.error);
