workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    factify-api:
        registry:
            location: registry.speakeasyapi.dev/factify/api/factify-api
targets:
    typescript:
        target: typescript
        source: factify-api
        output: .
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/factify/api/factify-api-typescript-code-samples
            style: standard
