workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    factify-api:
        inputs:
            - location: ./openapi.json
targets:
    typescript:
        target: typescript
        source: factify-api
        output: .
        codeSamples:
            output: codeSamples.yaml
            style: standard
