/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * AcceptOrganizationInviteRequest contains the token to accept an invitation.
 */
export type AcceptOrganizationInviteAcceptOrganizationInviteRequest = {
  /**
   * Organization the invitation belongs to (for validation).
   *
   * @remarks
   *  Pattern: org_[0-9a-hjkmnp-tv-z]{26}
   */
  organizationId: string;
  /**
   * The invitation token from the email link.
   */
  token: string;
};

export type AcceptOrganizationInviteRequest = {
  /**
   * Organization the invitation belongs to (for validation).
   *
   * @remarks
   *  Pattern: org_[0-9a-hjkmnp-tv-z]{26}
   */
  organizationId: string;
  body: AcceptOrganizationInviteAcceptOrganizationInviteRequest;
};

export type AcceptOrganizationInviteResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  factifyApiV1betaAcceptOrganizationInviteResponse?:
    | components.FactifyApiV1betaAcceptOrganizationInviteResponse
    | undefined;
};

/** @internal */
export type AcceptOrganizationInviteAcceptOrganizationInviteRequest$Outbound = {
  organization_id: string;
  token: string;
};

/** @internal */
export const AcceptOrganizationInviteAcceptOrganizationInviteRequest$outboundSchema:
  z.ZodMiniType<
    AcceptOrganizationInviteAcceptOrganizationInviteRequest$Outbound,
    AcceptOrganizationInviteAcceptOrganizationInviteRequest
  > = z.pipe(
    z.object({
      organizationId: z.string(),
      token: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        organizationId: "organization_id",
      });
    }),
  );

export function acceptOrganizationInviteAcceptOrganizationInviteRequestToJSON(
  acceptOrganizationInviteAcceptOrganizationInviteRequest:
    AcceptOrganizationInviteAcceptOrganizationInviteRequest,
): string {
  return JSON.stringify(
    AcceptOrganizationInviteAcceptOrganizationInviteRequest$outboundSchema
      .parse(acceptOrganizationInviteAcceptOrganizationInviteRequest),
  );
}

/** @internal */
export type AcceptOrganizationInviteRequest$Outbound = {
  organization_id: string;
  body: AcceptOrganizationInviteAcceptOrganizationInviteRequest$Outbound;
};

/** @internal */
export const AcceptOrganizationInviteRequest$outboundSchema: z.ZodMiniType<
  AcceptOrganizationInviteRequest$Outbound,
  AcceptOrganizationInviteRequest
> = z.pipe(
  z.object({
    organizationId: z.string(),
    body: z.lazy(() =>
      AcceptOrganizationInviteAcceptOrganizationInviteRequest$outboundSchema
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
    });
  }),
);

export function acceptOrganizationInviteRequestToJSON(
  acceptOrganizationInviteRequest: AcceptOrganizationInviteRequest,
): string {
  return JSON.stringify(
    AcceptOrganizationInviteRequest$outboundSchema.parse(
      acceptOrganizationInviteRequest,
    ),
  );
}

/** @internal */
export const AcceptOrganizationInviteResponse$inboundSchema: z.ZodMiniType<
  AcceptOrganizationInviteResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    "factify.api.v1beta.AcceptOrganizationInviteResponse": types.optional(
      components.FactifyApiV1betaAcceptOrganizationInviteResponse$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "factify.api.v1beta.AcceptOrganizationInviteResponse":
        "factifyApiV1betaAcceptOrganizationInviteResponse",
    });
  }),
);

export function acceptOrganizationInviteResponseFromJSON(
  jsonString: string,
): SafeParseResult<AcceptOrganizationInviteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AcceptOrganizationInviteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AcceptOrganizationInviteResponse' from JSON`,
  );
}
