/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * AddOrganizationMemberRequest identifies a user to add as a member.
 */
export type AddOrganizationMemberAddOrganizationMemberRequest = {
  role: components.OrganizationRole;
  /**
   * User account ID of the member to add.
   *
   * @remarks
   *  Pattern: user_[0-9a-hjkmnp-tv-z]{26}
   */
  userId: string;
};

export type AddOrganizationMemberRequest = {
  /**
   * Organization to add the member to.
   *
   * @remarks
   *  Pattern: org_[0-9a-hjkmnp-tv-z]{26}
   */
  organizationId: string;
  body: AddOrganizationMemberAddOrganizationMemberRequest;
};

export type AddOrganizationMemberResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  addOrganizationMemberResponse?:
    | components.AddOrganizationMemberResponse
    | undefined;
};

/** @internal */
export type AddOrganizationMemberAddOrganizationMemberRequest$Outbound = {
  role: string;
  user_id: string;
};

/** @internal */
export const AddOrganizationMemberAddOrganizationMemberRequest$outboundSchema:
  z.ZodMiniType<
    AddOrganizationMemberAddOrganizationMemberRequest$Outbound,
    AddOrganizationMemberAddOrganizationMemberRequest
  > = z.pipe(
    z.object({
      role: components.OrganizationRole$outboundSchema,
      userId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        userId: "user_id",
      });
    }),
  );

export function addOrganizationMemberAddOrganizationMemberRequestToJSON(
  addOrganizationMemberAddOrganizationMemberRequest:
    AddOrganizationMemberAddOrganizationMemberRequest,
): string {
  return JSON.stringify(
    AddOrganizationMemberAddOrganizationMemberRequest$outboundSchema.parse(
      addOrganizationMemberAddOrganizationMemberRequest,
    ),
  );
}

/** @internal */
export type AddOrganizationMemberRequest$Outbound = {
  organization_id: string;
  body: AddOrganizationMemberAddOrganizationMemberRequest$Outbound;
};

/** @internal */
export const AddOrganizationMemberRequest$outboundSchema: z.ZodMiniType<
  AddOrganizationMemberRequest$Outbound,
  AddOrganizationMemberRequest
> = z.pipe(
  z.object({
    organizationId: z.string(),
    body: z.lazy(() =>
      AddOrganizationMemberAddOrganizationMemberRequest$outboundSchema
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
    });
  }),
);

export function addOrganizationMemberRequestToJSON(
  addOrganizationMemberRequest: AddOrganizationMemberRequest,
): string {
  return JSON.stringify(
    AddOrganizationMemberRequest$outboundSchema.parse(
      addOrganizationMemberRequest,
    ),
  );
}

/** @internal */
export const AddOrganizationMemberResponse$inboundSchema: z.ZodMiniType<
  AddOrganizationMemberResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    AddOrganizationMemberResponse: types.optional(
      components.AddOrganizationMemberResponse$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "AddOrganizationMemberResponse": "addOrganizationMemberResponse",
    });
  }),
);

export function addOrganizationMemberResponseFromJSON(
  jsonString: string,
): SafeParseResult<AddOrganizationMemberResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddOrganizationMemberResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddOrganizationMemberResponse' from JSON`,
  );
}
