/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * ApproveAccessRequestRequest approves an access request.
 */
export type ApproveAccessRequestApproveAccessRequestRequest = {};

export type ApproveAccessRequestRequest = {
  /**
   * Document ID.
   */
  documentId: string;
  /**
   * Access request ID to approve.
   */
  accessRequestId: string;
  body: ApproveAccessRequestApproveAccessRequestRequest;
};

export type ApproveAccessRequestResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApproveAccessRequestResponse;
};

/** @internal */
export type ApproveAccessRequestApproveAccessRequestRequest$Outbound = {};

/** @internal */
export const ApproveAccessRequestApproveAccessRequestRequest$outboundSchema:
  z.ZodMiniType<
    ApproveAccessRequestApproveAccessRequestRequest$Outbound,
    ApproveAccessRequestApproveAccessRequestRequest
  > = z.object({});

export function approveAccessRequestApproveAccessRequestRequestToJSON(
  approveAccessRequestApproveAccessRequestRequest:
    ApproveAccessRequestApproveAccessRequestRequest,
): string {
  return JSON.stringify(
    ApproveAccessRequestApproveAccessRequestRequest$outboundSchema.parse(
      approveAccessRequestApproveAccessRequestRequest,
    ),
  );
}

/** @internal */
export type ApproveAccessRequestRequest$Outbound = {
  document_id: string;
  access_request_id: string;
  body: ApproveAccessRequestApproveAccessRequestRequest$Outbound;
};

/** @internal */
export const ApproveAccessRequestRequest$outboundSchema: z.ZodMiniType<
  ApproveAccessRequestRequest$Outbound,
  ApproveAccessRequestRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
    accessRequestId: z.string(),
    body: z.lazy(() =>
      ApproveAccessRequestApproveAccessRequestRequest$outboundSchema
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
      accessRequestId: "access_request_id",
    });
  }),
);

export function approveAccessRequestRequestToJSON(
  approveAccessRequestRequest: ApproveAccessRequestRequest,
): string {
  return JSON.stringify(
    ApproveAccessRequestRequest$outboundSchema.parse(
      approveAccessRequestRequest,
    ),
  );
}

/** @internal */
export const ApproveAccessRequestResponse$inboundSchema: z.ZodMiniType<
  ApproveAccessRequestResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: components.ApproveAccessRequestResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function approveAccessRequestResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApproveAccessRequestResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApproveAccessRequestResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApproveAccessRequestResponse' from JSON`,
  );
}
