/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * AttachPolicyRequest specifies a policy to attach to a document.
 */
export type AttachPolicyRequest = {
  /**
   * Document ID.
   *
   * @remarks
   *  Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
   */
  documentId?: string | undefined;
  /**
   * Policy ID to attach.
   *
   * @remarks
   *  Pattern: pol_[0-9a-hjkmnp-tv-z]{26}
   */
  policyId: string;
};

export type AttachDocumentPolicyRequest = {
  /**
   * Document ID.
   *
   * @remarks
   *  Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
   */
  documentId: string;
  body: AttachPolicyRequest;
};

export type AttachDocumentPolicyResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  factifyApiV1betaDocumentPolicy?:
    | components.FactifyApiV1betaDocumentPolicy
    | undefined;
};

/** @internal */
export type AttachPolicyRequest$Outbound = {
  document_id?: string | undefined;
  policy_id: string;
};

/** @internal */
export const AttachPolicyRequest$outboundSchema: z.ZodMiniType<
  AttachPolicyRequest$Outbound,
  AttachPolicyRequest
> = z.pipe(
  z.object({
    documentId: z.optional(z.string()),
    policyId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
      policyId: "policy_id",
    });
  }),
);

export function attachPolicyRequestToJSON(
  attachPolicyRequest: AttachPolicyRequest,
): string {
  return JSON.stringify(
    AttachPolicyRequest$outboundSchema.parse(attachPolicyRequest),
  );
}

/** @internal */
export type AttachDocumentPolicyRequest$Outbound = {
  document_id: string;
  body: AttachPolicyRequest$Outbound;
};

/** @internal */
export const AttachDocumentPolicyRequest$outboundSchema: z.ZodMiniType<
  AttachDocumentPolicyRequest$Outbound,
  AttachDocumentPolicyRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
    body: z.lazy(() => AttachPolicyRequest$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
    });
  }),
);

export function attachDocumentPolicyRequestToJSON(
  attachDocumentPolicyRequest: AttachDocumentPolicyRequest,
): string {
  return JSON.stringify(
    AttachDocumentPolicyRequest$outboundSchema.parse(
      attachDocumentPolicyRequest,
    ),
  );
}

/** @internal */
export const AttachDocumentPolicyResponse$inboundSchema: z.ZodMiniType<
  AttachDocumentPolicyResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    "factify.api.v1beta.DocumentPolicy": types.optional(
      components.FactifyApiV1betaDocumentPolicy$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "factify.api.v1beta.DocumentPolicy": "factifyApiV1betaDocumentPolicy",
    });
  }),
);

export function attachDocumentPolicyResponseFromJSON(
  jsonString: string,
): SafeParseResult<AttachDocumentPolicyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AttachDocumentPolicyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AttachDocumentPolicyResponse' from JSON`,
  );
}
