/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CheckAccessRequestStatusRequest = {
  /**
   * Document ID.
   */
  documentId: string;
};

export type CheckAccessRequestStatusResponse = {
  headers: { [k: string]: Array<string> };
  result: components.CheckAccessRequestStatusResponse;
};

/** @internal */
export type CheckAccessRequestStatusRequest$Outbound = {
  document_id: string;
};

/** @internal */
export const CheckAccessRequestStatusRequest$outboundSchema: z.ZodMiniType<
  CheckAccessRequestStatusRequest$Outbound,
  CheckAccessRequestStatusRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
    });
  }),
);

export function checkAccessRequestStatusRequestToJSON(
  checkAccessRequestStatusRequest: CheckAccessRequestStatusRequest,
): string {
  return JSON.stringify(
    CheckAccessRequestStatusRequest$outboundSchema.parse(
      checkAccessRequestStatusRequest,
    ),
  );
}

/** @internal */
export const CheckAccessRequestStatusResponse$inboundSchema: z.ZodMiniType<
  CheckAccessRequestStatusResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: components.CheckAccessRequestStatusResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function checkAccessRequestStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<CheckAccessRequestStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckAccessRequestStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckAccessRequestStatusResponse' from JSON`,
  );
}
