/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateDocumentVersionRequest = {
  /**
   * Document ID to create version for.
   *
   * @remarks
   *  Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
   */
  documentId: string;
  body: components.FactifyApiV1betaCreateVersionRequest;
};

export type CreateDocumentVersionResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  factifyApiV1betaVersion?: components.FactifyApiV1betaVersion | undefined;
};

/** @internal */
export type CreateDocumentVersionRequest$Outbound = {
  document_id: string;
  body: components.FactifyApiV1betaCreateVersionRequest$Outbound;
};

/** @internal */
export const CreateDocumentVersionRequest$outboundSchema: z.ZodMiniType<
  CreateDocumentVersionRequest$Outbound,
  CreateDocumentVersionRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
    body: components.FactifyApiV1betaCreateVersionRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
    });
  }),
);

export function createDocumentVersionRequestToJSON(
  createDocumentVersionRequest: CreateDocumentVersionRequest,
): string {
  return JSON.stringify(
    CreateDocumentVersionRequest$outboundSchema.parse(
      createDocumentVersionRequest,
    ),
  );
}

/** @internal */
export const CreateDocumentVersionResponse$inboundSchema: z.ZodMiniType<
  CreateDocumentVersionResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    "factify.api.v1beta.Version": types.optional(
      components.FactifyApiV1betaVersion$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "factify.api.v1beta.Version": "factifyApiV1betaVersion",
    });
  }),
);

export function createDocumentVersionResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateDocumentVersionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateDocumentVersionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateDocumentVersionResponse' from JSON`,
  );
}
