/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateDocumentResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  factifyApiV1betaCreateDocumentResponse?:
    | components.FactifyApiV1betaCreateDocumentResponse
    | undefined;
};

/** @internal */
export const CreateDocumentResponse$inboundSchema: z.ZodMiniType<
  CreateDocumentResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    "factify.api.v1beta.CreateDocumentResponse": types.optional(
      components.FactifyApiV1betaCreateDocumentResponse$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "factify.api.v1beta.CreateDocumentResponse":
        "factifyApiV1betaCreateDocumentResponse",
    });
  }),
);

export function createDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateDocumentResponse' from JSON`,
  );
}
