/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteAPIKeyQuotaRequest = {
  /**
   * The API key ID (required).
   */
  apiKeyId: string;
  /**
   * Optional: organization ID. If not provided, uses the caller's organization.
   */
  organizationId?: string | undefined;
};

export type DeleteAPIKeyQuotaResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  deleteAPIKeyQuotaResponse?: components.DeleteAPIKeyQuotaResponse | undefined;
};

/** @internal */
export type DeleteAPIKeyQuotaRequest$Outbound = {
  api_key_id: string;
  organization_id?: string | undefined;
};

/** @internal */
export const DeleteAPIKeyQuotaRequest$outboundSchema: z.ZodMiniType<
  DeleteAPIKeyQuotaRequest$Outbound,
  DeleteAPIKeyQuotaRequest
> = z.pipe(
  z.object({
    apiKeyId: z.string(),
    organizationId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      apiKeyId: "api_key_id",
      organizationId: "organization_id",
    });
  }),
);

export function deleteAPIKeyQuotaRequestToJSON(
  deleteAPIKeyQuotaRequest: DeleteAPIKeyQuotaRequest,
): string {
  return JSON.stringify(
    DeleteAPIKeyQuotaRequest$outboundSchema.parse(deleteAPIKeyQuotaRequest),
  );
}

/** @internal */
export const DeleteAPIKeyQuotaResponse$inboundSchema: z.ZodMiniType<
  DeleteAPIKeyQuotaResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    DeleteAPIKeyQuotaResponse: types.optional(
      components.DeleteAPIKeyQuotaResponse$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "DeleteAPIKeyQuotaResponse": "deleteAPIKeyQuotaResponse",
    });
  }),
);

export function deleteAPIKeyQuotaResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteAPIKeyQuotaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteAPIKeyQuotaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteAPIKeyQuotaResponse' from JSON`,
  );
}
