/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DetachDocumentPolicyRequest = {
  /**
   * Document ID.
   *
   * @remarks
   *  Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
   */
  documentId: string;
  /**
   * Policy ID to detach.
   *
   * @remarks
   *  Pattern: pol_[0-9a-hjkmnp-tv-z]{26}
   */
  policyId: string;
};

export type DetachDocumentPolicyResponse = {
  headers: { [k: string]: Array<string> };
  result: components.Empty;
};

/** @internal */
export type DetachDocumentPolicyRequest$Outbound = {
  document_id: string;
  policy_id: string;
};

/** @internal */
export const DetachDocumentPolicyRequest$outboundSchema: z.ZodMiniType<
  DetachDocumentPolicyRequest$Outbound,
  DetachDocumentPolicyRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
    policyId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
      policyId: "policy_id",
    });
  }),
);

export function detachDocumentPolicyRequestToJSON(
  detachDocumentPolicyRequest: DetachDocumentPolicyRequest,
): string {
  return JSON.stringify(
    DetachDocumentPolicyRequest$outboundSchema.parse(
      detachDocumentPolicyRequest,
    ),
  );
}

/** @internal */
export const DetachDocumentPolicyResponse$inboundSchema: z.ZodMiniType<
  DetachDocumentPolicyResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: components.Empty$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function detachDocumentPolicyResponseFromJSON(
  jsonString: string,
): SafeParseResult<DetachDocumentPolicyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DetachDocumentPolicyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DetachDocumentPolicyResponse' from JSON`,
  );
}
