/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GenerateDocumentEntryPageRequest = {
  /**
   * Document ID.
   *
   * @remarks
   *  Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
   */
  documentId: string;
};

export type GenerateDocumentEntryPageResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  generateEntryPageResponse?: components.GenerateEntryPageResponse | undefined;
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type GenerateDocumentEntryPageRequest$Outbound = {
  document_id: string;
};

/** @internal */
export const GenerateDocumentEntryPageRequest$outboundSchema: z.ZodMiniType<
  GenerateDocumentEntryPageRequest$Outbound,
  GenerateDocumentEntryPageRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
    });
  }),
);

export function generateDocumentEntryPageRequestToJSON(
  generateDocumentEntryPageRequest: GenerateDocumentEntryPageRequest,
): string {
  return JSON.stringify(
    GenerateDocumentEntryPageRequest$outboundSchema.parse(
      generateDocumentEntryPageRequest,
    ),
  );
}

/** @internal */
export const GenerateDocumentEntryPageResponse$inboundSchema: z.ZodMiniType<
  GenerateDocumentEntryPageResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    GenerateEntryPageResponse: types.optional(
      components.GenerateEntryPageResponse$inboundSchema,
    ),
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "GenerateEntryPageResponse": "generateEntryPageResponse",
      "Headers": "headers",
    });
  }),
);

export function generateDocumentEntryPageResponseFromJSON(
  jsonString: string,
): SafeParseResult<GenerateDocumentEntryPageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenerateDocumentEntryPageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenerateDocumentEntryPageResponse' from JSON`,
  );
}
