/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetDocumentRequest = {
  /**
   * Document ID.
   */
  documentId: string;
};

export type GetDocumentResponse = {
  headers: { [k: string]: Array<string> };
  result: components.GetDocumentResponse;
};

/** @internal */
export type GetDocumentRequest$Outbound = {
  document_id: string;
};

/** @internal */
export const GetDocumentRequest$outboundSchema: z.ZodMiniType<
  GetDocumentRequest$Outbound,
  GetDocumentRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
    });
  }),
);

export function getDocumentRequestToJSON(
  getDocumentRequest: GetDocumentRequest,
): string {
  return JSON.stringify(
    GetDocumentRequest$outboundSchema.parse(getDocumentRequest),
  );
}

/** @internal */
export const GetDocumentResponse$inboundSchema: z.ZodMiniType<
  GetDocumentResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: components.GetDocumentResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDocumentResponse' from JSON`,
  );
}
