/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetDocumentVersionRequest = {
  /**
   * Document ID.
   *
   * @remarks
   *  Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
   */
  documentId: string;
  /**
   * Version ID.
   *
   * @remarks
   *  Pattern: ver_[0-9a-hjkmnp-tv-z]{26}
   */
  versionId: string;
};

export type GetDocumentVersionResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  version?: components.Version | undefined;
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type GetDocumentVersionRequest$Outbound = {
  document_id: string;
  version_id: string;
};

/** @internal */
export const GetDocumentVersionRequest$outboundSchema: z.ZodMiniType<
  GetDocumentVersionRequest$Outbound,
  GetDocumentVersionRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
    versionId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
      versionId: "version_id",
    });
  }),
);

export function getDocumentVersionRequestToJSON(
  getDocumentVersionRequest: GetDocumentVersionRequest,
): string {
  return JSON.stringify(
    GetDocumentVersionRequest$outboundSchema.parse(getDocumentVersionRequest),
  );
}

/** @internal */
export const GetDocumentVersionResponse$inboundSchema: z.ZodMiniType<
  GetDocumentVersionResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    Version: types.optional(components.Version$inboundSchema),
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "Version": "version",
      "Headers": "headers",
    });
  }),
);

export function getDocumentVersionResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetDocumentVersionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDocumentVersionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDocumentVersionResponse' from JSON`,
  );
}
