/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetOrganizationPublicProfileRequest = {
  /**
   * Organization ID.
   *
   * @remarks
   *  Pattern: org_[0-9a-hjkmnp-tv-z]{26}
   */
  organizationId: string;
};

export type GetOrganizationPublicProfileResponse = {
  headers: { [k: string]: Array<string> };
  result: components.GetOrganizationPublicProfileResponse;
};

/** @internal */
export type GetOrganizationPublicProfileRequest$Outbound = {
  organization_id: string;
};

/** @internal */
export const GetOrganizationPublicProfileRequest$outboundSchema: z.ZodMiniType<
  GetOrganizationPublicProfileRequest$Outbound,
  GetOrganizationPublicProfileRequest
> = z.pipe(
  z.object({
    organizationId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
    });
  }),
);

export function getOrganizationPublicProfileRequestToJSON(
  getOrganizationPublicProfileRequest: GetOrganizationPublicProfileRequest,
): string {
  return JSON.stringify(
    GetOrganizationPublicProfileRequest$outboundSchema.parse(
      getOrganizationPublicProfileRequest,
    ),
  );
}

/** @internal */
export const GetOrganizationPublicProfileResponse$inboundSchema: z.ZodMiniType<
  GetOrganizationPublicProfileResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: components.GetOrganizationPublicProfileResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getOrganizationPublicProfileResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationPublicProfileResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetOrganizationPublicProfileResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationPublicProfileResponse' from JSON`,
  );
}
