/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetOrganizationQuotaRequest = {
  /**
   * Optional: organization ID to query. If not provided, uses the caller's organization.
   *
   * @remarks
   *  Only admins can query other organizations.
   */
  organizationId?: string | undefined;
};

export type GetOrganizationQuotaResponse = {
  headers: { [k: string]: Array<string> };
  result: components.GetOrganizationQuotaResponse;
};

/** @internal */
export type GetOrganizationQuotaRequest$Outbound = {
  organization_id?: string | undefined;
};

/** @internal */
export const GetOrganizationQuotaRequest$outboundSchema: z.ZodMiniType<
  GetOrganizationQuotaRequest$Outbound,
  GetOrganizationQuotaRequest
> = z.pipe(
  z.object({
    organizationId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
    });
  }),
);

export function getOrganizationQuotaRequestToJSON(
  getOrganizationQuotaRequest: GetOrganizationQuotaRequest,
): string {
  return JSON.stringify(
    GetOrganizationQuotaRequest$outboundSchema.parse(
      getOrganizationQuotaRequest,
    ),
  );
}

/** @internal */
export const GetOrganizationQuotaResponse$inboundSchema: z.ZodMiniType<
  GetOrganizationQuotaResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: components.GetOrganizationQuotaResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getOrganizationQuotaResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationQuotaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationQuotaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationQuotaResponse' from JSON`,
  );
}
