/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetUserPreferencesResponse = {
  headers: { [k: string]: Array<string> };
  result: components.GetUserPreferencesResponse;
};

/** @internal */
export const GetUserPreferencesResponse$inboundSchema: z.ZodMiniType<
  GetUserPreferencesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: components.GetUserPreferencesResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getUserPreferencesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetUserPreferencesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserPreferencesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserPreferencesResponse' from JSON`,
  );
}
