/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetVersionRequest = {
  /**
   * Version ID to retrieve.
   *
   * @remarks
   *  Pattern: ver_[0-9a-hjkmnp-tv-z]{26}
   */
  versionId: string;
};

export type GetVersionResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  version?: components.Version | undefined;
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type GetVersionRequest$Outbound = {
  version_id: string;
};

/** @internal */
export const GetVersionRequest$outboundSchema: z.ZodMiniType<
  GetVersionRequest$Outbound,
  GetVersionRequest
> = z.pipe(
  z.object({
    versionId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      versionId: "version_id",
    });
  }),
);

export function getVersionRequestToJSON(
  getVersionRequest: GetVersionRequest,
): string {
  return JSON.stringify(
    GetVersionRequest$outboundSchema.parse(getVersionRequest),
  );
}

/** @internal */
export const GetVersionResponse$inboundSchema: z.ZodMiniType<
  GetVersionResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    Version: types.optional(components.Version$inboundSchema),
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "Version": "version",
      "Headers": "headers",
    });
  }),
);

export function getVersionResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetVersionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetVersionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetVersionResponse' from JSON`,
  );
}
