/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * GrantDocumentAccessRequest grants access to one or more recipients.
 */
export type GrantDocumentAccessGrantDocumentAccessRequest = {
  /**
   * Custom message to include in the notification email.
   */
  customMessage?: string | null | undefined;
  /**
   * Recipients to grant access to (1-50).
   */
  recipients?: Array<components.RecipientGrant> | undefined;
  /**
   * Whether to send email notifications.
   */
  shouldSendNotification?: boolean | null | undefined;
};

export type GrantDocumentAccessRequest = {
  /**
   * Document ID.
   */
  documentId: string;
  body: GrantDocumentAccessGrantDocumentAccessRequest;
};

export type GrantDocumentAccessResponse = {
  headers: { [k: string]: Array<string> };
  result: components.GrantDocumentAccessResponse;
};

/** @internal */
export type GrantDocumentAccessGrantDocumentAccessRequest$Outbound = {
  custom_message?: string | null | undefined;
  recipients?: Array<components.RecipientGrant$Outbound> | undefined;
  should_send_notification?: boolean | null | undefined;
};

/** @internal */
export const GrantDocumentAccessGrantDocumentAccessRequest$outboundSchema:
  z.ZodMiniType<
    GrantDocumentAccessGrantDocumentAccessRequest$Outbound,
    GrantDocumentAccessGrantDocumentAccessRequest
  > = z.pipe(
    z.object({
      customMessage: z.optional(z.nullable(z.string())),
      recipients: z.optional(z.array(components.RecipientGrant$outboundSchema)),
      shouldSendNotification: z.optional(z.nullable(z.boolean())),
    }),
    z.transform((v) => {
      return remap$(v, {
        customMessage: "custom_message",
        shouldSendNotification: "should_send_notification",
      });
    }),
  );

export function grantDocumentAccessGrantDocumentAccessRequestToJSON(
  grantDocumentAccessGrantDocumentAccessRequest:
    GrantDocumentAccessGrantDocumentAccessRequest,
): string {
  return JSON.stringify(
    GrantDocumentAccessGrantDocumentAccessRequest$outboundSchema.parse(
      grantDocumentAccessGrantDocumentAccessRequest,
    ),
  );
}

/** @internal */
export type GrantDocumentAccessRequest$Outbound = {
  document_id: string;
  body: GrantDocumentAccessGrantDocumentAccessRequest$Outbound;
};

/** @internal */
export const GrantDocumentAccessRequest$outboundSchema: z.ZodMiniType<
  GrantDocumentAccessRequest$Outbound,
  GrantDocumentAccessRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
    body: z.lazy(() =>
      GrantDocumentAccessGrantDocumentAccessRequest$outboundSchema
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
    });
  }),
);

export function grantDocumentAccessRequestToJSON(
  grantDocumentAccessRequest: GrantDocumentAccessRequest,
): string {
  return JSON.stringify(
    GrantDocumentAccessRequest$outboundSchema.parse(grantDocumentAccessRequest),
  );
}

/** @internal */
export const GrantDocumentAccessResponse$inboundSchema: z.ZodMiniType<
  GrantDocumentAccessResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: components.GrantDocumentAccessResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function grantDocumentAccessResponseFromJSON(
  jsonString: string,
): SafeParseResult<GrantDocumentAccessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GrantDocumentAccessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GrantDocumentAccessResponse' from JSON`,
  );
}
