/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InspectDocumentAccessRequest = {
  /**
   * Document ID.
   */
  documentId: string;
};

export type InspectDocumentAccessResponse = {
  headers: { [k: string]: Array<string> };
  result: components.InspectAccessResponse;
};

/** @internal */
export type InspectDocumentAccessRequest$Outbound = {
  document_id: string;
};

/** @internal */
export const InspectDocumentAccessRequest$outboundSchema: z.ZodMiniType<
  InspectDocumentAccessRequest$Outbound,
  InspectDocumentAccessRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
    });
  }),
);

export function inspectDocumentAccessRequestToJSON(
  inspectDocumentAccessRequest: InspectDocumentAccessRequest,
): string {
  return JSON.stringify(
    InspectDocumentAccessRequest$outboundSchema.parse(
      inspectDocumentAccessRequest,
    ),
  );
}

/** @internal */
export const InspectDocumentAccessResponse$inboundSchema: z.ZodMiniType<
  InspectDocumentAccessResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: components.InspectAccessResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function inspectDocumentAccessResponseFromJSON(
  jsonString: string,
): SafeParseResult<InspectDocumentAccessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InspectDocumentAccessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InspectDocumentAccessResponse' from JSON`,
  );
}
