/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Represents seconds of UTC time since Unix epoch
 *
 * @remarks
 *  1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
 *  9999-12-31T23:59:59Z inclusive.
 */
export type ListDocumentsSeconds = number | string;

export type ListDocumentsRequest = {
  /**
   * Opaque pagination token from a previous response.
   *
   * @remarks
   *  Pass next_page_token or prev_page_token from a previous response to continue pagination.
   *  Empty or omitted for the first page.
   */
  pageToken?: string | undefined;
  /**
   * Maximum number of items to return per page (1-100). Default: 50.
   */
  pageSize?: number | undefined;
  /**
   * Represents seconds of UTC time since Unix epoch
   *
   * @remarks
   *  1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
   *  9999-12-31T23:59:59Z inclusive.
   */
  createdAfterSeconds?: number | string | undefined;
  /**
   * Non-negative fractions of a second at nanosecond resolution. Negative
   *
   * @remarks
   *  second values with fractions must still have non-negative nanos values
   *  that count forward in time. Must be from 0 to 999,999,999
   *  inclusive.
   */
  createdAfterNanos?: number | undefined;
  /**
   * Filter by creator ID(s) (user or service account). Returns documents matching ANY of the specified IDs.
   *
   * @remarks
   *  Accepts single value or comma-separated list.
   *  REST: ?created_by_id=user_01h2xcejqtf2nbrexx3vqjhp41 or ?created_by_id=user_xxx,svc_yyy
   */
  createdById?: string | undefined;
  /**
   * Filter by access level(s). Returns documents matching ANY of the specified levels.
   *
   * @remarks
   *  Accepts single value or comma-separated list.
   *  REST: ?access_level=private or ?access_level=private,organization
   *  Accepts clean enum names (case-insensitive): "private", "organization", "public"
   */
  accessLevel?: string | undefined;
  /**
   * Filter by processing status(es). Returns documents matching ANY of the specified statuses.
   *
   * @remarks
   *  Accepts single value or comma-separated list.
   *  REST: ?processing_status=ready or ?processing_status=processing,ready,failed
   *  Accepts clean enum names (case-insensitive): "processing", "ready", "failed"
   */
  processingStatus?: string | undefined;
};

export type ListDocumentsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  factifyApiV1betaListDocumentsResponse?:
    | components.FactifyApiV1betaListDocumentsResponse
    | undefined;
};

/** @internal */
export type ListDocumentsSeconds$Outbound = number | string;

/** @internal */
export const ListDocumentsSeconds$outboundSchema: z.ZodMiniType<
  ListDocumentsSeconds$Outbound,
  ListDocumentsSeconds
> = smartUnion([z.int(), z.string()]);

export function listDocumentsSecondsToJSON(
  listDocumentsSeconds: ListDocumentsSeconds,
): string {
  return JSON.stringify(
    ListDocumentsSeconds$outboundSchema.parse(listDocumentsSeconds),
  );
}

/** @internal */
export type ListDocumentsRequest$Outbound = {
  page_token?: string | undefined;
  page_size?: number | undefined;
  "created.after.seconds"?: number | string | undefined;
  "created.after.nanos"?: number | undefined;
  created_by_id?: string | undefined;
  access_level?: string | undefined;
  processing_status?: string | undefined;
};

/** @internal */
export const ListDocumentsRequest$outboundSchema: z.ZodMiniType<
  ListDocumentsRequest$Outbound,
  ListDocumentsRequest
> = z.pipe(
  z.object({
    pageToken: z.optional(z.string()),
    pageSize: z.optional(z.int()),
    createdAfterSeconds: z.optional(smartUnion([z.int(), z.string()])),
    createdAfterNanos: z.optional(z.int()),
    createdById: z.optional(z.string()),
    accessLevel: z.optional(z.string()),
    processingStatus: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      pageToken: "page_token",
      pageSize: "page_size",
      createdAfterSeconds: "created.after.seconds",
      createdAfterNanos: "created.after.nanos",
      createdById: "created_by_id",
      accessLevel: "access_level",
      processingStatus: "processing_status",
    });
  }),
);

export function listDocumentsRequestToJSON(
  listDocumentsRequest: ListDocumentsRequest,
): string {
  return JSON.stringify(
    ListDocumentsRequest$outboundSchema.parse(listDocumentsRequest),
  );
}

/** @internal */
export const ListDocumentsResponse$inboundSchema: z.ZodMiniType<
  ListDocumentsResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    "factify.api.v1beta.ListDocumentsResponse": types.optional(
      components.FactifyApiV1betaListDocumentsResponse$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "factify.api.v1beta.ListDocumentsResponse":
        "factifyApiV1betaListDocumentsResponse",
    });
  }),
);

export function listDocumentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDocumentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDocumentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDocumentsResponse' from JSON`,
  );
}
