/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListOrganizationInvitesRequest = {
  /**
   * Organization to list invitations for.
   *
   * @remarks
   *  Pattern: org_[0-9a-hjkmnp-tv-z]{26}
   */
  organizationId: string;
  /**
   * Filter by status. If empty, returns all invitations.
   *
   * @remarks
   *  ORGANIZATION_INVITE_STATUS_UNSPECIFIED (0) is not a valid filter value.
   */
  status?: Array<components.OrganizationInviteStatus> | undefined;
  /**
   * Opaque pagination token from a previous response.
   */
  pageToken?: string | undefined;
  /**
   * Maximum number of items to return per page (1-100). Default: 50.
   */
  pageSize?: number | undefined;
  /**
   * Case-insensitive substring match.
   *
   * @remarks
   *  REST: ?field.contains=value
   */
  emailContains?: string | undefined;
  /**
   * Exact match (case-sensitive).
   *
   * @remarks
   *  REST: ?field.exact=value
   */
  emailExact?: string | undefined;
  /**
   * Filter by sender. Only returns invitations sent by this user.
   *
   * @remarks
   *  REST: ?sender_id=user_01h2xcejqtf2nbrexx3vqjhp41
   *  Pattern: user_[0-9a-hjkmnp-tv-z]{26}
   */
  senderId?: string | undefined;
  /**
   * Filter by created.after (RFC 3339 format, e.g., 2024-01-15T09:30:00Z)
   */
  createdAfter?: Date | undefined;
};

export type ListOrganizationInvitesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  listOrganizationInvitesResponse?:
    | components.ListOrganizationInvitesResponse
    | undefined;
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type ListOrganizationInvitesRequest$Outbound = {
  organization_id: string;
  status?: Array<string> | undefined;
  page_token?: string | undefined;
  page_size?: number | undefined;
  "email.contains"?: string | undefined;
  "email.exact"?: string | undefined;
  sender_id?: string | undefined;
  "created.after"?: string | undefined;
};

/** @internal */
export const ListOrganizationInvitesRequest$outboundSchema: z.ZodMiniType<
  ListOrganizationInvitesRequest$Outbound,
  ListOrganizationInvitesRequest
> = z.pipe(
  z.object({
    organizationId: z.string(),
    status: z.optional(
      z.array(components.OrganizationInviteStatus$outboundSchema),
    ),
    pageToken: z.optional(z.string()),
    pageSize: z.optional(z.int()),
    emailContains: z.optional(z.string()),
    emailExact: z.optional(z.string()),
    senderId: z.optional(z.string()),
    createdAfter: z.optional(
      z.pipe(z.date(), z.transform(v => v.toISOString())),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
      pageToken: "page_token",
      pageSize: "page_size",
      emailContains: "email.contains",
      emailExact: "email.exact",
      senderId: "sender_id",
      createdAfter: "created.after",
    });
  }),
);

export function listOrganizationInvitesRequestToJSON(
  listOrganizationInvitesRequest: ListOrganizationInvitesRequest,
): string {
  return JSON.stringify(
    ListOrganizationInvitesRequest$outboundSchema.parse(
      listOrganizationInvitesRequest,
    ),
  );
}

/** @internal */
export const ListOrganizationInvitesResponse$inboundSchema: z.ZodMiniType<
  ListOrganizationInvitesResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    ListOrganizationInvitesResponse: types.optional(
      components.ListOrganizationInvitesResponse$inboundSchema,
    ),
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "ListOrganizationInvitesResponse": "listOrganizationInvitesResponse",
      "Headers": "headers",
    });
  }),
);

export function listOrganizationInvitesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListOrganizationInvitesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListOrganizationInvitesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListOrganizationInvitesResponse' from JSON`,
  );
}
