/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListAPIKeyQuotasRequest = {
  /**
   * Optional: organization ID. If not provided, uses the caller's organization.
   */
  organizationId?: string | undefined;
};

export type ListAPIKeyQuotasResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ListAPIKeyQuotasResponse;
};

/** @internal */
export type ListAPIKeyQuotasRequest$Outbound = {
  organization_id?: string | undefined;
};

/** @internal */
export const ListAPIKeyQuotasRequest$outboundSchema: z.ZodMiniType<
  ListAPIKeyQuotasRequest$Outbound,
  ListAPIKeyQuotasRequest
> = z.pipe(
  z.object({
    organizationId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
    });
  }),
);

export function listAPIKeyQuotasRequestToJSON(
  listAPIKeyQuotasRequest: ListAPIKeyQuotasRequest,
): string {
  return JSON.stringify(
    ListAPIKeyQuotasRequest$outboundSchema.parse(listAPIKeyQuotasRequest),
  );
}

/** @internal */
export const ListAPIKeyQuotasResponse$inboundSchema: z.ZodMiniType<
  ListAPIKeyQuotasResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: components.ListAPIKeyQuotasResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listAPIKeyQuotasResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAPIKeyQuotasResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAPIKeyQuotasResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAPIKeyQuotasResponse' from JSON`,
  );
}
