/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListApiKeysRequest = {
  /**
   * Organization ID to list keys for.
   *
   * @remarks
   *  Pattern: org_[0-9a-hjkmnp-tv-z]{26}
   */
  organizationId: string;
  /**
   * Whether to include revoked keys in the response.
   *
   * @remarks
   *  Default: false (only active and expired-but-not-revoked keys are returned).
   *  When true, all keys including revoked ones are returned.
   *  Note: Expired keys are always included unless also revoked; use is_active to filter.
   */
  includeRevoked?: boolean | undefined;
  /**
   * Opaque pagination token from a previous response.
   */
  pageToken?: string | undefined;
  /**
   * Maximum number of items to return per page (1-100). Default: 50.
   */
  pageSize?: number | undefined;
};

export type ListApiKeysResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  listApiKeysResponse?: components.ListApiKeysResponse | undefined;
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type ListApiKeysRequest$Outbound = {
  organization_id: string;
  include_revoked?: boolean | undefined;
  page_token?: string | undefined;
  page_size?: number | undefined;
};

/** @internal */
export const ListApiKeysRequest$outboundSchema: z.ZodMiniType<
  ListApiKeysRequest$Outbound,
  ListApiKeysRequest
> = z.pipe(
  z.object({
    organizationId: z.string(),
    includeRevoked: z.optional(z.boolean()),
    pageToken: z.optional(z.string()),
    pageSize: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
      includeRevoked: "include_revoked",
      pageToken: "page_token",
      pageSize: "page_size",
    });
  }),
);

export function listApiKeysRequestToJSON(
  listApiKeysRequest: ListApiKeysRequest,
): string {
  return JSON.stringify(
    ListApiKeysRequest$outboundSchema.parse(listApiKeysRequest),
  );
}

/** @internal */
export const ListApiKeysResponse$inboundSchema: z.ZodMiniType<
  ListApiKeysResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    ListApiKeysResponse: types.optional(
      components.ListApiKeysResponse$inboundSchema,
    ),
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "ListApiKeysResponse": "listApiKeysResponse",
      "Headers": "headers",
    });
  }),
);

export function listApiKeysResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListApiKeysResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListApiKeysResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListApiKeysResponse' from JSON`,
  );
}
