/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListDocumentAccessRequest = {
  /**
   * Document ID.
   */
  documentId: string;
};

export type ListDocumentAccessResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ListDocumentAccessResponse;
};

/** @internal */
export type ListDocumentAccessRequest$Outbound = {
  document_id: string;
};

/** @internal */
export const ListDocumentAccessRequest$outboundSchema: z.ZodMiniType<
  ListDocumentAccessRequest$Outbound,
  ListDocumentAccessRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
    });
  }),
);

export function listDocumentAccessRequestToJSON(
  listDocumentAccessRequest: ListDocumentAccessRequest,
): string {
  return JSON.stringify(
    ListDocumentAccessRequest$outboundSchema.parse(listDocumentAccessRequest),
  );
}

/** @internal */
export const ListDocumentAccessResponse$inboundSchema: z.ZodMiniType<
  ListDocumentAccessResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: components.ListDocumentAccessResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listDocumentAccessResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDocumentAccessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDocumentAccessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDocumentAccessResponse' from JSON`,
  );
}
