/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Represents seconds of UTC time since Unix epoch
 *
 * @remarks
 *  1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
 *  9999-12-31T23:59:59Z inclusive.
 */
export type ListOrganizationInvitesSeconds = number | string;

export type ListOrganizationInvitesRequest = {
  /**
   * Organization to list invitations for.
   *
   * @remarks
   *  Pattern: org_[0-9a-hjkmnp-tv-z]{26}
   */
  organizationId: string;
  /**
   * Filter by status. If empty, returns all invitations.
   *
   * @remarks
   *  ORGANIZATION_INVITE_STATUS_UNSPECIFIED (0) is not a valid filter value.
   */
  status?:
    | Array<components.FactifyApiV1betaOrganizationInviteStatus>
    | undefined;
  /**
   * Opaque pagination token from a previous response.
   */
  pageToken?: string | undefined;
  /**
   * Maximum number of items to return per page (1-100). Default: 50.
   */
  pageSize?: number | undefined;
  /**
   * Case-insensitive substring match.
   *
   * @remarks
   *  REST: ?field.contains=value
   */
  emailContains?: string | undefined;
  /**
   * Exact match (case-sensitive).
   *
   * @remarks
   *  REST: ?field.exact=value
   */
  emailExact?: string | undefined;
  /**
   * Filter by sender. Only returns invitations sent by this user.
   *
   * @remarks
   *  REST: ?sender_id=user_01h2xcejqtf2nbrexx3vqjhp41
   *  Pattern: user_[0-9a-hjkmnp-tv-z]{26}
   */
  senderId?: string | undefined;
  /**
   * Represents seconds of UTC time since Unix epoch
   *
   * @remarks
   *  1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
   *  9999-12-31T23:59:59Z inclusive.
   */
  createdAfterSeconds?: number | string | undefined;
  /**
   * Non-negative fractions of a second at nanosecond resolution. Negative
   *
   * @remarks
   *  second values with fractions must still have non-negative nanos values
   *  that count forward in time. Must be from 0 to 999,999,999
   *  inclusive.
   */
  createdAfterNanos?: number | undefined;
};

export type ListOrganizationInvitesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  factifyApiV1betaListOrganizationInvitesResponse?:
    | components.FactifyApiV1betaListOrganizationInvitesResponse
    | undefined;
};

/** @internal */
export type ListOrganizationInvitesSeconds$Outbound = number | string;

/** @internal */
export const ListOrganizationInvitesSeconds$outboundSchema: z.ZodMiniType<
  ListOrganizationInvitesSeconds$Outbound,
  ListOrganizationInvitesSeconds
> = smartUnion([z.int(), z.string()]);

export function listOrganizationInvitesSecondsToJSON(
  listOrganizationInvitesSeconds: ListOrganizationInvitesSeconds,
): string {
  return JSON.stringify(
    ListOrganizationInvitesSeconds$outboundSchema.parse(
      listOrganizationInvitesSeconds,
    ),
  );
}

/** @internal */
export type ListOrganizationInvitesRequest$Outbound = {
  organization_id: string;
  status?: Array<string> | undefined;
  page_token?: string | undefined;
  page_size?: number | undefined;
  "email.contains"?: string | undefined;
  "email.exact"?: string | undefined;
  sender_id?: string | undefined;
  "created.after.seconds"?: number | string | undefined;
  "created.after.nanos"?: number | undefined;
};

/** @internal */
export const ListOrganizationInvitesRequest$outboundSchema: z.ZodMiniType<
  ListOrganizationInvitesRequest$Outbound,
  ListOrganizationInvitesRequest
> = z.pipe(
  z.object({
    organizationId: z.string(),
    status: z.optional(
      z.array(
        components.FactifyApiV1betaOrganizationInviteStatus$outboundSchema,
      ),
    ),
    pageToken: z.optional(z.string()),
    pageSize: z.optional(z.int()),
    emailContains: z.optional(z.string()),
    emailExact: z.optional(z.string()),
    senderId: z.optional(z.string()),
    createdAfterSeconds: z.optional(smartUnion([z.int(), z.string()])),
    createdAfterNanos: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
      pageToken: "page_token",
      pageSize: "page_size",
      emailContains: "email.contains",
      emailExact: "email.exact",
      senderId: "sender_id",
      createdAfterSeconds: "created.after.seconds",
      createdAfterNanos: "created.after.nanos",
    });
  }),
);

export function listOrganizationInvitesRequestToJSON(
  listOrganizationInvitesRequest: ListOrganizationInvitesRequest,
): string {
  return JSON.stringify(
    ListOrganizationInvitesRequest$outboundSchema.parse(
      listOrganizationInvitesRequest,
    ),
  );
}

/** @internal */
export const ListOrganizationInvitesResponse$inboundSchema: z.ZodMiniType<
  ListOrganizationInvitesResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    "factify.api.v1beta.ListOrganizationInvitesResponse": types.optional(
      components.FactifyApiV1betaListOrganizationInvitesResponse$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "factify.api.v1beta.ListOrganizationInvitesResponse":
        "factifyApiV1betaListOrganizationInvitesResponse",
    });
  }),
);

export function listOrganizationInvitesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListOrganizationInvitesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListOrganizationInvitesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListOrganizationInvitesResponse' from JSON`,
  );
}
