/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListDocumentDuplicatesRequest = {
  /**
   * Document ID to check for duplicates.
   */
  documentId: string;
  /**
   * SHA256 hash of the document's visual content for duplicate matching.
   */
  fileContentsHash?: string | undefined;
};

export type ListDocumentDuplicatesResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ListDocumentDuplicatesResponse;
};

/** @internal */
export type ListDocumentDuplicatesRequest$Outbound = {
  document_id: string;
  file_contents_hash?: string | undefined;
};

/** @internal */
export const ListDocumentDuplicatesRequest$outboundSchema: z.ZodMiniType<
  ListDocumentDuplicatesRequest$Outbound,
  ListDocumentDuplicatesRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
    fileContentsHash: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
      fileContentsHash: "file_contents_hash",
    });
  }),
);

export function listDocumentDuplicatesRequestToJSON(
  listDocumentDuplicatesRequest: ListDocumentDuplicatesRequest,
): string {
  return JSON.stringify(
    ListDocumentDuplicatesRequest$outboundSchema.parse(
      listDocumentDuplicatesRequest,
    ),
  );
}

/** @internal */
export const ListDocumentDuplicatesResponse$inboundSchema: z.ZodMiniType<
  ListDocumentDuplicatesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: components.ListDocumentDuplicatesResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listDocumentDuplicatesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDocumentDuplicatesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDocumentDuplicatesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDocumentDuplicatesResponse' from JSON`,
  );
}
