/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListDocumentPoliciesRequest = {
  /**
   * Document ID.
   *
   * @remarks
   *  Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
   */
  documentId: string;
  /**
   * Opaque pagination token from a previous response.
   *
   * @remarks
   *  Pass next_page_token or prev_page_token from a previous response to continue pagination.
   *  Empty or omitted for the first page.
   */
  pageToken?: string | undefined;
  /**
   * Maximum number of items to return per page (1-100). Default: 50.
   */
  pageSize?: number | undefined;
};

export type ListDocumentPoliciesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  factifyApiV1betaListDocumentPoliciesResponse?:
    | components.FactifyApiV1betaListDocumentPoliciesResponse
    | undefined;
};

/** @internal */
export type ListDocumentPoliciesRequest$Outbound = {
  document_id: string;
  page_token?: string | undefined;
  page_size?: number | undefined;
};

/** @internal */
export const ListDocumentPoliciesRequest$outboundSchema: z.ZodMiniType<
  ListDocumentPoliciesRequest$Outbound,
  ListDocumentPoliciesRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
    pageToken: z.optional(z.string()),
    pageSize: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
      pageToken: "page_token",
      pageSize: "page_size",
    });
  }),
);

export function listDocumentPoliciesRequestToJSON(
  listDocumentPoliciesRequest: ListDocumentPoliciesRequest,
): string {
  return JSON.stringify(
    ListDocumentPoliciesRequest$outboundSchema.parse(
      listDocumentPoliciesRequest,
    ),
  );
}

/** @internal */
export const ListDocumentPoliciesResponse$inboundSchema: z.ZodMiniType<
  ListDocumentPoliciesResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    "factify.api.v1beta.ListDocumentPoliciesResponse": types.optional(
      components.FactifyApiV1betaListDocumentPoliciesResponse$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "factify.api.v1beta.ListDocumentPoliciesResponse":
        "factifyApiV1betaListDocumentPoliciesResponse",
    });
  }),
);

export function listDocumentPoliciesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDocumentPoliciesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDocumentPoliciesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDocumentPoliciesResponse' from JSON`,
  );
}
