/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * ProcessDocumentRequest triggers processing for a document version.
 */
export type ProcessDocumentProcessDocumentRequest = {
  /**
   * If true, returns immediately without waiting for processing to complete.
   */
  async?: boolean | undefined;
  /**
   * Optional version ID. If omitted, processes the current version.
   */
  versionId?: string | null | undefined;
};

export type ProcessDocumentRequest = {
  /**
   * Document ID.
   */
  documentId: string;
  body: ProcessDocumentProcessDocumentRequest;
};

export type ProcessDocumentResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ProcessDocumentResponse;
};

/** @internal */
export type ProcessDocumentProcessDocumentRequest$Outbound = {
  async?: boolean | undefined;
  version_id?: string | null | undefined;
};

/** @internal */
export const ProcessDocumentProcessDocumentRequest$outboundSchema:
  z.ZodMiniType<
    ProcessDocumentProcessDocumentRequest$Outbound,
    ProcessDocumentProcessDocumentRequest
  > = z.pipe(
    z.object({
      async: z.optional(z.boolean()),
      versionId: z.optional(z.nullable(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        versionId: "version_id",
      });
    }),
  );

export function processDocumentProcessDocumentRequestToJSON(
  processDocumentProcessDocumentRequest: ProcessDocumentProcessDocumentRequest,
): string {
  return JSON.stringify(
    ProcessDocumentProcessDocumentRequest$outboundSchema.parse(
      processDocumentProcessDocumentRequest,
    ),
  );
}

/** @internal */
export type ProcessDocumentRequest$Outbound = {
  document_id: string;
  body: ProcessDocumentProcessDocumentRequest$Outbound;
};

/** @internal */
export const ProcessDocumentRequest$outboundSchema: z.ZodMiniType<
  ProcessDocumentRequest$Outbound,
  ProcessDocumentRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
    body: z.lazy(() => ProcessDocumentProcessDocumentRequest$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
    });
  }),
);

export function processDocumentRequestToJSON(
  processDocumentRequest: ProcessDocumentRequest,
): string {
  return JSON.stringify(
    ProcessDocumentRequest$outboundSchema.parse(processDocumentRequest),
  );
}

/** @internal */
export const ProcessDocumentResponse$inboundSchema: z.ZodMiniType<
  ProcessDocumentResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: components.ProcessDocumentResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function processDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<ProcessDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProcessDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProcessDocumentResponse' from JSON`,
  );
}
