/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type QuotaServiceDeleteOrganizationQuotaRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: components.DeleteOrganizationQuotaRequest;
};

export type QuotaServiceDeleteOrganizationQuotaResponseResult =
  | components.DeleteOrganizationQuotaResponse
  | components.ConnectError;

export type QuotaServiceDeleteOrganizationQuotaResponse = {
  headers: { [k: string]: Array<string> };
  result: components.DeleteOrganizationQuotaResponse | components.ConnectError;
};

/** @internal */
export type QuotaServiceDeleteOrganizationQuotaRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: components.DeleteOrganizationQuotaRequest$Outbound;
};

/** @internal */
export const QuotaServiceDeleteOrganizationQuotaRequest$outboundSchema:
  z.ZodMiniType<
    QuotaServiceDeleteOrganizationQuotaRequest$Outbound,
    QuotaServiceDeleteOrganizationQuotaRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z.literal(1),
      connectTimeoutMs: z.optional(z.number()),
      body: components.DeleteOrganizationQuotaRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function quotaServiceDeleteOrganizationQuotaRequestToJSON(
  quotaServiceDeleteOrganizationQuotaRequest:
    QuotaServiceDeleteOrganizationQuotaRequest,
): string {
  return JSON.stringify(
    QuotaServiceDeleteOrganizationQuotaRequest$outboundSchema.parse(
      quotaServiceDeleteOrganizationQuotaRequest,
    ),
  );
}

/** @internal */
export const QuotaServiceDeleteOrganizationQuotaResponseResult$inboundSchema:
  z.ZodMiniType<QuotaServiceDeleteOrganizationQuotaResponseResult, unknown> =
    smartUnion([
      components.DeleteOrganizationQuotaResponse$inboundSchema,
      components.ConnectError$inboundSchema,
    ]);

export function quotaServiceDeleteOrganizationQuotaResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<
  QuotaServiceDeleteOrganizationQuotaResponseResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      QuotaServiceDeleteOrganizationQuotaResponseResult$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'QuotaServiceDeleteOrganizationQuotaResponseResult' from JSON`,
  );
}

/** @internal */
export const QuotaServiceDeleteOrganizationQuotaResponse$inboundSchema:
  z.ZodMiniType<QuotaServiceDeleteOrganizationQuotaResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: smartUnion([
        components.DeleteOrganizationQuotaResponse$inboundSchema,
        components.ConnectError$inboundSchema,
      ]),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function quotaServiceDeleteOrganizationQuotaResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  QuotaServiceDeleteOrganizationQuotaResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      QuotaServiceDeleteOrganizationQuotaResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'QuotaServiceDeleteOrganizationQuotaResponse' from JSON`,
  );
}
