/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type QuotaServiceSetOrganizationQuotaRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: components.SetOrganizationQuotaRequest;
};

export type QuotaServiceSetOrganizationQuotaResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  setOrganizationQuotaResponse?:
    | components.SetOrganizationQuotaResponse
    | undefined;
  /**
   * Error
   */
  connectError?: components.ConnectError | undefined;
};

/** @internal */
export type QuotaServiceSetOrganizationQuotaRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: components.SetOrganizationQuotaRequest$Outbound;
};

/** @internal */
export const QuotaServiceSetOrganizationQuotaRequest$outboundSchema:
  z.ZodMiniType<
    QuotaServiceSetOrganizationQuotaRequest$Outbound,
    QuotaServiceSetOrganizationQuotaRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z.literal(1),
      connectTimeoutMs: z.optional(z.number()),
      body: components.SetOrganizationQuotaRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function quotaServiceSetOrganizationQuotaRequestToJSON(
  quotaServiceSetOrganizationQuotaRequest:
    QuotaServiceSetOrganizationQuotaRequest,
): string {
  return JSON.stringify(
    QuotaServiceSetOrganizationQuotaRequest$outboundSchema.parse(
      quotaServiceSetOrganizationQuotaRequest,
    ),
  );
}

/** @internal */
export const QuotaServiceSetOrganizationQuotaResponse$inboundSchema:
  z.ZodMiniType<QuotaServiceSetOrganizationQuotaResponse, unknown> = z.pipe(
    z.object({
      HttpMeta: components.HTTPMetadata$inboundSchema,
      SetOrganizationQuotaResponse: types.optional(
        components.SetOrganizationQuotaResponse$inboundSchema,
      ),
      "connect.error": types.optional(components.ConnectError$inboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        "HttpMeta": "httpMeta",
        "SetOrganizationQuotaResponse": "setOrganizationQuotaResponse",
        "connect.error": "connectError",
      });
    }),
  );

export function quotaServiceSetOrganizationQuotaResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  QuotaServiceSetOrganizationQuotaResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      QuotaServiceSetOrganizationQuotaResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'QuotaServiceSetOrganizationQuotaResponse' from JSON`,
  );
}
