/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RemoveOrganizationMemberRequest = {
  /**
   * Organization to remove the member from.
   *
   * @remarks
   *  Pattern: org_[0-9a-hjkmnp-tv-z]{26}
   */
  organizationId: string;
  /**
   * User account ID of the member to remove.
   *
   * @remarks
   *  Pattern: user_[0-9a-hjkmnp-tv-z]{26}
   */
  userId: string;
};

export type RemoveOrganizationMemberResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  removeOrganizationMemberResponse?:
    | components.RemoveOrganizationMemberResponse
    | undefined;
};

/** @internal */
export type RemoveOrganizationMemberRequest$Outbound = {
  organization_id: string;
  user_id: string;
};

/** @internal */
export const RemoveOrganizationMemberRequest$outboundSchema: z.ZodMiniType<
  RemoveOrganizationMemberRequest$Outbound,
  RemoveOrganizationMemberRequest
> = z.pipe(
  z.object({
    organizationId: z.string(),
    userId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
      userId: "user_id",
    });
  }),
);

export function removeOrganizationMemberRequestToJSON(
  removeOrganizationMemberRequest: RemoveOrganizationMemberRequest,
): string {
  return JSON.stringify(
    RemoveOrganizationMemberRequest$outboundSchema.parse(
      removeOrganizationMemberRequest,
    ),
  );
}

/** @internal */
export const RemoveOrganizationMemberResponse$inboundSchema: z.ZodMiniType<
  RemoveOrganizationMemberResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    RemoveOrganizationMemberResponse: types.optional(
      components.RemoveOrganizationMemberResponse$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "RemoveOrganizationMemberResponse": "removeOrganizationMemberResponse",
    });
  }),
);

export function removeOrganizationMemberResponseFromJSON(
  jsonString: string,
): SafeParseResult<RemoveOrganizationMemberResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoveOrganizationMemberResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveOrganizationMemberResponse' from JSON`,
  );
}
