/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * ResendOrganizationInviteRequest identifies an invitation to resend.
 */
export type ResendOrganizationInviteResendOrganizationInviteRequest = {};

export type ResendOrganizationInviteRequest = {
  /**
   * Organization the invitation belongs to.
   *
   * @remarks
   *  Pattern: org_[0-9a-hjkmnp-tv-z]{26}
   */
  organizationId: string;
  /**
   * Invitation ID to resend.
   *
   * @remarks
   *  Pattern: inv_[0-9a-hjkmnp-tv-z]{26}
   */
  inviteId: string;
  body: ResendOrganizationInviteResendOrganizationInviteRequest;
};

export type ResendOrganizationInviteResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  resendOrganizationInviteResponse?:
    | components.ResendOrganizationInviteResponse
    | undefined;
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type ResendOrganizationInviteResendOrganizationInviteRequest$Outbound =
  {};

/** @internal */
export const ResendOrganizationInviteResendOrganizationInviteRequest$outboundSchema:
  z.ZodMiniType<
    ResendOrganizationInviteResendOrganizationInviteRequest$Outbound,
    ResendOrganizationInviteResendOrganizationInviteRequest
  > = z.object({});

export function resendOrganizationInviteResendOrganizationInviteRequestToJSON(
  resendOrganizationInviteResendOrganizationInviteRequest:
    ResendOrganizationInviteResendOrganizationInviteRequest,
): string {
  return JSON.stringify(
    ResendOrganizationInviteResendOrganizationInviteRequest$outboundSchema
      .parse(resendOrganizationInviteResendOrganizationInviteRequest),
  );
}

/** @internal */
export type ResendOrganizationInviteRequest$Outbound = {
  organization_id: string;
  invite_id: string;
  body: ResendOrganizationInviteResendOrganizationInviteRequest$Outbound;
};

/** @internal */
export const ResendOrganizationInviteRequest$outboundSchema: z.ZodMiniType<
  ResendOrganizationInviteRequest$Outbound,
  ResendOrganizationInviteRequest
> = z.pipe(
  z.object({
    organizationId: z.string(),
    inviteId: z.string(),
    body: z.lazy(() =>
      ResendOrganizationInviteResendOrganizationInviteRequest$outboundSchema
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
      inviteId: "invite_id",
    });
  }),
);

export function resendOrganizationInviteRequestToJSON(
  resendOrganizationInviteRequest: ResendOrganizationInviteRequest,
): string {
  return JSON.stringify(
    ResendOrganizationInviteRequest$outboundSchema.parse(
      resendOrganizationInviteRequest,
    ),
  );
}

/** @internal */
export const ResendOrganizationInviteResponse$inboundSchema: z.ZodMiniType<
  ResendOrganizationInviteResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    ResendOrganizationInviteResponse: types.optional(
      components.ResendOrganizationInviteResponse$inboundSchema,
    ),
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "ResendOrganizationInviteResponse": "resendOrganizationInviteResponse",
      "Headers": "headers",
    });
  }),
);

export function resendOrganizationInviteResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResendOrganizationInviteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResendOrganizationInviteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResendOrganizationInviteResponse' from JSON`,
  );
}
