/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * RevokeOrganizationInviteRequest identifies an invitation to revoke.
 */
export type RevokeOrganizationInviteRevokeOrganizationInviteRequest = {
  /**
   * Organization the invitation belongs to.
   *
   * @remarks
   *  Pattern: org_[0-9a-hjkmnp-tv-z]{26}
   */
  organizationId: string;
  /**
   * Invitation ID to revoke.
   *
   * @remarks
   *  Pattern: inv_[0-9a-hjkmnp-tv-z]{26}
   */
  inviteId: string;
};

export type RevokeOrganizationInviteRequest = {
  /**
   * Organization the invitation belongs to.
   *
   * @remarks
   *  Pattern: org_[0-9a-hjkmnp-tv-z]{26}
   */
  organizationId: string;
  /**
   * Invitation ID to revoke.
   *
   * @remarks
   *  Pattern: inv_[0-9a-hjkmnp-tv-z]{26}
   */
  inviteId: string;
  body: RevokeOrganizationInviteRevokeOrganizationInviteRequest;
};

export type RevokeOrganizationInviteResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  factifyApiV1betaRevokeOrganizationInviteResponse?:
    | components.FactifyApiV1betaRevokeOrganizationInviteResponse
    | undefined;
};

/** @internal */
export type RevokeOrganizationInviteRevokeOrganizationInviteRequest$Outbound = {
  organization_id: string;
  invite_id: string;
};

/** @internal */
export const RevokeOrganizationInviteRevokeOrganizationInviteRequest$outboundSchema:
  z.ZodMiniType<
    RevokeOrganizationInviteRevokeOrganizationInviteRequest$Outbound,
    RevokeOrganizationInviteRevokeOrganizationInviteRequest
  > = z.pipe(
    z.object({
      organizationId: z.string(),
      inviteId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        organizationId: "organization_id",
        inviteId: "invite_id",
      });
    }),
  );

export function revokeOrganizationInviteRevokeOrganizationInviteRequestToJSON(
  revokeOrganizationInviteRevokeOrganizationInviteRequest:
    RevokeOrganizationInviteRevokeOrganizationInviteRequest,
): string {
  return JSON.stringify(
    RevokeOrganizationInviteRevokeOrganizationInviteRequest$outboundSchema
      .parse(revokeOrganizationInviteRevokeOrganizationInviteRequest),
  );
}

/** @internal */
export type RevokeOrganizationInviteRequest$Outbound = {
  organization_id: string;
  invite_id: string;
  body: RevokeOrganizationInviteRevokeOrganizationInviteRequest$Outbound;
};

/** @internal */
export const RevokeOrganizationInviteRequest$outboundSchema: z.ZodMiniType<
  RevokeOrganizationInviteRequest$Outbound,
  RevokeOrganizationInviteRequest
> = z.pipe(
  z.object({
    organizationId: z.string(),
    inviteId: z.string(),
    body: z.lazy(() =>
      RevokeOrganizationInviteRevokeOrganizationInviteRequest$outboundSchema
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
      inviteId: "invite_id",
    });
  }),
);

export function revokeOrganizationInviteRequestToJSON(
  revokeOrganizationInviteRequest: RevokeOrganizationInviteRequest,
): string {
  return JSON.stringify(
    RevokeOrganizationInviteRequest$outboundSchema.parse(
      revokeOrganizationInviteRequest,
    ),
  );
}

/** @internal */
export const RevokeOrganizationInviteResponse$inboundSchema: z.ZodMiniType<
  RevokeOrganizationInviteResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    "factify.api.v1beta.RevokeOrganizationInviteResponse": types.optional(
      components.FactifyApiV1betaRevokeOrganizationInviteResponse$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "factify.api.v1beta.RevokeOrganizationInviteResponse":
        "factifyApiV1betaRevokeOrganizationInviteResponse",
    });
  }),
);

export function revokeOrganizationInviteResponseFromJSON(
  jsonString: string,
): SafeParseResult<RevokeOrganizationInviteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RevokeOrganizationInviteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RevokeOrganizationInviteResponse' from JSON`,
  );
}
