/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * SetAPIKeyQuotaRequest creates or updates a per-key quota.
 */
export type SetAPIKeyQuotaSetAPIKeyQuotaRequest = {
  /**
   * The limit for this key. Must be > 0.
   */
  limit?: number | null | undefined;
  /**
   * Optional: organization ID. If not provided, uses the caller's organization.
   */
  organizationId?: string | null | undefined;
};

export type SetAPIKeyQuotaRequest = {
  /**
   * The API key ID (required).
   */
  apiKeyId: string;
  body: SetAPIKeyQuotaSetAPIKeyQuotaRequest;
};

export type SetAPIKeyQuotaResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  setAPIKeyQuotaResponse?: components.SetAPIKeyQuotaResponse | undefined;
};

/** @internal */
export type SetAPIKeyQuotaSetAPIKeyQuotaRequest$Outbound = {
  limit?: number | null | undefined;
  organization_id?: string | null | undefined;
};

/** @internal */
export const SetAPIKeyQuotaSetAPIKeyQuotaRequest$outboundSchema: z.ZodMiniType<
  SetAPIKeyQuotaSetAPIKeyQuotaRequest$Outbound,
  SetAPIKeyQuotaSetAPIKeyQuotaRequest
> = z.pipe(
  z.object({
    limit: z.optional(z.nullable(z.int())),
    organizationId: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
    });
  }),
);

export function setAPIKeyQuotaSetAPIKeyQuotaRequestToJSON(
  setAPIKeyQuotaSetAPIKeyQuotaRequest: SetAPIKeyQuotaSetAPIKeyQuotaRequest,
): string {
  return JSON.stringify(
    SetAPIKeyQuotaSetAPIKeyQuotaRequest$outboundSchema.parse(
      setAPIKeyQuotaSetAPIKeyQuotaRequest,
    ),
  );
}

/** @internal */
export type SetAPIKeyQuotaRequest$Outbound = {
  api_key_id: string;
  body: SetAPIKeyQuotaSetAPIKeyQuotaRequest$Outbound;
};

/** @internal */
export const SetAPIKeyQuotaRequest$outboundSchema: z.ZodMiniType<
  SetAPIKeyQuotaRequest$Outbound,
  SetAPIKeyQuotaRequest
> = z.pipe(
  z.object({
    apiKeyId: z.string(),
    body: z.lazy(() => SetAPIKeyQuotaSetAPIKeyQuotaRequest$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      apiKeyId: "api_key_id",
    });
  }),
);

export function setAPIKeyQuotaRequestToJSON(
  setAPIKeyQuotaRequest: SetAPIKeyQuotaRequest,
): string {
  return JSON.stringify(
    SetAPIKeyQuotaRequest$outboundSchema.parse(setAPIKeyQuotaRequest),
  );
}

/** @internal */
export const SetAPIKeyQuotaResponse$inboundSchema: z.ZodMiniType<
  SetAPIKeyQuotaResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    SetAPIKeyQuotaResponse: types.optional(
      components.SetAPIKeyQuotaResponse$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "SetAPIKeyQuotaResponse": "setAPIKeyQuotaResponse",
    });
  }),
);

export function setAPIKeyQuotaResponseFromJSON(
  jsonString: string,
): SafeParseResult<SetAPIKeyQuotaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetAPIKeyQuotaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetAPIKeyQuotaResponse' from JSON`,
  );
}
