/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * SetGeneralAccessRequest sets the general access level.
 */
export type SetGeneralAccessSetGeneralAccessRequest = {
  generalAccessLevel: components.GeneralAccessLevel;
};

export type SetGeneralAccessRequest = {
  /**
   * Document ID.
   */
  documentId: string;
  body: SetGeneralAccessSetGeneralAccessRequest;
};

export type SetGeneralAccessResponse = {
  headers: { [k: string]: Array<string> };
  result: components.SetGeneralAccessResponse;
};

/** @internal */
export type SetGeneralAccessSetGeneralAccessRequest$Outbound = {
  general_access_level: string;
};

/** @internal */
export const SetGeneralAccessSetGeneralAccessRequest$outboundSchema:
  z.ZodMiniType<
    SetGeneralAccessSetGeneralAccessRequest$Outbound,
    SetGeneralAccessSetGeneralAccessRequest
  > = z.pipe(
    z.object({
      generalAccessLevel: components.GeneralAccessLevel$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        generalAccessLevel: "general_access_level",
      });
    }),
  );

export function setGeneralAccessSetGeneralAccessRequestToJSON(
  setGeneralAccessSetGeneralAccessRequest:
    SetGeneralAccessSetGeneralAccessRequest,
): string {
  return JSON.stringify(
    SetGeneralAccessSetGeneralAccessRequest$outboundSchema.parse(
      setGeneralAccessSetGeneralAccessRequest,
    ),
  );
}

/** @internal */
export type SetGeneralAccessRequest$Outbound = {
  document_id: string;
  body: SetGeneralAccessSetGeneralAccessRequest$Outbound;
};

/** @internal */
export const SetGeneralAccessRequest$outboundSchema: z.ZodMiniType<
  SetGeneralAccessRequest$Outbound,
  SetGeneralAccessRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
    body: z.lazy(() => SetGeneralAccessSetGeneralAccessRequest$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
    });
  }),
);

export function setGeneralAccessRequestToJSON(
  setGeneralAccessRequest: SetGeneralAccessRequest,
): string {
  return JSON.stringify(
    SetGeneralAccessRequest$outboundSchema.parse(setGeneralAccessRequest),
  );
}

/** @internal */
export const SetGeneralAccessResponse$inboundSchema: z.ZodMiniType<
  SetGeneralAccessResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: components.SetGeneralAccessResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function setGeneralAccessResponseFromJSON(
  jsonString: string,
): SafeParseResult<SetGeneralAccessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetGeneralAccessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetGeneralAccessResponse' from JSON`,
  );
}
