/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * UntrashDocumentRequest identifies the document to restore.
 */
export type UntrashDocumentUntrashDocumentRequest = {};

export type UntrashDocumentRequest = {
  /**
   * Document ID.
   */
  documentId: string;
  body: UntrashDocumentUntrashDocumentRequest;
};

export type UntrashDocumentResponse = {
  headers: { [k: string]: Array<string> };
  result: components.UntrashDocumentResponse;
};

/** @internal */
export type UntrashDocumentUntrashDocumentRequest$Outbound = {};

/** @internal */
export const UntrashDocumentUntrashDocumentRequest$outboundSchema:
  z.ZodMiniType<
    UntrashDocumentUntrashDocumentRequest$Outbound,
    UntrashDocumentUntrashDocumentRequest
  > = z.object({});

export function untrashDocumentUntrashDocumentRequestToJSON(
  untrashDocumentUntrashDocumentRequest: UntrashDocumentUntrashDocumentRequest,
): string {
  return JSON.stringify(
    UntrashDocumentUntrashDocumentRequest$outboundSchema.parse(
      untrashDocumentUntrashDocumentRequest,
    ),
  );
}

/** @internal */
export type UntrashDocumentRequest$Outbound = {
  document_id: string;
  body: UntrashDocumentUntrashDocumentRequest$Outbound;
};

/** @internal */
export const UntrashDocumentRequest$outboundSchema: z.ZodMiniType<
  UntrashDocumentRequest$Outbound,
  UntrashDocumentRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
    body: z.lazy(() => UntrashDocumentUntrashDocumentRequest$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
    });
  }),
);

export function untrashDocumentRequestToJSON(
  untrashDocumentRequest: UntrashDocumentRequest,
): string {
  return JSON.stringify(
    UntrashDocumentRequest$outboundSchema.parse(untrashDocumentRequest),
  );
}

/** @internal */
export const UntrashDocumentResponse$inboundSchema: z.ZodMiniType<
  UntrashDocumentResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: components.UntrashDocumentResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function untrashDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<UntrashDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UntrashDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UntrashDocumentResponse' from JSON`,
  );
}
