/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * UpdateDocumentAccessRequest updates a single recipient's role.
 */
export type UpdateDocumentAccessUpdateDocumentAccessRequest = {
  documentRole: components.DocumentRole;
};

export type UpdateDocumentAccessRequest = {
  /**
   * Document ID.
   */
  documentId: string;
  /**
   * Recipient ID (TypeID: user_xxx or bot_xxx).
   */
  recipientId: string;
  body: UpdateDocumentAccessUpdateDocumentAccessRequest;
};

export type UpdateDocumentAccessResponse = {
  headers: { [k: string]: Array<string> };
  result: components.UpdateDocumentAccessResponse;
};

/** @internal */
export type UpdateDocumentAccessUpdateDocumentAccessRequest$Outbound = {
  document_role: string;
};

/** @internal */
export const UpdateDocumentAccessUpdateDocumentAccessRequest$outboundSchema:
  z.ZodMiniType<
    UpdateDocumentAccessUpdateDocumentAccessRequest$Outbound,
    UpdateDocumentAccessUpdateDocumentAccessRequest
  > = z.pipe(
    z.object({
      documentRole: components.DocumentRole$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        documentRole: "document_role",
      });
    }),
  );

export function updateDocumentAccessUpdateDocumentAccessRequestToJSON(
  updateDocumentAccessUpdateDocumentAccessRequest:
    UpdateDocumentAccessUpdateDocumentAccessRequest,
): string {
  return JSON.stringify(
    UpdateDocumentAccessUpdateDocumentAccessRequest$outboundSchema.parse(
      updateDocumentAccessUpdateDocumentAccessRequest,
    ),
  );
}

/** @internal */
export type UpdateDocumentAccessRequest$Outbound = {
  document_id: string;
  recipient_id: string;
  body: UpdateDocumentAccessUpdateDocumentAccessRequest$Outbound;
};

/** @internal */
export const UpdateDocumentAccessRequest$outboundSchema: z.ZodMiniType<
  UpdateDocumentAccessRequest$Outbound,
  UpdateDocumentAccessRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
    recipientId: z.string(),
    body: z.lazy(() =>
      UpdateDocumentAccessUpdateDocumentAccessRequest$outboundSchema
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
      recipientId: "recipient_id",
    });
  }),
);

export function updateDocumentAccessRequestToJSON(
  updateDocumentAccessRequest: UpdateDocumentAccessRequest,
): string {
  return JSON.stringify(
    UpdateDocumentAccessRequest$outboundSchema.parse(
      updateDocumentAccessRequest,
    ),
  );
}

/** @internal */
export const UpdateDocumentAccessResponse$inboundSchema: z.ZodMiniType<
  UpdateDocumentAccessResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: components.UpdateDocumentAccessResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function updateDocumentAccessResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateDocumentAccessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateDocumentAccessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateDocumentAccessResponse' from JSON`,
  );
}
