/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * UpdateVersionRequest specifies fields to update on a version.
 */
export type UpdateVersionRequest = {
  /**
   * New description.
   */
  description?: string | null | undefined;
  /**
   * New title (max 255 characters).
   */
  title?: string | null | undefined;
};

export type UpdateDocumentVersionRequest = {
  /**
   * Document ID.
   *
   * @remarks
   *  Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
   */
  documentId: string;
  /**
   * Version ID to update.
   *
   * @remarks
   *  Pattern: ver_[0-9a-hjkmnp-tv-z]{26}
   */
  versionId: string;
  body: UpdateVersionRequest;
};

export type UpdateDocumentVersionResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  version?: components.Version | undefined;
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type UpdateVersionRequest$Outbound = {
  description?: string | null | undefined;
  title?: string | null | undefined;
};

/** @internal */
export const UpdateVersionRequest$outboundSchema: z.ZodMiniType<
  UpdateVersionRequest$Outbound,
  UpdateVersionRequest
> = z.object({
  description: z.optional(z.nullable(z.string())),
  title: z.optional(z.nullable(z.string())),
});

export function updateVersionRequestToJSON(
  updateVersionRequest: UpdateVersionRequest,
): string {
  return JSON.stringify(
    UpdateVersionRequest$outboundSchema.parse(updateVersionRequest),
  );
}

/** @internal */
export type UpdateDocumentVersionRequest$Outbound = {
  document_id: string;
  version_id: string;
  body: UpdateVersionRequest$Outbound;
};

/** @internal */
export const UpdateDocumentVersionRequest$outboundSchema: z.ZodMiniType<
  UpdateDocumentVersionRequest$Outbound,
  UpdateDocumentVersionRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
    versionId: z.string(),
    body: z.lazy(() => UpdateVersionRequest$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
      versionId: "version_id",
    });
  }),
);

export function updateDocumentVersionRequestToJSON(
  updateDocumentVersionRequest: UpdateDocumentVersionRequest,
): string {
  return JSON.stringify(
    UpdateDocumentVersionRequest$outboundSchema.parse(
      updateDocumentVersionRequest,
    ),
  );
}

/** @internal */
export const UpdateDocumentVersionResponse$inboundSchema: z.ZodMiniType<
  UpdateDocumentVersionResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    Version: types.optional(components.Version$inboundSchema),
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "Version": "version",
      "Headers": "headers",
    });
  }),
);

export function updateDocumentVersionResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateDocumentVersionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateDocumentVersionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateDocumentVersionResponse' from JSON`,
  );
}
