/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * UpdateDocumentRequest specifies fields to update on a document.
 */
export type UpdateDocumentUpdateDocumentRequest = {
  /**
   * Document ID to update.
   *
   * @remarks
   *  Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
   */
  documentId?: string | undefined;
  /**
   * New title (1-255 characters).
   */
  title?: string | null | undefined;
  /**
   * New description (max 2000 characters).
   */
  description?: string | null | undefined;
};

export type UpdateDocumentRequest = {
  /**
   * Document ID to update.
   *
   * @remarks
   *  Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
   */
  documentId: string;
  body: UpdateDocumentUpdateDocumentRequest;
};

export type UpdateDocumentResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  factifyApiV1betaUpdateDocumentResponse?:
    | components.FactifyApiV1betaUpdateDocumentResponse
    | undefined;
};

/** @internal */
export type UpdateDocumentUpdateDocumentRequest$Outbound = {
  document_id?: string | undefined;
  title?: string | null | undefined;
  description?: string | null | undefined;
};

/** @internal */
export const UpdateDocumentUpdateDocumentRequest$outboundSchema: z.ZodMiniType<
  UpdateDocumentUpdateDocumentRequest$Outbound,
  UpdateDocumentUpdateDocumentRequest
> = z.pipe(
  z.object({
    documentId: z.optional(z.string()),
    title: z.optional(z.nullable(z.string())),
    description: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
    });
  }),
);

export function updateDocumentUpdateDocumentRequestToJSON(
  updateDocumentUpdateDocumentRequest: UpdateDocumentUpdateDocumentRequest,
): string {
  return JSON.stringify(
    UpdateDocumentUpdateDocumentRequest$outboundSchema.parse(
      updateDocumentUpdateDocumentRequest,
    ),
  );
}

/** @internal */
export type UpdateDocumentRequest$Outbound = {
  document_id: string;
  body: UpdateDocumentUpdateDocumentRequest$Outbound;
};

/** @internal */
export const UpdateDocumentRequest$outboundSchema: z.ZodMiniType<
  UpdateDocumentRequest$Outbound,
  UpdateDocumentRequest
> = z.pipe(
  z.object({
    documentId: z.string(),
    body: z.lazy(() => UpdateDocumentUpdateDocumentRequest$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
    });
  }),
);

export function updateDocumentRequestToJSON(
  updateDocumentRequest: UpdateDocumentRequest,
): string {
  return JSON.stringify(
    UpdateDocumentRequest$outboundSchema.parse(updateDocumentRequest),
  );
}

/** @internal */
export const UpdateDocumentResponse$inboundSchema: z.ZodMiniType<
  UpdateDocumentResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    "factify.api.v1beta.UpdateDocumentResponse": types.optional(
      components.FactifyApiV1betaUpdateDocumentResponse$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "factify.api.v1beta.UpdateDocumentResponse":
        "factifyApiV1betaUpdateDocumentResponse",
    });
  }),
);

export function updateDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateDocumentResponse' from JSON`,
  );
}
