/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * UpdateVersionRequest specifies fields to update on a version.
 */
export type UpdateVersionUpdateVersionRequest = {
  /**
   * New description.
   */
  description?: string | null | undefined;
  /**
   * New title (max 255 characters).
   */
  title?: string | null | undefined;
};

export type UpdateVersionRequest = {
  /**
   * Version ID to update.
   *
   * @remarks
   *  Pattern: ver_[0-9a-hjkmnp-tv-z]{26}
   */
  versionId: string;
  body: UpdateVersionUpdateVersionRequest;
};

export type UpdateVersionResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  version?: components.Version | undefined;
};

/** @internal */
export type UpdateVersionUpdateVersionRequest$Outbound = {
  description?: string | null | undefined;
  title?: string | null | undefined;
};

/** @internal */
export const UpdateVersionUpdateVersionRequest$outboundSchema: z.ZodMiniType<
  UpdateVersionUpdateVersionRequest$Outbound,
  UpdateVersionUpdateVersionRequest
> = z.object({
  description: z.optional(z.nullable(z.string())),
  title: z.optional(z.nullable(z.string())),
});

export function updateVersionUpdateVersionRequestToJSON(
  updateVersionUpdateVersionRequest: UpdateVersionUpdateVersionRequest,
): string {
  return JSON.stringify(
    UpdateVersionUpdateVersionRequest$outboundSchema.parse(
      updateVersionUpdateVersionRequest,
    ),
  );
}

/** @internal */
export type UpdateVersionRequest$Outbound = {
  version_id: string;
  body: UpdateVersionUpdateVersionRequest$Outbound;
};

/** @internal */
export const UpdateVersionRequest$outboundSchema: z.ZodMiniType<
  UpdateVersionRequest$Outbound,
  UpdateVersionRequest
> = z.pipe(
  z.object({
    versionId: z.string(),
    body: z.lazy(() => UpdateVersionUpdateVersionRequest$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      versionId: "version_id",
    });
  }),
);

export function updateVersionRequestToJSON(
  updateVersionRequest: UpdateVersionRequest,
): string {
  return JSON.stringify(
    UpdateVersionRequest$outboundSchema.parse(updateVersionRequest),
  );
}

/** @internal */
export const UpdateVersionResponse$inboundSchema: z.ZodMiniType<
  UpdateVersionResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    Version: types.optional(components.Version$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "Version": "version",
    });
  }),
);

export function updateVersionResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateVersionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateVersionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateVersionResponse' from JSON`,
  );
}
