/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * UpdateOrganizationRequest contains the fields to update on an organization.
 */
export type UpdateOrganizationUpdateOrganizationRequest = {
  /**
   * Optional new display name. nil = no change. Minimum 1 character.
   */
  name?: string | null | undefined;
};

export type UpdateOrganizationRequest = {
  /**
   * Organization ID.
   *
   * @remarks
   *  Pattern: org_[0-9a-hjkmnp-tv-z]{26}
   */
  organizationId: string;
  body: UpdateOrganizationUpdateOrganizationRequest;
};

export type UpdateOrganizationResponse = {
  headers: { [k: string]: Array<string> };
  result: components.UpdateOrganizationResponse;
};

/** @internal */
export type UpdateOrganizationUpdateOrganizationRequest$Outbound = {
  name?: string | null | undefined;
};

/** @internal */
export const UpdateOrganizationUpdateOrganizationRequest$outboundSchema:
  z.ZodMiniType<
    UpdateOrganizationUpdateOrganizationRequest$Outbound,
    UpdateOrganizationUpdateOrganizationRequest
  > = z.object({
    name: z.optional(z.nullable(z.string())),
  });

export function updateOrganizationUpdateOrganizationRequestToJSON(
  updateOrganizationUpdateOrganizationRequest:
    UpdateOrganizationUpdateOrganizationRequest,
): string {
  return JSON.stringify(
    UpdateOrganizationUpdateOrganizationRequest$outboundSchema.parse(
      updateOrganizationUpdateOrganizationRequest,
    ),
  );
}

/** @internal */
export type UpdateOrganizationRequest$Outbound = {
  organization_id: string;
  body: UpdateOrganizationUpdateOrganizationRequest$Outbound;
};

/** @internal */
export const UpdateOrganizationRequest$outboundSchema: z.ZodMiniType<
  UpdateOrganizationRequest$Outbound,
  UpdateOrganizationRequest
> = z.pipe(
  z.object({
    organizationId: z.string(),
    body: z.lazy(() =>
      UpdateOrganizationUpdateOrganizationRequest$outboundSchema
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
    });
  }),
);

export function updateOrganizationRequestToJSON(
  updateOrganizationRequest: UpdateOrganizationRequest,
): string {
  return JSON.stringify(
    UpdateOrganizationRequest$outboundSchema.parse(updateOrganizationRequest),
  );
}

/** @internal */
export const UpdateOrganizationResponse$inboundSchema: z.ZodMiniType<
  UpdateOrganizationResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: components.UpdateOrganizationResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function updateOrganizationResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateOrganizationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateOrganizationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateOrganizationResponse' from JSON`,
  );
}
