name: 'Slack SDK Generation Failure Notification'
description: 'Send Slack notification when SDK generation fails'

inputs:
  webhook-url:
    description: 'Slack webhook URL for #prod-release channel'
    required: true
  sdk-name:
    description: 'Name of the SDK (e.g., TypeScript)'
    required: true
  workflow-run-url:
    description: 'URL to the workflow run'
    required: true
  commit-sha:
    description: 'Git commit SHA'
    required: true
  repository:
    description: 'SDK repository (e.g., factify-inc/factify-typescript)'
    required: true
  run-number:
    description: 'GitHub workflow run number'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Prepare failure message payload
      id: prepare-failure-message
      shell: bash
      run: |
        # Build the entire JSON payload using jq to properly escape everything
        PAYLOAD=$(jq -n \
          --arg sdk "${{ inputs.sdk-name }}" \
          --arg repo "${{ inputs.repository }}" \
          --arg commit "${{ inputs.commit-sha }}" \
          --arg runUrl "${{ inputs.workflow-run-url }}" \
          --arg runNum "${{ inputs.run-number }}" \
          '{text: "❌ *SDK Generation Failed (Run #\($runNum))*\n\n*SDK:* \($sdk)\n*Repository:* <https://github.com/\($repo)|\($repo)>\n*Commit:* <https://github.com/\($repo)/commit/\($commit)|View commit>\n*Workflow Run:* <\($runUrl)|View Run>"}')

        echo "payload<<EOF" >> $GITHUB_OUTPUT
        echo "$PAYLOAD" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Send failure notification to #prod-release
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: ${{ steps.prepare-failure-message.outputs.payload }}
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook-url }}
