/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * AccessGrantResult contains the outcome of granting access to one recipient.
 */
export type AccessGrantResult = {
  /**
   * Error message if the grant failed.
   */
  error?: string | undefined;
  /**
   * The recipient that was granted access.
   */
  recipient?: string | undefined;
  /**
   * Whether the grant succeeded.
   */
  success?: boolean | undefined;
};

/** @internal */
export const AccessGrantResult$inboundSchema: z.ZodMiniType<
  AccessGrantResult,
  unknown
> = z.object({
  error: types.optional(types.string()),
  recipient: types.optional(types.string()),
  success: types.optional(types.boolean()),
});

export function accessGrantResultFromJSON(
  jsonString: string,
): SafeParseResult<AccessGrantResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccessGrantResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccessGrantResult' from JSON`,
  );
}
