/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const AccessRequestStatus = {
  Pending: "pending",
  Approved: "approved",
  Denied: "denied",
} as const;
export type AccessRequestStatus = OpenEnum<typeof AccessRequestStatus>;

/** @internal */
export const AccessRequestStatus$inboundSchema: z.ZodMiniType<
  AccessRequestStatus,
  unknown
> = openEnums.inboundSchema(AccessRequestStatus);
