/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Organization, Organization$inboundSchema } from "./organization.js";

/**
 * AcceptOrganizationInviteResponse contains the organization the user joined.
 */
export type AcceptOrganizationInviteResponse = {
  /**
   * Organization represents a Factify organization.
   */
  organization: Organization;
};

/** @internal */
export const AcceptOrganizationInviteResponse$inboundSchema: z.ZodMiniType<
  AcceptOrganizationInviteResponse,
  unknown
> = z.object({
  organization: Organization$inboundSchema,
});

export function acceptOrganizationInviteResponseFromJSON(
  jsonString: string,
): SafeParseResult<AcceptOrganizationInviteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AcceptOrganizationInviteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AcceptOrganizationInviteResponse' from JSON`,
  );
}
