/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AccessRequestPermission,
  AccessRequestPermission$inboundSchema,
} from "./accessrequestpermission.js";
import {
  AccessRequestStatus,
  AccessRequestStatus$inboundSchema,
} from "./accessrequeststatus.js";
import { Subject, Subject$inboundSchema } from "./subject.js";

/**
 * AccessRequest represents a request for access to a document.
 */
export type AccessRequest = {
  /**
   * When the request was created.
   */
  createdAt: Date;
  /**
   * Document this request is for.
   *
   * @remarks
   *  Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
   */
  documentId: string;
  /**
   * Unique ID for the access request.
   *
   * @remarks
   *  Pattern: acr_[0-9a-hjkmnp-tv-z]{26}
   */
  id: string;
  /**
   * Optional message from the requester.
   */
  message?: string | null | undefined;
  permission: AccessRequestPermission;
  requestStatus: AccessRequestStatus;
  /**
   * Subject is a lightweight reference to either a user or a bot.
   *
   * @remarks
   *  Used in embedded fields like created_by.
   *  For full details, call GetUser or GetBot with the subject's id.
   * subject_type_matches_id_prefix // id prefix must match type (user_ for user, bot_ for bot)
   */
  subject: Subject;
  /**
   * Email of the requesting user. Denormalized for display convenience.
   */
  subjectEmail?: string | undefined;
  /**
   * When the request was last updated.
   */
  updatedAt: Date;
};

/** @internal */
export const AccessRequest$inboundSchema: z.ZodMiniType<
  AccessRequest,
  unknown
> = z.pipe(
  z.object({
    created_at: types.date(),
    document_id: types.string(),
    id: types.string(),
    message: z.optional(z.nullable(types.string())),
    permission: AccessRequestPermission$inboundSchema,
    request_status: AccessRequestStatus$inboundSchema,
    subject: Subject$inboundSchema,
    subject_email: types.optional(types.string()),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "document_id": "documentId",
      "request_status": "requestStatus",
      "subject_email": "subjectEmail",
      "updated_at": "updatedAt",
    });
  }),
);

export function accessRequestFromJSON(
  jsonString: string,
): SafeParseResult<AccessRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccessRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccessRequest' from JSON`,
  );
}
