/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * APIKeyQuota represents per-key quota status.
 */
export type APIKeyQuota = {
  /**
   * The API key ID.
   */
  apiKeyId?: string | undefined;
  /**
   * Current usage for this key in the billing period.
   */
  currentUsage?: number | undefined;
  /**
   * Whether this key's quota is exceeded. Only true when limit is set and exceeded.
   */
  isExceeded?: boolean | undefined;
  /**
   * The configured limit for this key. Not set means no explicit key limit.
   */
  limit?: number | null | undefined;
  /**
   * Remaining requests for this key. Only meaningful when limit is set.
   */
  remaining?: number | undefined;
};

/** @internal */
export const APIKeyQuota$inboundSchema: z.ZodMiniType<APIKeyQuota, unknown> = z
  .pipe(
    z.object({
      api_key_id: types.optional(types.string()),
      current_usage: types.optional(types.number()),
      is_exceeded: types.optional(types.boolean()),
      limit: z.optional(z.nullable(types.number())),
      remaining: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "api_key_id": "apiKeyId",
        "current_usage": "currentUsage",
        "is_exceeded": "isExceeded",
      });
    }),
  );

export function apiKeyQuotaFromJSON(
  jsonString: string,
): SafeParseResult<APIKeyQuota, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => APIKeyQuota$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'APIKeyQuota' from JSON`,
  );
}
