/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * ApiKey represents an authentication credential for programmatic API access.
 */
export type ApiKey = {
  /**
   * Timestamp when the key was created.
   */
  createdAt: Date;
  /**
   * Expiration timestamp. If set, the key becomes invalid after this time.
   */
  expiresAt?: Date | undefined;
  /**
   * Unique ID for the API key.
   *
   * @remarks
   *  Pattern: key_[0-9a-hjkmnp-tv-z]{26}
   */
  id: string;
  /**
   * Whether the key is currently active (not revoked and not expired).
   *
   * @remarks
   *  Computed: is_active = (revoked_at == null) && (expires_at == null || expires_at > now())
   */
  isActive: boolean;
  /**
   * Truncated key prefix for identification in UI (e.g., "ffy_prod_01jd4h5...").
   *
   * @remarks
   *  Shows the first 16 characters for better uniqueness while maintaining security.
   */
  keyPrefix: string;
  /**
   * Human-readable name for the key (e.g., "Production", "Staging").
   */
  name: string;
  /**
   * ID of the organization this key belongs to.
   *
   * @remarks
   *  Pattern: org_[0-9a-hjkmnp-tv-z]{26}
   */
  organizationId: string;
  /**
   * Timestamp when the key was revoked. Null if the key has not been revoked.
   */
  revokedAt?: Date | undefined;
};

/** @internal */
export const ApiKey$inboundSchema: z.ZodMiniType<ApiKey, unknown> = z.pipe(
  z.object({
    created_at: types.date(),
    expires_at: types.optional(types.date()),
    id: types.string(),
    is_active: types.boolean(),
    key_prefix: types.string(),
    name: types.string(),
    organization_id: types.string(),
    revoked_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "expires_at": "expiresAt",
      "is_active": "isActive",
      "key_prefix": "keyPrefix",
      "organization_id": "organizationId",
      "revoked_at": "revokedAt",
    });
  }),
);

export function apiKeyFromJSON(
  jsonString: string,
): SafeParseResult<ApiKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiKey' from JSON`,
  );
}
