/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * CheckAccessRequestStatusResponse returns whether the caller has a pending request.
 */
export type CheckAccessRequestStatusResponse = {
  hasPendingRequest?: boolean | undefined;
};

/** @internal */
export const CheckAccessRequestStatusResponse$inboundSchema: z.ZodMiniType<
  CheckAccessRequestStatusResponse,
  unknown
> = z.pipe(
  z.object({
    has_pending_request: types.optional(types.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_pending_request": "hasPendingRequest",
    });
  }),
);

export function checkAccessRequestStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<CheckAccessRequestStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckAccessRequestStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckAccessRequestStatusResponse' from JSON`,
  );
}
