/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ConnectErrorDetailsAny,
  ConnectErrorDetailsAny$inboundSchema,
} from "./connecterrordetailsany.js";

/**
 * The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
 */
export const ConnectErrorCode = {
  Canceled: "canceled",
  Unknown: "unknown",
  InvalidArgument: "invalid_argument",
  DeadlineExceeded: "deadline_exceeded",
  NotFound: "not_found",
  AlreadyExists: "already_exists",
  PermissionDenied: "permission_denied",
  ResourceExhausted: "resource_exhausted",
  FailedPrecondition: "failed_precondition",
  Aborted: "aborted",
  OutOfRange: "out_of_range",
  Unimplemented: "unimplemented",
  Internal: "internal",
  Unavailable: "unavailable",
  DataLoss: "data_loss",
  Unauthenticated: "unauthenticated",
} as const;
/**
 * The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
 */
export type ConnectErrorCode = OpenEnum<typeof ConnectErrorCode>;

/**
 * Error type returned by Connect: https://connectrpc.com/docs/go/errors/#http-representation
 */
export type ConnectError = {
  /**
   * The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
   */
  code?: ConnectErrorCode | undefined;
  /**
   * A list of messages that carry the error details. There is no limit on the number of messages.
   */
  details?: Array<ConnectErrorDetailsAny> | undefined;
  /**
   * A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
   */
  message?: string | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const ConnectErrorCode$inboundSchema: z.ZodMiniType<
  ConnectErrorCode,
  unknown
> = openEnums.inboundSchema(ConnectErrorCode);

/** @internal */
export const ConnectError$inboundSchema: z.ZodMiniType<ConnectError, unknown> =
  collectExtraKeys$(
    z.catchall(
      z.object({
        code: types.optional(ConnectErrorCode$inboundSchema),
        details: types.optional(z.array(ConnectErrorDetailsAny$inboundSchema)),
        message: types.optional(types.string()),
      }),
      z.any(),
    ),
    "additionalProperties",
    true,
  );

export function connectErrorFromJSON(
  jsonString: string,
): SafeParseResult<ConnectError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConnectError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConnectError' from JSON`,
  );
}
