/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as b64$ from "../../lib/base64.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Deserialized error detail payload. The 'type' field indicates the schema. This field is for easier debugging and should not be relied upon for application logic.
 */
export type Debug = { [k: string]: any };

/**
 * Contains an arbitrary serialized message along with a @type that describes the type of the serialized message, with an additional debug field for ConnectRPC error details.
 */
export type ConnectErrorDetailsAny = {
  /**
   * Deserialized error detail payload. The 'type' field indicates the schema. This field is for easier debugging and should not be relied upon for application logic.
   */
  debug?: { [k: string]: any } | undefined;
  /**
   * A URL that acts as a globally unique identifier for the type of the serialized message. For example: `type.googleapis.com/google.rpc.ErrorInfo`. This is used to determine the schema of the data in the `value` field and is the discriminator for the `debug` field.
   */
  type?: string | undefined;
  /**
   * The Protobuf message, serialized as bytes and base64-encoded. The specific message type is identified by the `type` field.
   */
  value?: Uint8Array | string | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const Debug$inboundSchema: z.ZodMiniType<Debug, unknown> = z.record(
  z.string(),
  z.any(),
);

export function debugFromJSON(
  jsonString: string,
): SafeParseResult<Debug, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Debug$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Debug' from JSON`,
  );
}

/** @internal */
export const ConnectErrorDetailsAny$inboundSchema: z.ZodMiniType<
  ConnectErrorDetailsAny,
  unknown
> = collectExtraKeys$(
  z.catchall(
    z.object({
      debug: types.optional(z.record(z.string(), z.any())),
      type: types.optional(types.string()),
      value: types.optional(b64$.zodInbound),
    }),
    z.any(),
  ),
  "additionalProperties",
  true,
);

export function connectErrorDetailsAnyFromJSON(
  jsonString: string,
): SafeParseResult<ConnectErrorDetailsAny, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConnectErrorDetailsAny$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConnectErrorDetailsAny' from JSON`,
  );
}
