/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * CreateOrganizationRequest contains the data needed to create a new organization.
 */
export type CreateOrganizationRequest = {
  /**
   * Human-readable organization name.
   */
  name: string;
  /**
   * Owner user ID. If not provided, the authenticated user becomes the owner.
   *
   * @remarks
   *  Authorization: Specifying a different user requires system maintainer role.
   *  Required when the caller is a service account (service accounts cannot own organizations).
   *  Pattern: user_[0-9a-hjkmnp-tv-z]{26}
   */
  ownerUserId?: string | undefined;
};

/** @internal */
export type CreateOrganizationRequest$Outbound = {
  name: string;
  owner_user_id?: string | undefined;
};

/** @internal */
export const CreateOrganizationRequest$outboundSchema: z.ZodMiniType<
  CreateOrganizationRequest$Outbound,
  CreateOrganizationRequest
> = z.pipe(
  z.object({
    name: z.string(),
    ownerUserId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      ownerUserId: "owner_user_id",
    });
  }),
);

export function createOrganizationRequestToJSON(
  createOrganizationRequest: CreateOrganizationRequest,
): string {
  return JSON.stringify(
    CreateOrganizationRequest$outboundSchema.parse(createOrganizationRequest),
  );
}
