/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { AccessRequest, AccessRequest$inboundSchema } from "./accessrequest.js";

/**
 * CreateAccessRequestResponse contains the created access request.
 */
export type CreateAccessRequestResponse = {
  /**
   * AccessRequest represents a request for access to a document.
   */
  accessRequest: AccessRequest;
};

/** @internal */
export const CreateAccessRequestResponse$inboundSchema: z.ZodMiniType<
  CreateAccessRequestResponse,
  unknown
> = z.pipe(
  z.object({
    access_request: AccessRequest$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "access_request": "accessRequest",
    });
  }),
);

export function createAccessRequestResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateAccessRequestResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAccessRequestResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAccessRequestResponse' from JSON`,
  );
}
