/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  OrganizationInvite,
  OrganizationInvite$inboundSchema,
} from "./organizationinvite.js";

/**
 * CreateOrganizationInviteResponse contains the created invitation.
 */
export type CreateOrganizationInviteResponse = {
  /**
   * OrganizationInvite represents an invitation to join an organization.
   *
   * @remarks
   * accepted_fields_consistency // accepted_at and accepted_by must both be set or both be unset
   */
  invite: OrganizationInvite;
};

/** @internal */
export const CreateOrganizationInviteResponse$inboundSchema: z.ZodMiniType<
  CreateOrganizationInviteResponse,
  unknown
> = z.object({
  invite: OrganizationInvite$inboundSchema,
});

export function createOrganizationInviteResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateOrganizationInviteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateOrganizationInviteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateOrganizationInviteResponse' from JSON`,
  );
}
