/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { ApiKey, ApiKey$inboundSchema } from "./apikey.js";

/**
 * CreateApiKeyResponse contains the newly created API key and its secret.
 */
export type CreateApiKeyResponse = {
  /**
   * ApiKey represents an authentication credential for programmatic API access.
   */
  apiKey: ApiKey;
  /**
   * The API key secret. This is only returned once and cannot be retrieved later.
   *
   * @remarks
   *  Format: ffy_{env}_{base32_uuid7}{base62_random}
   *  - env: "prod" or "test"
   *  - base32_uuid7: 26 chars (TypeID base32 alphabet: 0-9a-hjkmnp-tv-z)
   *  - base62_random: 43 chars (0-9A-Za-z)
   *  Store this value securely - it will not be shown again.
   *  SECURITY WARNING: This field must NEVER be logged. Handlers must redact secrets from all logs.
   */
  secret: string;
};

/** @internal */
export const CreateApiKeyResponse$inboundSchema: z.ZodMiniType<
  CreateApiKeyResponse,
  unknown
> = z.pipe(
  z.object({
    api_key: ApiKey$inboundSchema,
    secret: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "api_key": "apiKey",
    });
  }),
);

export function createApiKeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateApiKeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateApiKeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateApiKeyResponse' from JSON`,
  );
}
