/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { ShareLink, ShareLink$inboundSchema } from "./sharelink.js";

/**
 * CreateShareLinkResponse contains the created share link.
 */
export type CreateShareLinkResponse = {
  /**
   * ShareLink represents a shareable link for a document.
   */
  shareLink?: ShareLink | undefined;
  /**
   * Shortened URL for the share link (if available).
   */
  shortUrl?: string | null | undefined;
};

/** @internal */
export const CreateShareLinkResponse$inboundSchema: z.ZodMiniType<
  CreateShareLinkResponse,
  unknown
> = z.pipe(
  z.object({
    share_link: types.optional(ShareLink$inboundSchema),
    short_url: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "share_link": "shareLink",
      "short_url": "shortUrl",
    });
  }),
);

export function createShareLinkResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateShareLinkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateShareLinkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateShareLinkResponse' from JSON`,
  );
}
