/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { blobLikeSchema } from "../../types/blobs.js";

export type CreateVersionRequestPayload = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/**
 * CreateVersionRequest contains the file and metadata for creating a version.
 */
export type CreateVersionRequest = {
  /**
   * Description of changes in this version.
   */
  description?: string | null | undefined;
  /**
   * Document ID to create version for.
   *
   * @remarks
   *  Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
   */
  documentId?: string | undefined;
  /**
   * PDF file for new version
   */
  payload: CreateVersionRequestPayload | Blob;
  /**
   * Optional version title.
   */
  title?: string | null | undefined;
};

/** @internal */
export type CreateVersionRequestPayload$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const CreateVersionRequestPayload$outboundSchema: z.ZodMiniType<
  CreateVersionRequestPayload$Outbound,
  CreateVersionRequestPayload
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.custom<Blob>(x => x instanceof Blob),
    z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
    z.custom<Uint8Array>(x => x instanceof Uint8Array),
  ]),
});

export function createVersionRequestPayloadToJSON(
  createVersionRequestPayload: CreateVersionRequestPayload,
): string {
  return JSON.stringify(
    CreateVersionRequestPayload$outboundSchema.parse(
      createVersionRequestPayload,
    ),
  );
}

/** @internal */
export type CreateVersionRequest$Outbound = {
  description?: string | null | undefined;
  document_id?: string | undefined;
  payload: CreateVersionRequestPayload$Outbound | Blob;
  title?: string | null | undefined;
};

/** @internal */
export const CreateVersionRequest$outboundSchema: z.ZodMiniType<
  CreateVersionRequest$Outbound,
  CreateVersionRequest
> = z.pipe(
  z.object({
    description: z.optional(z.nullable(z.string())),
    documentId: z.optional(z.string()),
    payload: z.union([
      z.lazy(() => CreateVersionRequestPayload$outboundSchema),
      blobLikeSchema,
    ]),
    title: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      documentId: "document_id",
    });
  }),
);

export function createVersionRequestToJSON(
  createVersionRequest: CreateVersionRequest,
): string {
  return JSON.stringify(
    CreateVersionRequest$outboundSchema.parse(createVersionRequest),
  );
}
