/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { blobLikeSchema } from "../../types/blobs.js";

export type CreateVersionRequestPayload = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/**
 * CreateVersionRequest contains the file and metadata for creating a version.
 */
export type CreateVersionRequest = {
  /**
   * Description of changes in this version.
   */
  description?: string | null | undefined;
  /**
   * PDF file for new version
   */
  payload: CreateVersionRequestPayload | Blob;
  /**
   * Optional version title.
   */
  title?: string | null | undefined;
};

/** @internal */
export type CreateVersionRequestPayload$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const CreateVersionRequestPayload$outboundSchema: z.ZodMiniType<
  CreateVersionRequestPayload$Outbound,
  CreateVersionRequestPayload
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.custom<Blob>(x => x instanceof Blob),
    z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
    z.custom<Uint8Array>(x => x instanceof Uint8Array),
  ]),
});

export function createVersionRequestPayloadToJSON(
  createVersionRequestPayload: CreateVersionRequestPayload,
): string {
  return JSON.stringify(
    CreateVersionRequestPayload$outboundSchema.parse(
      createVersionRequestPayload,
    ),
  );
}

/** @internal */
export type CreateVersionRequest$Outbound = {
  description?: string | null | undefined;
  payload: CreateVersionRequestPayload$Outbound | Blob;
  title?: string | null | undefined;
};

/** @internal */
export const CreateVersionRequest$outboundSchema: z.ZodMiniType<
  CreateVersionRequest$Outbound,
  CreateVersionRequest
> = z.object({
  description: z.optional(z.nullable(z.string())),
  payload: z.union([
    z.lazy(() => CreateVersionRequestPayload$outboundSchema),
    blobLikeSchema,
  ]),
  title: z.optional(z.nullable(z.string())),
});

export function createVersionRequestToJSON(
  createVersionRequest: CreateVersionRequest,
): string {
  return JSON.stringify(
    CreateVersionRequest$outboundSchema.parse(createVersionRequest),
  );
}
