/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * CreateApiKeyRequest contains the data needed to create a new API key.
 */
export type CreateApiKeyRequest = {
  /**
   * Expiration timestamp. If not set, the key does not expire.
   *
   * @remarks
   *  When set, must be in the future and within 1 year.
   *  Security note: Keys without expiration should be rotated periodically.
   * timestamp.gt_now = true
   * timestamp.within = 8760h0m0s
   */
  expiresAt?: Date | undefined;
  /**
   * Human-readable name for the key (e.g., "Production", "Staging").
   */
  name: string;
  /**
   * Organization ID to create the key for.
   *
   * @remarks
   *  Pattern: org_[0-9a-hjkmnp-tv-z]{26}
   */
  organizationId: string;
};

/** @internal */
export type CreateApiKeyRequest$Outbound = {
  expires_at?: string | undefined;
  name: string;
  organization_id: string;
};

/** @internal */
export const CreateApiKeyRequest$outboundSchema: z.ZodMiniType<
  CreateApiKeyRequest$Outbound,
  CreateApiKeyRequest
> = z.pipe(
  z.object({
    expiresAt: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    name: z.string(),
    organizationId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      expiresAt: "expires_at",
      organizationId: "organization_id",
    });
  }),
);

export function createApiKeyRequestToJSON(
  createApiKeyRequest: CreateApiKeyRequest,
): string {
  return JSON.stringify(
    CreateApiKeyRequest$outboundSchema.parse(createApiKeyRequest),
  );
}
