/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * DeleteOrganizationQuotaRequest is a request to delete quota configuration.
 */
export type DeleteOrganizationQuotaRequest = {
  /**
   * The organization ID (required).
   */
  organizationId?: string | undefined;
};

/** @internal */
export type DeleteOrganizationQuotaRequest$Outbound = {
  organization_id?: string | undefined;
};

/** @internal */
export const DeleteOrganizationQuotaRequest$outboundSchema: z.ZodMiniType<
  DeleteOrganizationQuotaRequest$Outbound,
  DeleteOrganizationQuotaRequest
> = z.pipe(
  z.object({
    organizationId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
    });
  }),
);

export function deleteOrganizationQuotaRequestToJSON(
  deleteOrganizationQuotaRequest: DeleteOrganizationQuotaRequest,
): string {
  return JSON.stringify(
    DeleteOrganizationQuotaRequest$outboundSchema.parse(
      deleteOrganizationQuotaRequest,
    ),
  );
}
