/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * DeleteOrganizationQuotaResponse confirms deletion. Empty response - success indicated by no error.
 */
export type DeleteOrganizationQuotaResponse = {};

/** @internal */
export const DeleteOrganizationQuotaResponse$inboundSchema: z.ZodMiniType<
  DeleteOrganizationQuotaResponse,
  unknown
> = z.object({});

export function deleteOrganizationQuotaResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteOrganizationQuotaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteOrganizationQuotaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteOrganizationQuotaResponse' from JSON`,
  );
}
