/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * DeleteAPIKeyQuotaResponse confirms deletion. Empty response - success indicated by no error.
 */
export type DeleteAPIKeyQuotaResponse = {};

/** @internal */
export const DeleteAPIKeyQuotaResponse$inboundSchema: z.ZodMiniType<
  DeleteAPIKeyQuotaResponse,
  unknown
> = z.object({});

export function deleteAPIKeyQuotaResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteAPIKeyQuotaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteAPIKeyQuotaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteAPIKeyQuotaResponse' from JSON`,
  );
}
