/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * DocumentPermissionSet contains the permissions the authenticated user has on a document.
 */
export type DocumentPermissionSet = {
  attachPolicy?: boolean | undefined;
  commentPrivate?: boolean | undefined;
  commentPublic?: boolean | undefined;
  copyContent?: boolean | undefined;
  createVersion?: boolean | undefined;
  export?: boolean | undefined;
  grantAccess?: boolean | undefined;
  listVersions?: boolean | undefined;
  manageAccess?: boolean | undefined;
  open?: boolean | undefined;
  screenshot?: boolean | undefined;
  trash?: boolean | undefined;
  view?: boolean | undefined;
  viewAnalytics?: boolean | undefined;
  viewLeads?: boolean | undefined;
  viewTimeline?: boolean | undefined;
};

/** @internal */
export const DocumentPermissionSet$inboundSchema: z.ZodMiniType<
  DocumentPermissionSet,
  unknown
> = z.pipe(
  z.object({
    attach_policy: types.optional(types.boolean()),
    comment_private: types.optional(types.boolean()),
    comment_public: types.optional(types.boolean()),
    copy_content: types.optional(types.boolean()),
    create_version: types.optional(types.boolean()),
    export: types.optional(types.boolean()),
    grant_access: types.optional(types.boolean()),
    list_versions: types.optional(types.boolean()),
    manage_access: types.optional(types.boolean()),
    open: types.optional(types.boolean()),
    screenshot: types.optional(types.boolean()),
    trash: types.optional(types.boolean()),
    view: types.optional(types.boolean()),
    view_analytics: types.optional(types.boolean()),
    view_leads: types.optional(types.boolean()),
    view_timeline: types.optional(types.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "attach_policy": "attachPolicy",
      "comment_private": "commentPrivate",
      "comment_public": "commentPublic",
      "copy_content": "copyContent",
      "create_version": "createVersion",
      "grant_access": "grantAccess",
      "list_versions": "listVersions",
      "manage_access": "manageAccess",
      "view_analytics": "viewAnalytics",
      "view_leads": "viewLeads",
      "view_timeline": "viewTimeline",
    });
  }),
);

export function documentPermissionSetFromJSON(
  jsonString: string,
): SafeParseResult<DocumentPermissionSet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DocumentPermissionSet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentPermissionSet' from JSON`,
  );
}
