/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { AccessLevel, AccessLevel$inboundSchema } from "./accesslevel.js";
import {
  DocumentPermissionSet,
  DocumentPermissionSet$inboundSchema,
} from "./documentpermissionset.js";
import {
  ProcessingStatus,
  ProcessingStatus$inboundSchema,
} from "./processingstatus.js";
import { Subject, Subject$inboundSchema } from "./subject.js";
import { VersionRef, VersionRef$inboundSchema } from "./versionref.js";

/**
 * Document represents a Factify document.
 */
export type Document = {
  accessLevel: AccessLevel;
  /**
   * Timestamp when document was created.
   */
  createdAt: Date;
  /**
   * Subject is a lightweight reference to either a user or a bot.
   *
   * @remarks
   *  Used in embedded fields like created_by.
   *  For full details, call GetUser or GetBot with the subject's id.
   * subject_type_matches_id_prefix // id prefix must match type (user_ for user, bot_ for bot)
   */
  createdBy: Subject;
  /**
   * Reference to the current version, if any.
   */
  currentVersion?: VersionRef | null | undefined;
  /**
   * Optional document description.
   */
  description?: string | null | undefined;
  generalAccess?: AccessLevel | undefined;
  /**
   * Unique ID for the document.
   *
   * @remarks
   *  Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
   */
  id: string;
  /**
   * Whether this document is a demo document created during FTUE onboarding.
   */
  isDemo?: boolean | undefined;
  /**
   * Timestamp when the authenticated user last viewed this document.
   *
   * @remarks
   *  Absent if the user has never viewed it.
   */
  lastViewedAt?: Date | undefined;
  /**
   * Organization that owns this document (via the document creator).
   *
   * @remarks
   *  Empty if the owner's organization could not be resolved.
   */
  ownerOrganizationId?: string | undefined;
  /**
   * DocumentPermissionSet contains the permissions the authenticated user has on a document.
   */
  permissionSet?: DocumentPermissionSet | undefined;
  processingStatus: ProcessingStatus;
  /**
   * Timestamp when this document was last shared to the authenticated user.
   *
   * @remarks
   *  Absent if the document was never shared to them.
   */
  sharedAt?: Date | undefined;
  /**
   * URL of the document thumbnail image.
   */
  thumbnailUrl?: string | undefined;
  /**
   * Document title.
   */
  title: string;
  /**
   * Timestamp when the document was trashed, if applicable.
   *
   * @remarks
   *  Absent if the document is not trashed.
   */
  trashedAt?: Date | undefined;
  /**
   * Timestamp when document was last updated.
   */
  updatedAt?: Date | undefined;
  /**
   * URL for accessing the document on Factify.
   */
  url: string;
};

/** @internal */
export const Document$inboundSchema: z.ZodMiniType<Document, unknown> = z.pipe(
  z.object({
    access_level: AccessLevel$inboundSchema,
    created_at: types.date(),
    created_by: Subject$inboundSchema,
    current_version: z.optional(z.nullable(VersionRef$inboundSchema)),
    description: z.optional(z.nullable(types.string())),
    general_access: types.optional(AccessLevel$inboundSchema),
    id: types.string(),
    is_demo: types.optional(types.boolean()),
    last_viewed_at: types.optional(types.date()),
    owner_organization_id: types.optional(types.string()),
    permission_set: types.optional(DocumentPermissionSet$inboundSchema),
    processing_status: ProcessingStatus$inboundSchema,
    shared_at: types.optional(types.date()),
    thumbnail_url: types.optional(types.string()),
    title: types.string(),
    trashed_at: types.optional(types.date()),
    updated_at: types.optional(types.date()),
    url: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "access_level": "accessLevel",
      "created_at": "createdAt",
      "created_by": "createdBy",
      "current_version": "currentVersion",
      "general_access": "generalAccess",
      "is_demo": "isDemo",
      "last_viewed_at": "lastViewedAt",
      "owner_organization_id": "ownerOrganizationId",
      "permission_set": "permissionSet",
      "processing_status": "processingStatus",
      "shared_at": "sharedAt",
      "thumbnail_url": "thumbnailUrl",
      "trashed_at": "trashedAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function documentFromJSON(
  jsonString: string,
): SafeParseResult<Document, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Document$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Document' from JSON`,
  );
}
