/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const DocumentRole = {
  Viewer: "viewer",
  Commenter: "commenter",
  Collaborator: "collaborator",
  Admin: "admin",
  Owner: "owner",
} as const;
export type DocumentRole = OpenEnum<typeof DocumentRole>;

/** @internal */
export const DocumentRole$inboundSchema: z.ZodMiniType<DocumentRole, unknown> =
  openEnums.inboundSchema(DocumentRole);
/** @internal */
export const DocumentRole$outboundSchema: z.ZodMiniType<string, DocumentRole> =
  openEnums.outboundSchema(DocumentRole);
