/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaDocumentLayout,
  QcrV1alphaDocumentLayout$inboundSchema,
} from "./qcrv1alphadocumentlayout.js";
import {
  QcrV1alphaDocumentRecord,
  QcrV1alphaDocumentRecord$inboundSchema,
} from "./qcrv1alphadocumentrecord.js";

/**
 * DocumentBundle groups a document record with its optional spatial layout.
 */
export type DocumentBundle = {
  /**
   * Top-level layout structure, joined to a DocumentRecord by record_id.
   *
   * @remarks
   *  Used with the Block-based record representation (DocumentRecord.blocks).
   */
  layout?: QcrV1alphaDocumentLayout | undefined;
  /**
   * DocumentRecord is the QCR representation of an ingested document.
   *
   * @remarks
   *  Immutable once extracted. Source-format-agnostic.
   *
   *  Structure is a flat sequence of blocks. Sections provide optional grouping
   *  and can nest, but block-level elements (paragraphs, tables, etc.) are leaves
   *  — they do not contain other blocks. This constrains nesting to only what is
   *  semantically valid and gives every element a natural positional address.
   *
   *  Addressing convention: every element is addressable by its index path through
   *  the typed containment hierarchy. Examples:
   *    blocks[2]                        → third block
   *    blocks[2].section.blocks[0]      → first block inside a section
   *    blocks[4].table.rows[1].cells[0] → second row, first cell of a table
   *    blocks[3].list.items[2]          → third item of a list
   *
   *  These addresses are deterministic for a given record and are used by
   *  DocumentLayout to join layout data to semantic content.
   */
  record?: QcrV1alphaDocumentRecord | undefined;
};

/** @internal */
export const DocumentBundle$inboundSchema: z.ZodMiniType<
  DocumentBundle,
  unknown
> = z.object({
  layout: types.optional(QcrV1alphaDocumentLayout$inboundSchema),
  record: types.optional(QcrV1alphaDocumentRecord$inboundSchema),
});

export function documentBundleFromJSON(
  jsonString: string,
): SafeParseResult<DocumentBundle, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DocumentBundle$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentBundle' from JSON`,
  );
}
