/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Policy, Policy$inboundSchema } from "./policy.js";
import { User, User$inboundSchema } from "./user.js";

/**
 * DocumentPolicy represents a policy attached to a document.
 */
export type DocumentPolicy = {
  /**
   * Timestamp when policy was attached.
   */
  attachedAt: Date;
  /**
   * User represents a user or service account.
   */
  attachedBy: User;
  /**
   * Document ID this policy is attached to.
   *
   * @remarks
   *  Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
   */
  documentId: string;
  /**
   * Policy represents a governance policy.
   */
  policy: Policy;
};

/** @internal */
export const DocumentPolicy$inboundSchema: z.ZodMiniType<
  DocumentPolicy,
  unknown
> = z.pipe(
  z.object({
    attached_at: types.date(),
    attached_by: User$inboundSchema,
    document_id: types.string(),
    policy: Policy$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "attached_at": "attachedAt",
      "attached_by": "attachedBy",
      "document_id": "documentId",
    });
  }),
);

export function documentPolicyFromJSON(
  jsonString: string,
): SafeParseResult<DocumentPolicy, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DocumentPolicy$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentPolicy' from JSON`,
  );
}
