/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A generic empty message that you can re-use to avoid defining duplicated
 *
 * @remarks
 *  empty messages in your APIs. A typical example is to use it as the request
 *  or the response type of an API method. For instance:
 *
 *      service Foo {
 *        rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);
 *      }
 */
export type Empty = {};

/** @internal */
export const Empty$inboundSchema: z.ZodMiniType<Empty, unknown> = z.object({});

export function emptyFromJSON(
  jsonString: string,
): SafeParseResult<Empty, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Empty$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Empty' from JSON`,
  );
}
