/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Machine-readable error reason for programmatic handling
 */
export const Reason = {
  MissingRequiredField: "missing_required_field",
  InvalidFieldValue: "invalid_field_value",
  InvalidEnumValue: "invalid_enum_value",
  InvalidCursor: "invalid_cursor",
  InvalidIdFormat: "invalid_id_format",
  MissingApiKey: "missing_api_key",
  InvalidApiKey: "invalid_api_key",
  ExpiredApiKey: "expired_api_key",
  InvalidToken: "invalid_token",
  ExpiredToken: "expired_token",
  AuthenticationRequired: "authentication_required",
  InsufficientPermissions: "insufficient_permissions",
  ResourceNotFound: "resource_not_found",
  ResourceAlreadyExists: "resource_already_exists",
  RateLimitExceeded: "rate_limit_exceeded",
  QuotaExceeded: "quota_exceeded",
  PreconditionFailed: "precondition_failed",
  FeatureDisabled: "feature_disabled",
  InternalError: "internal_error",
  ServiceUnavailable: "service_unavailable",
  Unimplemented: "unimplemented",
} as const;
/**
 * Machine-readable error reason for programmatic handling
 */
export type Reason = OpenEnum<typeof Reason>;

export type ErrorDetail = {
  /**
   * The parameter that caused the error (only set for validation errors)
   */
  param?: string | undefined;
  /**
   * Machine-readable error reason for programmatic handling
   */
  reason?: Reason | undefined;
  /**
   * Request correlation ID for tracing and log lookup (e.g., "req_01arwx4k8xrgqskvxq69gdn019")
   */
  requestId?: string | undefined;
};

/** @internal */
export const Reason$inboundSchema: z.ZodMiniType<Reason, unknown> = openEnums
  .inboundSchema(Reason);

/** @internal */
export const ErrorDetail$inboundSchema: z.ZodMiniType<ErrorDetail, unknown> = z
  .pipe(
    z.object({
      param: types.optional(types.string()),
      reason: types.optional(Reason$inboundSchema),
      request_id: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "request_id": "requestId",
      });
    }),
  );

export function errorDetailFromJSON(
  jsonString: string,
): SafeParseResult<ErrorDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorDetail' from JSON`,
  );
}
