/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * ExportDocumentResponse contains the download URL.
 */
export type ExportDocumentResponse = {
  /**
   * Timestamp when the download URL expires.
   */
  expiresAt: Date;
  /**
   * HTTP headers to include when fetching the URL.
   */
  headers?: { [k: string]: string } | undefined;
  /**
   * Presigned URL to download the document PDF.
   */
  url: string;
};

/** @internal */
export const ExportDocumentResponse$inboundSchema: z.ZodMiniType<
  ExportDocumentResponse,
  unknown
> = z.pipe(
  z.object({
    expires_at: types.date(),
    headers: types.optional(z.record(z.string(), types.string())),
    url: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "expires_at": "expiresAt",
    });
  }),
);

export function exportDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<ExportDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExportDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExportDocumentResponse' from JSON`,
  );
}
