/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FactifyApiV1betaUserType,
  FactifyApiV1betaUserType$inboundSchema,
} from "./factifyapiv1betausertype.js";

/**
 * User represents a user or service account.
 */
export type FactifyApiV1betaUser = {
  /**
   * Unique ID for the user or service account.
   *
   * @remarks
   *  Pattern: user_[0-9a-hjkmnp-tv-z]{26} for users, svc_[0-9a-hjkmnp-tv-z]{26} for service accounts
   */
  id: string;
  type: FactifyApiV1betaUserType;
  /**
   * Display name of the user or service account.
   */
  name: string;
};

/** @internal */
export const FactifyApiV1betaUser$inboundSchema: z.ZodMiniType<
  FactifyApiV1betaUser,
  unknown
> = z.object({
  id: types.string(),
  type: FactifyApiV1betaUserType$inboundSchema,
  name: types.string(),
});

export function factifyApiV1betaUserFromJSON(
  jsonString: string,
): SafeParseResult<FactifyApiV1betaUser, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FactifyApiV1betaUser$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FactifyApiV1betaUser' from JSON`,
  );
}
