/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FactifyApiV1betaOrganizationInvite,
  FactifyApiV1betaOrganizationInvite$inboundSchema,
} from "./factifyapiv1betaorganizationinvite.js";

/**
 * ResendOrganizationInviteResponse contains the updated invitation.
 */
export type FactifyApiV1betaResendOrganizationInviteResponse = {
  /**
   * OrganizationInvite represents an invitation to join an organization.
   *
   * @remarks
   * accepted_fields_consistency // accepted_at and accepted_by must both be set or both be unset
   */
  invite: FactifyApiV1betaOrganizationInvite;
};

/** @internal */
export const FactifyApiV1betaResendOrganizationInviteResponse$inboundSchema:
  z.ZodMiniType<FactifyApiV1betaResendOrganizationInviteResponse, unknown> = z
    .object({
      invite: FactifyApiV1betaOrganizationInvite$inboundSchema,
    });

export function factifyApiV1betaResendOrganizationInviteResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  FactifyApiV1betaResendOrganizationInviteResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FactifyApiV1betaResendOrganizationInviteResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FactifyApiV1betaResendOrganizationInviteResponse' from JSON`,
  );
}
