/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FactifyApiV1betaDocument,
  FactifyApiV1betaDocument$inboundSchema,
} from "./factifyapiv1betadocument.js";

/**
 * UpdateDocumentResponse contains the updated document.
 */
export type FactifyApiV1betaUpdateDocumentResponse = {
  /**
   * Document represents a Factify document.
   */
  document: FactifyApiV1betaDocument;
};

/** @internal */
export const FactifyApiV1betaUpdateDocumentResponse$inboundSchema:
  z.ZodMiniType<FactifyApiV1betaUpdateDocumentResponse, unknown> = z.object({
    document: FactifyApiV1betaDocument$inboundSchema,
  });

export function factifyApiV1betaUpdateDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<FactifyApiV1betaUpdateDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FactifyApiV1betaUpdateDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FactifyApiV1betaUpdateDocumentResponse' from JSON`,
  );
}
