/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * OrganizationInviteStatus represents the state of an organization invitation.
 */
export const FactifyApiV1betaOrganizationInviteStatus = {
  OrganizationInviteStatusUnspecified: "ORGANIZATION_INVITE_STATUS_UNSPECIFIED",
  OrganizationInviteStatusPending: "ORGANIZATION_INVITE_STATUS_PENDING",
  OrganizationInviteStatusAccepted: "ORGANIZATION_INVITE_STATUS_ACCEPTED",
  OrganizationInviteStatusExpired: "ORGANIZATION_INVITE_STATUS_EXPIRED",
  OrganizationInviteStatusRevoked: "ORGANIZATION_INVITE_STATUS_REVOKED",
} as const;
/**
 * OrganizationInviteStatus represents the state of an organization invitation.
 */
export type FactifyApiV1betaOrganizationInviteStatus = OpenEnum<
  typeof FactifyApiV1betaOrganizationInviteStatus
>;

/** @internal */
export const FactifyApiV1betaOrganizationInviteStatus$inboundSchema:
  z.ZodMiniType<FactifyApiV1betaOrganizationInviteStatus, unknown> = openEnums
    .inboundSchema(FactifyApiV1betaOrganizationInviteStatus);
/** @internal */
export const FactifyApiV1betaOrganizationInviteStatus$outboundSchema:
  z.ZodMiniType<string, FactifyApiV1betaOrganizationInviteStatus> = openEnums
    .outboundSchema(FactifyApiV1betaOrganizationInviteStatus);
