/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FactifyApiV1betaOrganization,
  FactifyApiV1betaOrganization$inboundSchema,
} from "./factifyapiv1betaorganization.js";

/**
 * AcceptOrganizationInviteResponse contains the organization the user joined.
 */
export type FactifyApiV1betaAcceptOrganizationInviteResponse = {
  /**
   * Organization represents a Factify organization.
   */
  organization: FactifyApiV1betaOrganization;
};

/** @internal */
export const FactifyApiV1betaAcceptOrganizationInviteResponse$inboundSchema:
  z.ZodMiniType<FactifyApiV1betaAcceptOrganizationInviteResponse, unknown> = z
    .object({
      organization: FactifyApiV1betaOrganization$inboundSchema,
    });

export function factifyApiV1betaAcceptOrganizationInviteResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  FactifyApiV1betaAcceptOrganizationInviteResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FactifyApiV1betaAcceptOrganizationInviteResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FactifyApiV1betaAcceptOrganizationInviteResponse' from JSON`,
  );
}
