/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FactifyApiV1betaDocument,
  FactifyApiV1betaDocument$inboundSchema,
} from "./factifyapiv1betadocument.js";

/**
 * CreateDocumentResponse contains the newly created document.
 */
export type FactifyApiV1betaCreateDocumentResponse = {
  /**
   * Document represents a Factify document.
   */
  document: FactifyApiV1betaDocument;
};

/** @internal */
export const FactifyApiV1betaCreateDocumentResponse$inboundSchema:
  z.ZodMiniType<FactifyApiV1betaCreateDocumentResponse, unknown> = z.object({
    document: FactifyApiV1betaDocument$inboundSchema,
  });

export function factifyApiV1betaCreateDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<FactifyApiV1betaCreateDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FactifyApiV1betaCreateDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FactifyApiV1betaCreateDocumentResponse' from JSON`,
  );
}
