/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const FactifyApiV1betaUserType = {
  UserAccount: "user_account",
  ServiceAccount: "service_account",
} as const;
export type FactifyApiV1betaUserType = OpenEnum<
  typeof FactifyApiV1betaUserType
>;

/** @internal */
export const FactifyApiV1betaUserType$inboundSchema: z.ZodMiniType<
  FactifyApiV1betaUserType,
  unknown
> = openEnums.inboundSchema(FactifyApiV1betaUserType);
