/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FactifyApiV1betaOrganizationInvite,
  FactifyApiV1betaOrganizationInvite$inboundSchema,
} from "./factifyapiv1betaorganizationinvite.js";

/**
 * RevokeOrganizationInviteResponse contains the revoked invitation.
 */
export type FactifyApiV1betaRevokeOrganizationInviteResponse = {
  /**
   * OrganizationInvite represents an invitation to join an organization.
   *
   * @remarks
   * accepted_fields_consistency // accepted_at and accepted_by must both be set or both be unset
   */
  invite: FactifyApiV1betaOrganizationInvite;
};

/** @internal */
export const FactifyApiV1betaRevokeOrganizationInviteResponse$inboundSchema:
  z.ZodMiniType<FactifyApiV1betaRevokeOrganizationInviteResponse, unknown> = z
    .object({
      invite: FactifyApiV1betaOrganizationInvite$inboundSchema,
    });

export function factifyApiV1betaRevokeOrganizationInviteResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  FactifyApiV1betaRevokeOrganizationInviteResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FactifyApiV1betaRevokeOrganizationInviteResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FactifyApiV1betaRevokeOrganizationInviteResponse' from JSON`,
  );
}
