/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * CreateOrganizationRequest contains the data needed to create a new organization.
 */
export type FactifyApiV1betaCreateOrganizationRequest = {
  /**
   * Human-readable organization name.
   */
  name: string;
  /**
   * Owner user ID. If not provided, the authenticated user becomes the owner.
   *
   * @remarks
   *  Authorization: Specifying a different user requires system maintainer role.
   *  Required when the caller is a service account (service accounts cannot own organizations).
   *  Pattern: user_[0-9a-hjkmnp-tv-z]{26}
   */
  ownerUserId?: string | null | undefined;
};

/** @internal */
export type FactifyApiV1betaCreateOrganizationRequest$Outbound = {
  name: string;
  owner_user_id?: string | null | undefined;
};

/** @internal */
export const FactifyApiV1betaCreateOrganizationRequest$outboundSchema:
  z.ZodMiniType<
    FactifyApiV1betaCreateOrganizationRequest$Outbound,
    FactifyApiV1betaCreateOrganizationRequest
  > = z.pipe(
    z.object({
      name: z.string(),
      ownerUserId: z.optional(z.nullable(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        ownerUserId: "owner_user_id",
      });
    }),
  );

export function factifyApiV1betaCreateOrganizationRequestToJSON(
  factifyApiV1betaCreateOrganizationRequest:
    FactifyApiV1betaCreateOrganizationRequest,
): string {
  return JSON.stringify(
    FactifyApiV1betaCreateOrganizationRequest$outboundSchema.parse(
      factifyApiV1betaCreateOrganizationRequest,
    ),
  );
}
