/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FactifyApiV1betaOrganizationInvite,
  FactifyApiV1betaOrganizationInvite$inboundSchema,
} from "./factifyapiv1betaorganizationinvite.js";
import {
  FactifyApiV1betaPagination,
  FactifyApiV1betaPagination$inboundSchema,
} from "./factifyapiv1betapagination.js";

/**
 * ListOrganizationInvitesResponse contains a page of invitations.
 */
export type FactifyApiV1betaListOrganizationInvitesResponse = {
  /**
   * List of invitations.
   */
  items?: Array<FactifyApiV1betaOrganizationInvite> | undefined;
  /**
   * Pagination contains cursor-based pagination metadata.
   *
   * @remarks
   *  Follows Google AIP-158 for pagination field naming.
   */
  pagination: FactifyApiV1betaPagination;
};

/** @internal */
export const FactifyApiV1betaListOrganizationInvitesResponse$inboundSchema:
  z.ZodMiniType<FactifyApiV1betaListOrganizationInvitesResponse, unknown> = z
    .object({
      items: types.optional(
        z.array(FactifyApiV1betaOrganizationInvite$inboundSchema),
      ),
      pagination: FactifyApiV1betaPagination$inboundSchema,
    });

export function factifyApiV1betaListOrganizationInvitesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  FactifyApiV1betaListOrganizationInvitesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FactifyApiV1betaListOrganizationInvitesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FactifyApiV1betaListOrganizationInvitesResponse' from JSON`,
  );
}
