/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FactifyApiV1betaOrganization,
  FactifyApiV1betaOrganization$inboundSchema,
} from "./factifyapiv1betaorganization.js";

/**
 * GetOrganizationResponse contains the requested organization.
 */
export type FactifyApiV1betaGetOrganizationResponse = {
  /**
   * Organization represents a Factify organization.
   */
  organization: FactifyApiV1betaOrganization;
};

/** @internal */
export const FactifyApiV1betaGetOrganizationResponse$inboundSchema:
  z.ZodMiniType<FactifyApiV1betaGetOrganizationResponse, unknown> = z.object({
    organization: FactifyApiV1betaOrganization$inboundSchema,
  });

export function factifyApiV1betaGetOrganizationResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  FactifyApiV1betaGetOrganizationResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FactifyApiV1betaGetOrganizationResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FactifyApiV1betaGetOrganizationResponse' from JSON`,
  );
}
