/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Pagination contains cursor-based pagination metadata.
 *
 * @remarks
 *  Follows Google AIP-158 for pagination field naming.
 */
export type FactifyApiV1betaPagination = {
  /**
   * Token to retrieve the next page of results.
   *
   * @remarks
   *  Empty if there are no more results in the forward direction.
   */
  nextPageToken?: string | undefined;
  /**
   * Token to retrieve the previous page of results.
   *
   * @remarks
   *  Empty if this is the first page.
   */
  prevPageToken?: string | undefined;
  /**
   * Whether there are more results in the forward direction.
   */
  hasMore?: boolean | undefined;
};

/** @internal */
export const FactifyApiV1betaPagination$inboundSchema: z.ZodMiniType<
  FactifyApiV1betaPagination,
  unknown
> = z.pipe(
  z.object({
    next_page_token: types.optional(types.string()),
    prev_page_token: types.optional(types.string()),
    has_more: types.optional(types.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_page_token": "nextPageToken",
      "prev_page_token": "prevPageToken",
      "has_more": "hasMore",
    });
  }),
);

export function factifyApiV1betaPaginationFromJSON(
  jsonString: string,
): SafeParseResult<FactifyApiV1betaPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FactifyApiV1betaPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FactifyApiV1betaPagination' from JSON`,
  );
}
