/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FactifyApiV1betaDocument,
  FactifyApiV1betaDocument$inboundSchema,
} from "./factifyapiv1betadocument.js";
import {
  FactifyApiV1betaPagination,
  FactifyApiV1betaPagination$inboundSchema,
} from "./factifyapiv1betapagination.js";

/**
 * ListDocumentsResponse contains a page of documents.
 */
export type FactifyApiV1betaListDocumentsResponse = {
  /**
   * List of documents.
   */
  items?: Array<FactifyApiV1betaDocument> | undefined;
  /**
   * Pagination contains cursor-based pagination metadata.
   *
   * @remarks
   *  Follows Google AIP-158 for pagination field naming.
   */
  pagination: FactifyApiV1betaPagination;
};

/** @internal */
export const FactifyApiV1betaListDocumentsResponse$inboundSchema: z.ZodMiniType<
  FactifyApiV1betaListDocumentsResponse,
  unknown
> = z.object({
  items: types.optional(z.array(FactifyApiV1betaDocument$inboundSchema)),
  pagination: FactifyApiV1betaPagination$inboundSchema,
});

export function factifyApiV1betaListDocumentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<FactifyApiV1betaListDocumentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FactifyApiV1betaListDocumentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FactifyApiV1betaListDocumentsResponse' from JSON`,
  );
}
