/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FactifyApiV1betaOrganization,
  FactifyApiV1betaOrganization$inboundSchema,
} from "./factifyapiv1betaorganization.js";
import {
  FactifyApiV1betaPagination,
  FactifyApiV1betaPagination$inboundSchema,
} from "./factifyapiv1betapagination.js";

/**
 * ListOrganizationsResponse contains a page of organizations.
 */
export type FactifyApiV1betaListOrganizationsResponse = {
  /**
   * List of organizations.
   */
  items?: Array<FactifyApiV1betaOrganization> | undefined;
  /**
   * Pagination contains cursor-based pagination metadata.
   *
   * @remarks
   *  Follows Google AIP-158 for pagination field naming.
   */
  pagination: FactifyApiV1betaPagination;
};

/** @internal */
export const FactifyApiV1betaListOrganizationsResponse$inboundSchema:
  z.ZodMiniType<FactifyApiV1betaListOrganizationsResponse, unknown> = z.object({
    items: types.optional(z.array(FactifyApiV1betaOrganization$inboundSchema)),
    pagination: FactifyApiV1betaPagination$inboundSchema,
  });

export function factifyApiV1betaListOrganizationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  FactifyApiV1betaListOrganizationsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FactifyApiV1betaListOrganizationsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FactifyApiV1betaListOrganizationsResponse' from JSON`,
  );
}
