/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { blobLikeSchema } from "../../types/blobs.js";
import {
  FactifyApiV1betaAccessLevel,
  FactifyApiV1betaAccessLevel$outboundSchema,
} from "./factifyapiv1betaaccesslevel.js";

export type FactifyApiV1betaCreateDocumentRequestPayload = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/**
 * CreateDocumentRequest contains the file and metadata for creating a document.
 */
export type FactifyApiV1betaCreateDocumentRequest = {
  /**
   * PDF file to upload
   */
  payload: FactifyApiV1betaCreateDocumentRequestPayload | Blob;
  /**
   * Document title.
   */
  title: string;
  /**
   * Optional document description.
   */
  description?: string | null | undefined;
  accessLevel?: FactifyApiV1betaAccessLevel | undefined;
};

/** @internal */
export type FactifyApiV1betaCreateDocumentRequestPayload$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const FactifyApiV1betaCreateDocumentRequestPayload$outboundSchema:
  z.ZodMiniType<
    FactifyApiV1betaCreateDocumentRequestPayload$Outbound,
    FactifyApiV1betaCreateDocumentRequestPayload
  > = z.object({
    fileName: z.string(),
    content: z.union([
      z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
      z.custom<Blob>(x => x instanceof Blob),
      z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
      z.custom<Uint8Array>(x => x instanceof Uint8Array),
    ]),
  });

export function factifyApiV1betaCreateDocumentRequestPayloadToJSON(
  factifyApiV1betaCreateDocumentRequestPayload:
    FactifyApiV1betaCreateDocumentRequestPayload,
): string {
  return JSON.stringify(
    FactifyApiV1betaCreateDocumentRequestPayload$outboundSchema.parse(
      factifyApiV1betaCreateDocumentRequestPayload,
    ),
  );
}

/** @internal */
export type FactifyApiV1betaCreateDocumentRequest$Outbound = {
  payload: FactifyApiV1betaCreateDocumentRequestPayload$Outbound | Blob;
  title: string;
  description?: string | null | undefined;
  access_level?: string | undefined;
};

/** @internal */
export const FactifyApiV1betaCreateDocumentRequest$outboundSchema:
  z.ZodMiniType<
    FactifyApiV1betaCreateDocumentRequest$Outbound,
    FactifyApiV1betaCreateDocumentRequest
  > = z.pipe(
    z.object({
      payload: z.union([
        z.lazy(() =>
          FactifyApiV1betaCreateDocumentRequestPayload$outboundSchema
        ),
        blobLikeSchema,
      ]),
      title: z.string(),
      description: z.optional(z.nullable(z.string())),
      accessLevel: z.optional(FactifyApiV1betaAccessLevel$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        accessLevel: "access_level",
      });
    }),
  );

export function factifyApiV1betaCreateDocumentRequestToJSON(
  factifyApiV1betaCreateDocumentRequest: FactifyApiV1betaCreateDocumentRequest,
): string {
  return JSON.stringify(
    FactifyApiV1betaCreateDocumentRequest$outboundSchema.parse(
      factifyApiV1betaCreateDocumentRequest,
    ),
  );
}
