/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * GenerateEntryPageResponse contains the download URL for the entry page.
 */
export type GenerateEntryPageResponse = {
  /**
   * Temporary download URL for the entry page PDF.
   */
  downloadUrl: string;
};

/** @internal */
export const GenerateEntryPageResponse$inboundSchema: z.ZodMiniType<
  GenerateEntryPageResponse,
  unknown
> = z.pipe(
  z.object({
    download_url: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "download_url": "downloadUrl",
    });
  }),
);

export function generateEntryPageResponseFromJSON(
  jsonString: string,
): SafeParseResult<GenerateEntryPageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenerateEntryPageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenerateEntryPageResponse' from JSON`,
  );
}
