/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const GeneralAccessLevel = {
  Restricted: "restricted",
  Organization: "organization",
  AnyoneWithLink: "anyone_with_link",
} as const;
export type GeneralAccessLevel = OpenEnum<typeof GeneralAccessLevel>;

/** @internal */
export const GeneralAccessLevel$inboundSchema: z.ZodMiniType<
  GeneralAccessLevel,
  unknown
> = openEnums.inboundSchema(GeneralAccessLevel);
/** @internal */
export const GeneralAccessLevel$outboundSchema: z.ZodMiniType<
  string,
  GeneralAccessLevel
> = openEnums.outboundSchema(GeneralAccessLevel);
