/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Organization, Organization$inboundSchema } from "./organization.js";
import { User, User$inboundSchema } from "./user.js";

/**
 * GetMeResponse contains the authenticated user's profile.
 */
export type GetMeResponse = {
  /**
   * Organizations the user is a member of.
   */
  organizations?: Array<Organization> | undefined;
  /**
   * User represents a human user account.
   *
   * @remarks
   *  Returned by GetUser (endpoint deferred).
   */
  user: User;
};

/** @internal */
export const GetMeResponse$inboundSchema: z.ZodMiniType<
  GetMeResponse,
  unknown
> = z.object({
  organizations: types.optional(z.array(Organization$inboundSchema)),
  user: User$inboundSchema,
});

export function getMeResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetMeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetMeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMeResponse' from JSON`,
  );
}
