/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Organization, Organization$inboundSchema } from "./organization.js";

/**
 * GetOrganizationResponse contains the requested organization.
 */
export type GetOrganizationResponse = {
  /**
   * Organization represents a Factify organization.
   */
  organization: Organization;
};

/** @internal */
export const GetOrganizationResponse$inboundSchema: z.ZodMiniType<
  GetOrganizationResponse,
  unknown
> = z.object({
  organization: Organization$inboundSchema,
});

export function getOrganizationResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationResponse' from JSON`,
  );
}
