/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  OrganizationQuota,
  OrganizationQuota$inboundSchema,
} from "./organizationquota.js";

/**
 * GetOrganizationQuotaResponse returns the quota status.
 */
export type GetOrganizationQuotaResponse = {
  /**
   * OrganizationQuota represents the quota status for an organization.
   */
  quota?: OrganizationQuota | undefined;
};

/** @internal */
export const GetOrganizationQuotaResponse$inboundSchema: z.ZodMiniType<
  GetOrganizationQuotaResponse,
  unknown
> = z.object({
  quota: types.optional(OrganizationQuota$inboundSchema),
});

export function getOrganizationQuotaResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationQuotaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationQuotaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationQuotaResponse' from JSON`,
  );
}
