/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DocumentBundle,
  DocumentBundle$inboundSchema,
} from "./documentbundle.js";
import {
  SpreadsheetBundle,
  SpreadsheetBundle$inboundSchema,
} from "./spreadsheetbundle.js";

export type Spreadsheet = {
  /**
   * SpreadsheetBundle groups a spreadsheet record with its optional grid layout.
   */
  spreadsheet: SpreadsheetBundle;
  /**
   * Unique record ID (UUID format).
   */
  id?: string | undefined;
  /**
   * Source format of the original upload (e.g., pdf, docx, xlsx, csv).
   */
  sourceFormat?: string | undefined;
};

export type GetRecordResponseDocument = {
  /**
   * DocumentBundle groups a document record with its optional spatial layout.
   */
  document: DocumentBundle;
  /**
   * Unique record ID (UUID format).
   */
  id?: string | undefined;
  /**
   * Source format of the original upload (e.g., pdf, docx, xlsx, csv).
   */
  sourceFormat?: string | undefined;
};

/**
 * GetRecordResponse contains the processed content and layout for a version.
 *
 * @remarks
 *  The content oneof is populated based on source_format:
 *    - document formats (pdf, docx, markdown): document field
 *    - spreadsheet formats (xlsx, csv):        spreadsheet field
 */
export type GetRecordResponse = GetRecordResponseDocument | Spreadsheet;

/** @internal */
export const Spreadsheet$inboundSchema: z.ZodMiniType<Spreadsheet, unknown> = z
  .pipe(
    z.object({
      spreadsheet: SpreadsheetBundle$inboundSchema,
      id: types.optional(types.string()),
      source_format: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "source_format": "sourceFormat",
      });
    }),
  );

export function spreadsheetFromJSON(
  jsonString: string,
): SafeParseResult<Spreadsheet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Spreadsheet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Spreadsheet' from JSON`,
  );
}

/** @internal */
export const GetRecordResponseDocument$inboundSchema: z.ZodMiniType<
  GetRecordResponseDocument,
  unknown
> = z.pipe(
  z.object({
    document: DocumentBundle$inboundSchema,
    id: types.optional(types.string()),
    source_format: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "source_format": "sourceFormat",
    });
  }),
);

export function getRecordResponseDocumentFromJSON(
  jsonString: string,
): SafeParseResult<GetRecordResponseDocument, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRecordResponseDocument$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRecordResponseDocument' from JSON`,
  );
}

/** @internal */
export const GetRecordResponse$inboundSchema: z.ZodMiniType<
  GetRecordResponse,
  unknown
> = smartUnion([
  z.lazy(() => GetRecordResponseDocument$inboundSchema),
  z.lazy(() => Spreadsheet$inboundSchema),
]);

export function getRecordResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetRecordResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRecordResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRecordResponse' from JSON`,
  );
}
