/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaDocumentLayout,
  QcrV1alphaDocumentLayout$inboundSchema,
} from "./qcrv1alphadocumentlayout.js";
import {
  QcrV1alphaDocumentRecord,
  QcrV1alphaDocumentRecord$inboundSchema,
} from "./qcrv1alphadocumentrecord.js";

/**
 * GetRecordResponse contains the processed document content and layout.
 */
export type GetRecordResponse = {
  /**
   * DocumentRecord is the QCR representation of an ingested document.
   *
   * @remarks
   *  Immutable once extracted. Source-format-agnostic.
   *
   *  Structure is a flat sequence of blocks. Sections provide optional grouping
   *  and can nest, but block-level elements (paragraphs, tables, etc.) are leaves
   *  — they do not contain other blocks. This constrains nesting to only what is
   *  semantically valid and gives every element a natural positional address.
   *
   *  Addressing convention: every element is addressable by its index path through
   *  the typed containment hierarchy. Examples:
   *    blocks[2]                        → third block
   *    blocks[2].section.blocks[0]      → first block inside a section
   *    blocks[4].table.rows[1].cells[0] → second row, first cell of a table
   *    blocks[3].list.items[2]          → third item of a list
   *
   *  These addresses are deterministic for a given record and are used by
   *  DocumentLayout to join layout data to semantic content.
   */
  document?: QcrV1alphaDocumentRecord | undefined;
  /**
   * Unique record ID (UUID format).
   */
  id?: string | undefined;
  /**
   * Top-level layout structure, joined to a DocumentRecord by record_id.
   *
   * @remarks
   *  Used with the Block-based record representation (DocumentRecord.blocks).
   */
  layout?: QcrV1alphaDocumentLayout | undefined;
  /**
   * Source format of the original upload (e.g., pdf, docx, xlsx).
   */
  sourceFormat?: string | undefined;
};

/** @internal */
export const GetRecordResponse$inboundSchema: z.ZodMiniType<
  GetRecordResponse,
  unknown
> = z.pipe(
  z.object({
    document: types.optional(QcrV1alphaDocumentRecord$inboundSchema),
    id: types.optional(types.string()),
    layout: types.optional(QcrV1alphaDocumentLayout$inboundSchema),
    source_format: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "source_format": "sourceFormat",
    });
  }),
);

export function getRecordResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetRecordResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRecordResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRecordResponse' from JSON`,
  );
}
