/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { DailyUsage, DailyUsage$inboundSchema } from "./dailyusage.js";

/**
 * GetUsageHistoryResponse returns usage history.
 */
export type GetUsageHistoryResponse = {
  /**
   * Daily usage records.
   */
  dailyUsage?: Array<DailyUsage> | undefined;
  /**
   * The organization ID.
   */
  organizationId?: string | undefined;
  /**
   * Total requests in the period.
   */
  totalRequests?: number | undefined;
};

/** @internal */
export const GetUsageHistoryResponse$inboundSchema: z.ZodMiniType<
  GetUsageHistoryResponse,
  unknown
> = z.pipe(
  z.object({
    daily_usage: types.optional(z.array(DailyUsage$inboundSchema)),
    organization_id: types.optional(types.string()),
    total_requests: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "daily_usage": "dailyUsage",
      "organization_id": "organizationId",
      "total_requests": "totalRequests",
    });
  }),
);

export function getUsageHistoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetUsageHistoryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUsageHistoryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUsageHistoryResponse' from JSON`,
  );
}
