/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AccessGrantResult,
  AccessGrantResult$inboundSchema,
} from "./accessgrantresult.js";

/**
 * GrantDocumentAccessResponse contains the results of granting access.
 */
export type GrantDocumentAccessResponse = {
  /**
   * Document ID.
   */
  documentId?: string | undefined;
  /**
   * Number of failed grants.
   */
  failed?: number | undefined;
  /**
   * Results for each recipient.
   */
  results?: Array<AccessGrantResult> | undefined;
  /**
   * Number of successful grants.
   */
  successful?: number | undefined;
  /**
   * Total number of recipients processed.
   */
  total?: number | undefined;
};

/** @internal */
export const GrantDocumentAccessResponse$inboundSchema: z.ZodMiniType<
  GrantDocumentAccessResponse,
  unknown
> = z.pipe(
  z.object({
    document_id: types.optional(types.string()),
    failed: types.optional(types.number()),
    results: types.optional(z.array(AccessGrantResult$inboundSchema)),
    successful: types.optional(types.number()),
    total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "document_id": "documentId",
    });
  }),
);

export function grantDocumentAccessResponseFromJSON(
  jsonString: string,
): SafeParseResult<GrantDocumentAccessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GrantDocumentAccessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GrantDocumentAccessResponse' from JSON`,
  );
}
