/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Organization, Organization$inboundSchema } from "./organization.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";

/**
 * ListOrganizationsResponse contains a page of organizations.
 */
export type ListOrganizationsResponse = {
  /**
   * List of organizations.
   */
  items?: Array<Organization> | undefined;
  /**
   * Pagination contains cursor-based pagination metadata.
   *
   * @remarks
   *  Follows Google AIP-158 for pagination field naming.
   */
  pagination: Pagination;
};

/** @internal */
export const ListOrganizationsResponse$inboundSchema: z.ZodMiniType<
  ListOrganizationsResponse,
  unknown
> = z.object({
  items: types.optional(z.array(Organization$inboundSchema)),
  pagination: Pagination$inboundSchema,
});

export function listOrganizationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListOrganizationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListOrganizationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListOrganizationsResponse' from JSON`,
  );
}
