/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Document, Document$inboundSchema } from "./document.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";

/**
 * ListDocumentsResponse contains a page of documents.
 */
export type ListDocumentsResponse = {
  /**
   * List of documents.
   */
  items?: Array<Document> | undefined;
  /**
   * Pagination contains cursor-based pagination metadata.
   *
   * @remarks
   *  Follows Google AIP-158 for pagination field naming.
   */
  pagination?: Pagination | undefined;
};

/** @internal */
export const ListDocumentsResponse$inboundSchema: z.ZodMiniType<
  ListDocumentsResponse,
  unknown
> = z.object({
  items: types.optional(z.array(Document$inboundSchema)),
  pagination: types.optional(Pagination$inboundSchema),
});

export function listDocumentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDocumentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDocumentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDocumentsResponse' from JSON`,
  );
}
