/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { ApiKey, ApiKey$inboundSchema } from "./apikey.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";

/**
 * ListApiKeysResponse contains a page of API keys.
 */
export type ListApiKeysResponse = {
  /**
   * List of API keys (secrets are never included).
   */
  items?: Array<ApiKey> | undefined;
  /**
   * Pagination contains cursor-based pagination metadata.
   *
   * @remarks
   *  Follows Google AIP-158 for pagination field naming.
   */
  pagination: Pagination;
};

/** @internal */
export const ListApiKeysResponse$inboundSchema: z.ZodMiniType<
  ListApiKeysResponse,
  unknown
> = z.object({
  items: types.optional(z.array(ApiKey$inboundSchema)),
  pagination: Pagination$inboundSchema,
});

export function listApiKeysResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListApiKeysResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListApiKeysResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListApiKeysResponse' from JSON`,
  );
}
