/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DuplicateDocument,
  DuplicateDocument$inboundSchema,
} from "./duplicatedocument.js";

/**
 * ListDocumentDuplicatesResponse contains the duplicate documents.
 */
export type ListDocumentDuplicatesResponse = {
  /**
   * Duplicate documents found. Empty if none found or accessible.
   */
  items?: Array<DuplicateDocument> | undefined;
};

/** @internal */
export const ListDocumentDuplicatesResponse$inboundSchema: z.ZodMiniType<
  ListDocumentDuplicatesResponse,
  unknown
> = z.object({
  items: types.optional(z.array(DuplicateDocument$inboundSchema)),
});

export function listDocumentDuplicatesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDocumentDuplicatesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDocumentDuplicatesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDocumentDuplicatesResponse' from JSON`,
  );
}
