/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  GeneralAccessLevel,
  GeneralAccessLevel$inboundSchema,
} from "./generalaccesslevel.js";
import { Recipient, Recipient$inboundSchema } from "./recipient.js";

/**
 * ListDocumentAccessResponse contains the access list and general access level.
 */
export type ListDocumentAccessResponse = {
  /**
   * Document ID.
   */
  documentId?: string | undefined;
  generalAccessLevel?: GeneralAccessLevel | undefined;
  /**
   * Recipients with access.
   */
  recipients?: Array<Recipient> | undefined;
};

/** @internal */
export const ListDocumentAccessResponse$inboundSchema: z.ZodMiniType<
  ListDocumentAccessResponse,
  unknown
> = z.pipe(
  z.object({
    document_id: types.optional(types.string()),
    general_access_level: types.optional(GeneralAccessLevel$inboundSchema),
    recipients: types.optional(z.array(Recipient$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "document_id": "documentId",
      "general_access_level": "generalAccessLevel",
    });
  }),
);

export function listDocumentAccessResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDocumentAccessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDocumentAccessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDocumentAccessResponse' from JSON`,
  );
}
