/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DocumentPolicy,
  DocumentPolicy$inboundSchema,
} from "./documentpolicy.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";

/**
 * ListDocumentPoliciesResponse contains a page of policy attachments.
 */
export type ListDocumentPoliciesResponse = {
  /**
   * List of policy attachments.
   */
  items?: Array<DocumentPolicy> | undefined;
  /**
   * Pagination contains cursor-based pagination metadata.
   *
   * @remarks
   *  Follows Google AIP-158 for pagination field naming.
   */
  pagination: Pagination;
};

/** @internal */
export const ListDocumentPoliciesResponse$inboundSchema: z.ZodMiniType<
  ListDocumentPoliciesResponse,
  unknown
> = z.object({
  items: types.optional(z.array(DocumentPolicy$inboundSchema)),
  pagination: Pagination$inboundSchema,
});

export function listDocumentPoliciesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDocumentPoliciesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDocumentPoliciesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDocumentPoliciesResponse' from JSON`,
  );
}
