/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { AccessRequest, AccessRequest$inboundSchema } from "./accessrequest.js";

/**
 * ListAccessRequestsResponse contains the list of access requests.
 */
export type ListAccessRequestsResponse = {
  hasMore?: boolean | undefined;
  items?: Array<AccessRequest> | undefined;
};

/** @internal */
export const ListAccessRequestsResponse$inboundSchema: z.ZodMiniType<
  ListAccessRequestsResponse,
  unknown
> = z.pipe(
  z.object({
    has_more: types.optional(types.boolean()),
    items: types.optional(z.array(AccessRequest$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
    });
  }),
);

export function listAccessRequestsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAccessRequestsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAccessRequestsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAccessRequestsResponse' from JSON`,
  );
}
