/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { APIKeyQuota, APIKeyQuota$inboundSchema } from "./apikeyquota.js";

/**
 * ListAPIKeyQuotasResponse returns all key-level quotas.
 */
export type ListAPIKeyQuotasResponse = {
  /**
   * Per-key quota configurations and usage.
   */
  quotas?: Array<APIKeyQuota> | undefined;
};

/** @internal */
export const ListAPIKeyQuotasResponse$inboundSchema: z.ZodMiniType<
  ListAPIKeyQuotasResponse,
  unknown
> = z.object({
  quotas: types.optional(z.array(APIKeyQuota$inboundSchema)),
});

export function listAPIKeyQuotasResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAPIKeyQuotasResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAPIKeyQuotasResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAPIKeyQuotasResponse' from JSON`,
  );
}
