/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  OrganizationRole,
  OrganizationRole$inboundSchema,
} from "./organizationrole.js";
import { User, User$inboundSchema } from "./user.js";

/**
 * OrganizationMember represents a member of an organization.
 */
export type OrganizationMember = {
  /**
   * When the member joined the organization.
   */
  joinedAt: Date;
  role: OrganizationRole;
  /**
   * User represents a human user account.
   *
   * @remarks
   *  Returned by GetUser (endpoint deferred).
   */
  user: User;
};

/** @internal */
export const OrganizationMember$inboundSchema: z.ZodMiniType<
  OrganizationMember,
  unknown
> = z.pipe(
  z.object({
    joined_at: types.date(),
    role: OrganizationRole$inboundSchema,
    user: User$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "joined_at": "joinedAt",
    });
  }),
);

export function organizationMemberFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationMember, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationMember$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationMember' from JSON`,
  );
}
