/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { QuotaTier, QuotaTier$inboundSchema } from "./quotatier.js";

/**
 * OrganizationQuota represents the quota status for an organization.
 */
export type OrganizationQuota = {
  /**
   * Current usage in the billing period.
   */
  currentUsage?: number | undefined;
  /**
   * The effective monthly limit (considers custom_limit if set).
   */
  effectiveLimit?: number | undefined;
  /**
   * Whether quota is exceeded.
   */
  isExceeded?: boolean | undefined;
  /**
   * The organization ID.
   *
   * @remarks
   *  Pattern: org_[0-9a-hjkmnp-tv-z]{26}
   */
  organizationId?: string | undefined;
  /**
   * Start of current billing period.
   */
  periodStart?: Date | undefined;
  /**
   * Remaining requests in the billing period.
   */
  remaining?: number | undefined;
  /**
   * When the quota resets (start of next billing period).
   */
  resetAt?: Date | undefined;
  /**
   * QuotaTier represents the organization's quota tier.
   */
  tier?: QuotaTier | undefined;
  /**
   * Usage as a percentage (0-100+).
   */
  usagePercent?: number | undefined;
};

/** @internal */
export const OrganizationQuota$inboundSchema: z.ZodMiniType<
  OrganizationQuota,
  unknown
> = z.pipe(
  z.object({
    current_usage: types.optional(types.number()),
    effective_limit: types.optional(types.number()),
    is_exceeded: types.optional(types.boolean()),
    organization_id: types.optional(types.string()),
    period_start: types.optional(types.date()),
    remaining: types.optional(types.number()),
    reset_at: types.optional(types.date()),
    tier: types.optional(QuotaTier$inboundSchema),
    usage_percent: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "current_usage": "currentUsage",
      "effective_limit": "effectiveLimit",
      "is_exceeded": "isExceeded",
      "organization_id": "organizationId",
      "period_start": "periodStart",
      "reset_at": "resetAt",
      "usage_percent": "usagePercent",
    });
  }),
);

export function organizationQuotaFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationQuota, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationQuota$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationQuota' from JSON`,
  );
}
