/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const OrganizationRole = {
  Owner: "owner",
  Admin: "admin",
  Member: "member",
} as const;
export type OrganizationRole = ClosedEnum<typeof OrganizationRole>;

/** @internal */
export const OrganizationRole$outboundSchema: z.ZodMiniEnum<
  typeof OrganizationRole
> = z.enum(OrganizationRole);
