/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Organization represents a Factify organization.
 */
export type Organization = {
  /**
   * Timestamp when the organization was created.
   */
  createdAt: Date;
  /**
   * Unique ID for the organization.
   *
   * @remarks
   *  Pattern: org_[0-9a-hjkmnp-tv-z]{26}
   */
  id: string;
  /**
   * Human-readable organization name.
   */
  name: string;
};

/** @internal */
export const Organization$inboundSchema: z.ZodMiniType<Organization, unknown> =
  z.pipe(
    z.object({
      created_at: types.date(),
      id: types.string(),
      name: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "created_at": "createdAt",
      });
    }),
  );

export function organizationFromJSON(
  jsonString: string,
): SafeParseResult<Organization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Organization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Organization' from JSON`,
  );
}
