/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  OrganizationInviteStatus,
  OrganizationInviteStatus$inboundSchema,
} from "./organizationinvitestatus.js";
import { User, User$inboundSchema } from "./user.js";

/**
 * OrganizationInvite represents an invitation to join an organization.
 *
 * @remarks
 * accepted_fields_consistency // accepted_at and accepted_by must both be set or both be unset
 */
export type OrganizationInvite = {
  /**
   * When the invitation was accepted (if accepted).
   */
  acceptedAt?: Date | undefined;
  /**
   * User represents a user or service account.
   */
  acceptedBy?: User | undefined;
  /**
   * When the invitation was created.
   */
  createdAt: Date;
  /**
   * Email address of the recipient.
   */
  email: string;
  /**
   * When the invitation expires.
   */
  expiresAt: Date;
  /**
   * Unique identifier for the invitation.
   */
  id: string;
  /**
   * Custom message from sender to recipient (if provided).
   *
   * @remarks
   *  Max 2000 bytes to support ~500 multibyte characters.
   */
  message?: string | null | undefined;
  /**
   * Organization the invitation is for.
   */
  organizationId: string;
  /**
   * User represents a user or service account.
   */
  sender: User;
  /**
   * OrganizationInviteStatus represents the state of an organization invitation.
   */
  status: OrganizationInviteStatus;
};

/** @internal */
export const OrganizationInvite$inboundSchema: z.ZodMiniType<
  OrganizationInvite,
  unknown
> = z.pipe(
  z.object({
    accepted_at: types.optional(types.date()),
    accepted_by: types.optional(User$inboundSchema),
    created_at: types.date(),
    email: types.string(),
    expires_at: types.date(),
    id: types.string(),
    message: z.optional(z.nullable(types.string())),
    organization_id: types.string(),
    sender: User$inboundSchema,
    status: OrganizationInviteStatus$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "accepted_at": "acceptedAt",
      "accepted_by": "acceptedBy",
      "created_at": "createdAt",
      "expires_at": "expiresAt",
      "organization_id": "organizationId",
    });
  }),
);

export function organizationInviteFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationInvite, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationInvite$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationInvite' from JSON`,
  );
}
