/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Policy represents a governance policy.
 */
export type Policy = {
  /**
   * Timestamp when policy was created.
   */
  createdAt: Date;
  /**
   * Unique ID for the policy.
   *
   * @remarks
   *  Pattern: pol_[0-9a-hjkmnp-tv-z]{26}
   */
  id: string;
  /**
   * Policy name.
   */
  name: string;
};

/** @internal */
export const Policy$inboundSchema: z.ZodMiniType<Policy, unknown> = z.pipe(
  z.object({
    created_at: types.date(),
    id: types.string(),
    name: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
    });
  }),
);

export function policyFromJSON(
  jsonString: string,
): SafeParseResult<Policy, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Policy$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Policy' from JSON`,
  );
}
