/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const ProcessingStatus = {
  Processing: "processing",
  Ready: "ready",
  Failed: "failed",
} as const;
export type ProcessingStatus = OpenEnum<typeof ProcessingStatus>;

/** @internal */
export const ProcessingStatus$inboundSchema: z.ZodMiniType<
  ProcessingStatus,
  unknown
> = openEnums.inboundSchema(ProcessingStatus);
