/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * ProcessingOutcome describes the result of a processing trigger request.
 */
export const ProcessingOutcome = {
  ProcessingOutcomeUnspecified: "PROCESSING_OUTCOME_UNSPECIFIED",
  ProcessingOutcomeStarted: "PROCESSING_OUTCOME_STARTED",
  ProcessingOutcomeAlreadyProcessing: "PROCESSING_OUTCOME_ALREADY_PROCESSING",
  ProcessingOutcomeAlreadyCompleted: "PROCESSING_OUTCOME_ALREADY_COMPLETED",
  ProcessingOutcomeFailed: "PROCESSING_OUTCOME_FAILED",
} as const;
/**
 * ProcessingOutcome describes the result of a processing trigger request.
 */
export type ProcessingOutcome = OpenEnum<typeof ProcessingOutcome>;

/** @internal */
export const ProcessingOutcome$inboundSchema: z.ZodMiniType<
  ProcessingOutcome,
  unknown
> = openEnums.inboundSchema(ProcessingOutcome);
