/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const QcrV1alphaCellErrorType = {
  CellErrorTypeUnspecified: "CELL_ERROR_TYPE_UNSPECIFIED",
  CellErrorTypeNull: "CELL_ERROR_TYPE_NULL",
  CellErrorTypeDivZero: "CELL_ERROR_TYPE_DIV_ZERO",
  CellErrorTypeValue: "CELL_ERROR_TYPE_VALUE",
  CellErrorTypeRef: "CELL_ERROR_TYPE_REF",
  CellErrorTypeName: "CELL_ERROR_TYPE_NAME",
  CellErrorTypeNum: "CELL_ERROR_TYPE_NUM",
  CellErrorTypeNa: "CELL_ERROR_TYPE_NA",
  CellErrorTypeGettingData: "CELL_ERROR_TYPE_GETTING_DATA",
  CellErrorTypeSpill: "CELL_ERROR_TYPE_SPILL",
  CellErrorTypeCalc: "CELL_ERROR_TYPE_CALC",
} as const;
export type QcrV1alphaCellErrorType = OpenEnum<typeof QcrV1alphaCellErrorType>;

/** @internal */
export const QcrV1alphaCellErrorType$inboundSchema: z.ZodMiniType<
  QcrV1alphaCellErrorType,
  unknown
> = openEnums.inboundSchema(QcrV1alphaCellErrorType);
