/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaTableDataRow,
  QcrV1alphaTableDataRow$inboundSchema,
} from "./qcrv1alphatabledatarow.js";

export type QcrV1alphaTableData = {
  rows?: Array<QcrV1alphaTableDataRow> | undefined;
};

/** @internal */
export const QcrV1alphaTableData$inboundSchema: z.ZodMiniType<
  QcrV1alphaTableData,
  unknown
> = z.object({
  rows: types.optional(z.array(QcrV1alphaTableDataRow$inboundSchema)),
});

export function qcrV1alphaTableDataFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaTableData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaTableData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaTableData' from JSON`,
  );
}
