/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaHorizontalAlignment,
  QcrV1alphaHorizontalAlignment$inboundSchema,
} from "./qcrv1alphahorizontalalignment.js";
import {
  QcrV1alphaVerticalAlignment,
  QcrV1alphaVerticalAlignment$inboundSchema,
} from "./qcrv1alphaverticalalignment.js";

export type VerticalText = {
  /**
   * stacked vertical text
   */
  verticalText: boolean;
  horizontal?: QcrV1alphaHorizontalAlignment | undefined;
  vertical?: QcrV1alphaVerticalAlignment | undefined;
};

export type RotationDegrees = {
  /**
   * -90 to 90; positive = counter-clockwise
   */
  rotationDegrees: number;
  horizontal?: QcrV1alphaHorizontalAlignment | undefined;
  vertical?: QcrV1alphaVerticalAlignment | undefined;
};

export type QcrV1alphaCellAlignment = RotationDegrees | VerticalText;

/** @internal */
export const VerticalText$inboundSchema: z.ZodMiniType<VerticalText, unknown> =
  z.pipe(
    z.object({
      vertical_text: types.boolean(),
      horizontal: types.optional(QcrV1alphaHorizontalAlignment$inboundSchema),
      vertical: types.optional(QcrV1alphaVerticalAlignment$inboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        "vertical_text": "verticalText",
      });
    }),
  );

export function verticalTextFromJSON(
  jsonString: string,
): SafeParseResult<VerticalText, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VerticalText$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerticalText' from JSON`,
  );
}

/** @internal */
export const RotationDegrees$inboundSchema: z.ZodMiniType<
  RotationDegrees,
  unknown
> = z.pipe(
  z.object({
    rotation_degrees: types.number(),
    horizontal: types.optional(QcrV1alphaHorizontalAlignment$inboundSchema),
    vertical: types.optional(QcrV1alphaVerticalAlignment$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "rotation_degrees": "rotationDegrees",
    });
  }),
);

export function rotationDegreesFromJSON(
  jsonString: string,
): SafeParseResult<RotationDegrees, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RotationDegrees$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RotationDegrees' from JSON`,
  );
}

/** @internal */
export const QcrV1alphaCellAlignment$inboundSchema: z.ZodMiniType<
  QcrV1alphaCellAlignment,
  unknown
> = smartUnion([
  z.lazy(() => RotationDegrees$inboundSchema),
  z.lazy(() => VerticalText$inboundSchema),
]);

export function qcrV1alphaCellAlignmentFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaCellAlignment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaCellAlignment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaCellAlignment' from JSON`,
  );
}
