/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const QcrV1alphaMimeType = {
  MimeTypeUnspecified: "MIME_TYPE_UNSPECIFIED",
  MimeTypeImagePng: "MIME_TYPE_IMAGE_PNG",
  MimeTypeImageJpeg: "MIME_TYPE_IMAGE_JPEG",
  MimeTypeImageGif: "MIME_TYPE_IMAGE_GIF",
  MimeTypeImageWebp: "MIME_TYPE_IMAGE_WEBP",
  MimeTypeImageBmp: "MIME_TYPE_IMAGE_BMP",
  MimeTypeImageTiff: "MIME_TYPE_IMAGE_TIFF",
  MimeTypeImageSvg: "MIME_TYPE_IMAGE_SVG",
  MimeTypeImageEps: "MIME_TYPE_IMAGE_EPS",
  MimeTypeApplicationPdf: "MIME_TYPE_APPLICATION_PDF",
} as const;
export type QcrV1alphaMimeType = OpenEnum<typeof QcrV1alphaMimeType>;

/** @internal */
export const QcrV1alphaMimeType$inboundSchema: z.ZodMiniType<
  QcrV1alphaMimeType,
  unknown
> = openEnums.inboundSchema(QcrV1alphaMimeType);
