/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaPathSegment,
  QcrV1alphaPathSegment$inboundSchema,
} from "./qcrv1alphapathsegment.js";

/**
 * BlockPath addresses an element within the record's typed containment
 *
 * @remarks
 *  hierarchy. Each segment steps into a specific typed child collection.
 *
 *  Examples:
 *    [block(2)]                                → blocks[2]
 *    [block(2), block(0)]                      → blocks[2].section.blocks[0]
 *    [block(4), row(1), cell(0)]               → blocks[4].table.rows[1].cells[0]
 *    [block(3), item(2)]                       → blocks[3].list.items[2]
 *    [block(3), item(2), item(0)]              → nested sub-list item
 *
 *  The path is unambiguous because each segment type implies which child
 *  collection to descend into (blocks for sections, rows for tables, etc.).
 */
export type QcrV1alphaBlockPath = {
  segments?: Array<QcrV1alphaPathSegment> | undefined;
};

/** @internal */
export const QcrV1alphaBlockPath$inboundSchema: z.ZodMiniType<
  QcrV1alphaBlockPath,
  unknown
> = z.object({
  segments: types.optional(z.array(QcrV1alphaPathSegment$inboundSchema)),
});

export function qcrV1alphaBlockPathFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaBlockPath, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaBlockPath$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaBlockPath' from JSON`,
  );
}
