/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type QcrV1alphaTableDataRowCell = {
  colSpan?: number | undefined;
  isHeader?: boolean | undefined;
  rowSpan?: number | undefined;
  text?: string | undefined;
};

/** @internal */
export const QcrV1alphaTableDataRowCell$inboundSchema: z.ZodMiniType<
  QcrV1alphaTableDataRowCell,
  unknown
> = z.pipe(
  z.object({
    col_span: types.optional(types.number()),
    is_header: types.optional(types.boolean()),
    row_span: types.optional(types.number()),
    text: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "col_span": "colSpan",
      "is_header": "isHeader",
      "row_span": "rowSpan",
    });
  }),
);

export function qcrV1alphaTableDataRowCellFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaTableDataRowCell, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaTableDataRowCell$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaTableDataRowCell' from JSON`,
  );
}
