/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaCellAlignment,
  QcrV1alphaCellAlignment$inboundSchema,
} from "./qcrv1alphacellalignment.js";

export type QcrV1alphaCellLayoutBinding = {
  alignment?: QcrV1alphaCellAlignment | undefined;
  col?: number | undefined;
  row?: number | undefined;
  textWrap?: boolean | undefined;
};

/** @internal */
export const QcrV1alphaCellLayoutBinding$inboundSchema: z.ZodMiniType<
  QcrV1alphaCellLayoutBinding,
  unknown
> = z.pipe(
  z.object({
    alignment: types.optional(QcrV1alphaCellAlignment$inboundSchema),
    col: types.optional(types.number()),
    row: types.optional(types.number()),
    text_wrap: types.optional(types.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "text_wrap": "textWrap",
    });
  }),
);

export function qcrV1alphaCellLayoutBindingFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaCellLayoutBinding, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaCellLayoutBinding$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaCellLayoutBinding' from JSON`,
  );
}
