/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaCellErrorType,
  QcrV1alphaCellErrorType$inboundSchema,
} from "./qcrv1alphacellerrortype.js";

export type StringValue = {
  stringValue: string;
  hyperlink?: string | undefined;
  note?: string | undefined;
};

export type NumberValue = {
  numberValue: number;
  hyperlink?: string | undefined;
  note?: string | undefined;
};

export type ErrorValue = {
  errorValue: QcrV1alphaCellErrorType;
  hyperlink?: string | undefined;
  note?: string | undefined;
};

export type BoolValue = {
  boolValue: boolean;
  hyperlink?: string | undefined;
  note?: string | undefined;
};

/**
 * DataCell holds a single semantic value. Source-format concerns (formulas,
 *
 * @remarks
 *  formatting) are not modeled — the record captures what the data means.
 */
export type QcrV1alphaDataCell =
  | BoolValue
  | ErrorValue
  | NumberValue
  | StringValue;

/** @internal */
export const StringValue$inboundSchema: z.ZodMiniType<StringValue, unknown> = z
  .pipe(
    z.object({
      string_value: types.string(),
      hyperlink: types.optional(types.string()),
      note: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "string_value": "stringValue",
      });
    }),
  );

export function stringValueFromJSON(
  jsonString: string,
): SafeParseResult<StringValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StringValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StringValue' from JSON`,
  );
}

/** @internal */
export const NumberValue$inboundSchema: z.ZodMiniType<NumberValue, unknown> = z
  .pipe(
    z.object({
      number_value: types.number(),
      hyperlink: types.optional(types.string()),
      note: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "number_value": "numberValue",
      });
    }),
  );

export function numberValueFromJSON(
  jsonString: string,
): SafeParseResult<NumberValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NumberValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NumberValue' from JSON`,
  );
}

/** @internal */
export const ErrorValue$inboundSchema: z.ZodMiniType<ErrorValue, unknown> = z
  .pipe(
    z.object({
      error_value: QcrV1alphaCellErrorType$inboundSchema,
      hyperlink: types.optional(types.string()),
      note: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "error_value": "errorValue",
      });
    }),
  );

export function errorValueFromJSON(
  jsonString: string,
): SafeParseResult<ErrorValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorValue' from JSON`,
  );
}

/** @internal */
export const BoolValue$inboundSchema: z.ZodMiniType<BoolValue, unknown> = z
  .pipe(
    z.object({
      bool_value: types.boolean(),
      hyperlink: types.optional(types.string()),
      note: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "bool_value": "boolValue",
      });
    }),
  );

export function boolValueFromJSON(
  jsonString: string,
): SafeParseResult<BoolValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BoolValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BoolValue' from JSON`,
  );
}

/** @internal */
export const QcrV1alphaDataCell$inboundSchema: z.ZodMiniType<
  QcrV1alphaDataCell,
  unknown
> = smartUnion([
  z.lazy(() => BoolValue$inboundSchema),
  z.lazy(() => ErrorValue$inboundSchema),
  z.lazy(() => NumberValue$inboundSchema),
  z.lazy(() => StringValue$inboundSchema),
]);

export function qcrV1alphaDataCellFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaDataCell, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaDataCell$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaDataCell' from JSON`,
  );
}
