/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaTableWidthMode,
  QcrV1alphaTableWidthMode$inboundSchema,
} from "./qcrv1alphatablewidthmode.js";

export type QcrV1alphaTableLayout = {
  columnWidthsMm?: Array<number> | undefined;
  widthMode?: QcrV1alphaTableWidthMode | undefined;
};

/** @internal */
export const QcrV1alphaTableLayout$inboundSchema: z.ZodMiniType<
  QcrV1alphaTableLayout,
  unknown
> = z.pipe(
  z.object({
    column_widths_mm: types.optional(z.array(types.number())),
    width_mode: types.optional(QcrV1alphaTableWidthMode$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "column_widths_mm": "columnWidthsMm",
      "width_mode": "widthMode",
    });
  }),
);

export function qcrV1alphaTableLayoutFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaTableLayout, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaTableLayout$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaTableLayout' from JSON`,
  );
}
