/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type QcrV1alphaFrozenPane = {
  /**
   * 0 = no col freeze; N = cols 0..N-1 frozen
   */
  frozenCol?: number | undefined;
  /**
   * 0 = no row freeze; N = rows 0..N-1 frozen
   */
  frozenRow?: number | undefined;
};

/** @internal */
export const QcrV1alphaFrozenPane$inboundSchema: z.ZodMiniType<
  QcrV1alphaFrozenPane,
  unknown
> = z.pipe(
  z.object({
    frozen_col: types.optional(types.number()),
    frozen_row: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "frozen_col": "frozenCol",
      "frozen_row": "frozenRow",
    });
  }),
);

export function qcrV1alphaFrozenPaneFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaFrozenPane, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaFrozenPane$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaFrozenPane' from JSON`,
  );
}
