/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const QcrV1alphaVerticalAlignment = {
  VerticalAlignmentUnspecified: "VERTICAL_ALIGNMENT_UNSPECIFIED",
  VerticalAlignmentTop: "VERTICAL_ALIGNMENT_TOP",
  VerticalAlignmentCenter: "VERTICAL_ALIGNMENT_CENTER",
  VerticalAlignmentBottom: "VERTICAL_ALIGNMENT_BOTTOM",
} as const;
export type QcrV1alphaVerticalAlignment = OpenEnum<
  typeof QcrV1alphaVerticalAlignment
>;

/** @internal */
export const QcrV1alphaVerticalAlignment$inboundSchema: z.ZodMiniType<
  QcrV1alphaVerticalAlignment,
  unknown
> = openEnums.inboundSchema(QcrV1alphaVerticalAlignment);
