/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Row = {
  /**
   * index into TableData.rows[]
   */
  row: number;
};

export type Item = {
  /**
   * index into ListData.items[] or sub_list.items[]
   */
  item: number;
};

export type Cell = {
  /**
   * index into Row.cells[]
   */
  cell: number;
};

export type Block = {
  /**
   * index into blocks[] (document-level or section-level)
   */
  block: number;
};

export type QcrV1alphaPathSegment = Block | Cell | Item | Row;

/** @internal */
export const Row$inboundSchema: z.ZodMiniType<Row, unknown> = z.object({
  row: types.number(),
});

export function rowFromJSON(
  jsonString: string,
): SafeParseResult<Row, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Row$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Row' from JSON`,
  );
}

/** @internal */
export const Item$inboundSchema: z.ZodMiniType<Item, unknown> = z.object({
  item: types.number(),
});

export function itemFromJSON(
  jsonString: string,
): SafeParseResult<Item, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item' from JSON`,
  );
}

/** @internal */
export const Cell$inboundSchema: z.ZodMiniType<Cell, unknown> = z.object({
  cell: types.number(),
});

export function cellFromJSON(
  jsonString: string,
): SafeParseResult<Cell, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Cell$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Cell' from JSON`,
  );
}

/** @internal */
export const Block$inboundSchema: z.ZodMiniType<Block, unknown> = z.object({
  block: types.number(),
});

export function blockFromJSON(
  jsonString: string,
): SafeParseResult<Block, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Block$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Block' from JSON`,
  );
}

/** @internal */
export const QcrV1alphaPathSegment$inboundSchema: z.ZodMiniType<
  QcrV1alphaPathSegment,
  unknown
> = smartUnion([
  z.lazy(() => Block$inboundSchema),
  z.lazy(() => Cell$inboundSchema),
  z.lazy(() => Item$inboundSchema),
  z.lazy(() => Row$inboundSchema),
]);

export function qcrV1alphaPathSegmentFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaPathSegment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaPathSegment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaPathSegment' from JSON`,
  );
}
