/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const QcrV1alphaNumberFormatCategory = {
  NumberFormatCategoryUnspecified: "NUMBER_FORMAT_CATEGORY_UNSPECIFIED",
  NumberFormatCategoryGeneral: "NUMBER_FORMAT_CATEGORY_GENERAL",
  NumberFormatCategoryNumber: "NUMBER_FORMAT_CATEGORY_NUMBER",
  NumberFormatCategoryCurrency: "NUMBER_FORMAT_CATEGORY_CURRENCY",
  NumberFormatCategoryAccounting: "NUMBER_FORMAT_CATEGORY_ACCOUNTING",
  NumberFormatCategoryPercentage: "NUMBER_FORMAT_CATEGORY_PERCENTAGE",
  NumberFormatCategoryFraction: "NUMBER_FORMAT_CATEGORY_FRACTION",
  NumberFormatCategoryScientific: "NUMBER_FORMAT_CATEGORY_SCIENTIFIC",
  NumberFormatCategoryText: "NUMBER_FORMAT_CATEGORY_TEXT",
  NumberFormatCategoryDate: "NUMBER_FORMAT_CATEGORY_DATE",
  NumberFormatCategoryTime: "NUMBER_FORMAT_CATEGORY_TIME",
  NumberFormatCategoryDateTime: "NUMBER_FORMAT_CATEGORY_DATE_TIME",
  NumberFormatCategoryDuration: "NUMBER_FORMAT_CATEGORY_DURATION",
} as const;
export type QcrV1alphaNumberFormatCategory = OpenEnum<
  typeof QcrV1alphaNumberFormatCategory
>;

/** @internal */
export const QcrV1alphaNumberFormatCategory$inboundSchema: z.ZodMiniType<
  QcrV1alphaNumberFormatCategory,
  unknown
> = openEnums.inboundSchema(QcrV1alphaNumberFormatCategory);
