/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type QcrV1alphaHeadingData = {
  level?: number | undefined;
  text?: string | undefined;
};

/** @internal */
export const QcrV1alphaHeadingData$inboundSchema: z.ZodMiniType<
  QcrV1alphaHeadingData,
  unknown
> = z.object({
  level: types.optional(types.number()),
  text: types.optional(types.string()),
});

export function qcrV1alphaHeadingDataFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaHeadingData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaHeadingData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaHeadingData' from JSON`,
  );
}
