/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type QcrV1alphaQuoteData = {
  text?: string | undefined;
};

/** @internal */
export const QcrV1alphaQuoteData$inboundSchema: z.ZodMiniType<
  QcrV1alphaQuoteData,
  unknown
> = z.object({
  text: types.optional(types.string()),
});

export function qcrV1alphaQuoteDataFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaQuoteData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaQuoteData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaQuoteData' from JSON`,
  );
}
