/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaCellLayoutBinding,
  QcrV1alphaCellLayoutBinding$inboundSchema,
} from "./qcrv1alphacelllayoutbinding.js";
import {
  QcrV1alphaColumnFormatBinding,
  QcrV1alphaColumnFormatBinding$inboundSchema,
} from "./qcrv1alphacolumnformatbinding.js";
import {
  QcrV1alphaColumnLayout,
  QcrV1alphaColumnLayout$inboundSchema,
} from "./qcrv1alphacolumnlayout.js";
import {
  QcrV1alphaDirection,
  QcrV1alphaDirection$inboundSchema,
} from "./qcrv1alphadirection.js";
import {
  QcrV1alphaFrozenPane,
  QcrV1alphaFrozenPane$inboundSchema,
} from "./qcrv1alphafrozenpane.js";
import {
  QcrV1alphaMergedRegion,
  QcrV1alphaMergedRegion$inboundSchema,
} from "./qcrv1alphamergedregion.js";
import {
  QcrV1alphaRowLayout,
  QcrV1alphaRowLayout$inboundSchema,
} from "./qcrv1alpharowlayout.js";

export type QcrV1alphaSheetLayout = {
  cellBindings?: Array<QcrV1alphaCellLayoutBinding> | undefined;
  columnFormats?: Array<QcrV1alphaColumnFormatBinding> | undefined;
  columns?: Array<QcrV1alphaColumnLayout> | undefined;
  /**
   * Text direction / reading order.
   */
  direction?: QcrV1alphaDirection | undefined;
  frozenPane?: QcrV1alphaFrozenPane | undefined;
  isHidden?: boolean | undefined;
  mergedRegions?: Array<QcrV1alphaMergedRegion> | undefined;
  rows?: Array<QcrV1alphaRowLayout> | undefined;
  /**
   * references Sheet.name
   */
  sheetName?: string | undefined;
};

/** @internal */
export const QcrV1alphaSheetLayout$inboundSchema: z.ZodMiniType<
  QcrV1alphaSheetLayout,
  unknown
> = z.pipe(
  z.object({
    cell_bindings: types.optional(
      z.array(QcrV1alphaCellLayoutBinding$inboundSchema),
    ),
    column_formats: types.optional(
      z.array(QcrV1alphaColumnFormatBinding$inboundSchema),
    ),
    columns: types.optional(z.array(QcrV1alphaColumnLayout$inboundSchema)),
    direction: types.optional(QcrV1alphaDirection$inboundSchema),
    frozen_pane: types.optional(QcrV1alphaFrozenPane$inboundSchema),
    is_hidden: types.optional(types.boolean()),
    merged_regions: types.optional(
      z.array(QcrV1alphaMergedRegion$inboundSchema),
    ),
    rows: types.optional(z.array(QcrV1alphaRowLayout$inboundSchema)),
    sheet_name: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "cell_bindings": "cellBindings",
      "column_formats": "columnFormats",
      "frozen_pane": "frozenPane",
      "is_hidden": "isHidden",
      "merged_regions": "mergedRegions",
      "sheet_name": "sheetName",
    });
  }),
);

export function qcrV1alphaSheetLayoutFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaSheetLayout, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaSheetLayout$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaSheetLayout' from JSON`,
  );
}
