/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaVectorImageData,
  QcrV1alphaVectorImageData$inboundSchema,
} from "./qcrv1alphavectorimagedata.js";
import { Value, Value$inboundSchema } from "./value.js";

/**
 * Chart rendered as a figure plus metadata.
 */
export type QcrV1alphaSheetChart = {
  anchorCol?: number | undefined;
  anchorRow?: number | undefined;
  /**
   * `Struct` represents a structured data value, consisting of fields
   *
   * @remarks
   *  which map to dynamically typed values. In some languages, `Struct`
   *  might be supported by a native representation. For example, in
   *  scripting languages like JS a struct is represented as an
   *  object. The details of that representation are described together
   *  with the proto support for the language.
   *
   *  The JSON representation for `Struct` is JSON object.
   */
  attributes?: { [k: string]: Value | null } | undefined;
  /**
   * e.g., "bar", "line", "pie"
   */
  chartType?: string | undefined;
  /**
   * VectorImageData represents a vector graphic (SVG, diagram, chart).
   */
  rendered?: QcrV1alphaVectorImageData | undefined;
  /**
   * A1-notation data ranges
   */
  sourceRanges?: Array<string> | undefined;
  title?: string | undefined;
};

/** @internal */
export const QcrV1alphaSheetChart$inboundSchema: z.ZodMiniType<
  QcrV1alphaSheetChart,
  unknown
> = z.pipe(
  z.object({
    anchor_col: types.optional(types.number()),
    anchor_row: types.optional(types.number()),
    attributes: types.optional(
      z.record(z.string(), types.nullable(Value$inboundSchema)),
    ),
    chart_type: types.optional(types.string()),
    rendered: types.optional(QcrV1alphaVectorImageData$inboundSchema),
    source_ranges: types.optional(z.array(types.string())),
    title: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "anchor_col": "anchorCol",
      "anchor_row": "anchorRow",
      "chart_type": "chartType",
      "source_ranges": "sourceRanges",
    });
  }),
);

export function qcrV1alphaSheetChartFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaSheetChart, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaSheetChart$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaSheetChart' from JSON`,
  );
}
