/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Normalized bounding box relative to the page (0.0–1.0).
 *
 * @remarks
 *  Origin is top-left: (0,0) is the top-left corner of the page,
 *  x increases rightward, y increases downward.
 *  Extraction pipelines must flip the y-axis for bottom-left origin formats (PDF).
 *  To get absolute coordinates, multiply by the page's PhysicalDimensions.
 */
export type QcrV1alphaBoundingBox = {
  height?: number | undefined;
  width?: number | undefined;
  x?: number | undefined;
  y?: number | undefined;
};

/** @internal */
export const QcrV1alphaBoundingBox$inboundSchema: z.ZodMiniType<
  QcrV1alphaBoundingBox,
  unknown
> = z.object({
  height: types.optional(types.number()),
  width: types.optional(types.number()),
  x: types.optional(types.number()),
  y: types.optional(types.number()),
});

export function qcrV1alphaBoundingBoxFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaBoundingBox, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaBoundingBox$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaBoundingBox' from JSON`,
  );
}
