/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const QcrV1alphaLineSpacing = {
  LineSpacingUnspecified: "LINE_SPACING_UNSPECIFIED",
  LineSpacingSingle: "LINE_SPACING_SINGLE",
  LineSpacingOneAndHalf: "LINE_SPACING_ONE_AND_HALF",
  LineSpacingDouble: "LINE_SPACING_DOUBLE",
} as const;
export type QcrV1alphaLineSpacing = OpenEnum<typeof QcrV1alphaLineSpacing>;

/** @internal */
export const QcrV1alphaLineSpacing$inboundSchema: z.ZodMiniType<
  QcrV1alphaLineSpacing,
  unknown
> = openEnums.inboundSchema(QcrV1alphaLineSpacing);
