/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Text direction / reading order.
 */
export const QcrV1alphaDirection = {
  DirectionUnspecified: "DIRECTION_UNSPECIFIED",
  DirectionLtr: "DIRECTION_LTR",
  DirectionRtl: "DIRECTION_RTL",
} as const;
/**
 * Text direction / reading order.
 */
export type QcrV1alphaDirection = OpenEnum<typeof QcrV1alphaDirection>;

/** @internal */
export const QcrV1alphaDirection$inboundSchema: z.ZodMiniType<
  QcrV1alphaDirection,
  unknown
> = openEnums.inboundSchema(QcrV1alphaDirection);
