/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaListData,
  QcrV1alphaListData$inboundSchema,
} from "./qcrv1alphalistdata.js";

export type QcrV1alphaListDataItem = {
  subList?: QcrV1alphaListData | undefined;
  text?: string | undefined;
};

/** @internal */
export const QcrV1alphaListDataItem$inboundSchema: z.ZodMiniType<
  QcrV1alphaListDataItem,
  unknown
> = z.pipe(
  z.object({
    sub_list: types.optional(z.lazy(() => QcrV1alphaListData$inboundSchema)),
    text: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "sub_list": "subList",
    });
  }),
);

export function qcrV1alphaListDataItemFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaListDataItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaListDataItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaListDataItem' from JSON`,
  );
}
