/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaTableDataRowCell,
  QcrV1alphaTableDataRowCell$inboundSchema,
} from "./qcrv1alphatabledatarowcell.js";

export type QcrV1alphaTableDataRow = {
  cells?: Array<QcrV1alphaTableDataRowCell> | undefined;
};

/** @internal */
export const QcrV1alphaTableDataRow$inboundSchema: z.ZodMiniType<
  QcrV1alphaTableDataRow,
  unknown
> = z.object({
  cells: types.optional(z.array(QcrV1alphaTableDataRowCell$inboundSchema)),
});

export function qcrV1alphaTableDataRowFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaTableDataRow, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaTableDataRow$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaTableDataRow' from JSON`,
  );
}
