/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type QcrV1alphaIndentation = {
  /**
   * positive = indent, negative = hanging
   */
  firstLineMm?: number | undefined;
  leftMm?: number | undefined;
  rightMm?: number | undefined;
};

/** @internal */
export const QcrV1alphaIndentation$inboundSchema: z.ZodMiniType<
  QcrV1alphaIndentation,
  unknown
> = z.pipe(
  z.object({
    first_line_mm: types.optional(types.number()),
    left_mm: types.optional(types.number()),
    right_mm: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "first_line_mm": "firstLineMm",
      "left_mm": "leftMm",
      "right_mm": "rightMm",
    });
  }),
);

export function qcrV1alphaIndentationFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaIndentation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaIndentation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaIndentation' from JSON`,
  );
}
