/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Value, Value$inboundSchema } from "./value.js";

/**
 * SourceReference links a record back to the source it was extracted from.
 *
 * @remarks
 *
 *  Three typed fields identify WHAT, WHERE, and WHEN. Everything else —
 *  format, content hash, storage location, checksums, external URLs — goes
 *  in the attributes bag, because the relevant metadata varies by source type.
 *
 *  Examples by source type:
 *
 *    File upload:
 *      source_id  = "intg_01j8k..."                    (upload channel instance)
 *      remote_id  = "req_01h2xcejqtf2nbrexx3vqjhp41"   (upload request ID)
 *      attributes = {format: "pdf", location: "uploads/.../original.pdf",
 *                    content_hash: "a1b2c3...", storage_etag: "\"abc\""}
 *
 *    Gmail integration:
 *      source_id  = "intg_01k9m..."                    (Gmail connector instance)
 *      remote_id  = "18abc123def"                       (Gmail message ID)
 *      attributes = {format: "eml", thread_id: "...",
 *                    external_url: "https://mail.google.com/..."}
 *
 *    Confluence sync:
 *      source_id  = "intg_01p3q..."                    (Confluence connector instance)
 *      remote_id  = "12345678"                          (Confluence page ID)
 *      attributes = {format: "html", space_key: "ENG",
 *                    external_url: "https://acme.atlassian.net/wiki/..."}
 */
export type QcrV1alphaSourceReference = {
  /**
   * `Struct` represents a structured data value, consisting of fields
   *
   * @remarks
   *  which map to dynamically typed values. In some languages, `Struct`
   *  might be supported by a native representation. For example, in
   *  scripting languages like JS a struct is represented as an
   *  object. The details of that representation are described together
   *  with the proto support for the language.
   *
   *  The JSON representation for `Struct` is JSON object.
   */
  attributes?: { [k: string]: Value | null } | undefined;
  /**
   * When this content was ingested into the system.
   */
  ingestedAt?: Date | undefined;
  /**
   * The content's coordinates in the external system — whatever identifier
   *
   * @remarks
   *  the source system uses for this specific piece of content.
   *  Examples: upload request ID, Gmail message ID, Confluence page ID,
   *            S3 object key, Merge remote_id.
   */
  remoteId?: string | undefined;
  /**
   * Identifies the integration or connector instance that produced this
   *
   * @remarks
   *  record. Stable across re-syncs of the same source.
   *  Example: "intg_01j8k..." (opaque ID from integration registry).
   */
  sourceId?: string | undefined;
};

/** @internal */
export const QcrV1alphaSourceReference$inboundSchema: z.ZodMiniType<
  QcrV1alphaSourceReference,
  unknown
> = z.pipe(
  z.object({
    attributes: types.optional(
      z.record(z.string(), types.nullable(Value$inboundSchema)),
    ),
    ingested_at: types.optional(types.date()),
    remote_id: types.optional(types.string()),
    source_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "ingested_at": "ingestedAt",
      "remote_id": "remoteId",
      "source_id": "sourceId",
    });
  }),
);

export function qcrV1alphaSourceReferenceFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaSourceReference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaSourceReference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaSourceReference' from JSON`,
  );
}
