/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaDataTable,
  QcrV1alphaDataTable$inboundSchema,
} from "./qcrv1alphadatatable.js";
import {
  QcrV1alphaSheetChart,
  QcrV1alphaSheetChart$inboundSchema,
} from "./qcrv1alphasheetchart.js";
import {
  QcrV1alphaSheetImage,
  QcrV1alphaSheetImage$inboundSchema,
} from "./qcrv1alphasheetimage.js";
import { Value, Value$inboundSchema } from "./value.js";

export type QcrV1alphaSheet = {
  /**
   * `Struct` represents a structured data value, consisting of fields
   *
   * @remarks
   *  which map to dynamically typed values. In some languages, `Struct`
   *  might be supported by a native representation. For example, in
   *  scripting languages like JS a struct is represented as an
   *  object. The details of that representation are described together
   *  with the proto support for the language.
   *
   *  The JSON representation for `Struct` is JSON object.
   */
  attributes?: { [k: string]: Value | null } | undefined;
  charts?: Array<QcrV1alphaSheetChart> | undefined;
  images?: Array<QcrV1alphaSheetImage> | undefined;
  /**
   * unique within workbook, used as join key by SheetLayout
   */
  name?: string | undefined;
  tables?: Array<QcrV1alphaDataTable> | undefined;
};

/** @internal */
export const QcrV1alphaSheet$inboundSchema: z.ZodMiniType<
  QcrV1alphaSheet,
  unknown
> = z.object({
  attributes: types.optional(
    z.record(z.string(), types.nullable(Value$inboundSchema)),
  ),
  charts: types.optional(z.array(QcrV1alphaSheetChart$inboundSchema)),
  images: types.optional(z.array(QcrV1alphaSheetImage$inboundSchema)),
  name: types.optional(types.string()),
  tables: types.optional(z.array(QcrV1alphaDataTable$inboundSchema)),
});

export function qcrV1alphaSheetFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaSheet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaSheet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaSheet' from JSON`,
  );
}
