/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type QcrV1alphaCodeBlockData = {
  code?: string | undefined;
  language?: string | undefined;
};

/** @internal */
export const QcrV1alphaCodeBlockData$inboundSchema: z.ZodMiniType<
  QcrV1alphaCodeBlockData,
  unknown
> = z.object({
  code: types.optional(types.string()),
  language: types.optional(types.string()),
});

export function qcrV1alphaCodeBlockDataFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaCodeBlockData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaCodeBlockData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaCodeBlockData' from JSON`,
  );
}
