/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaBlock,
  QcrV1alphaBlock$inboundSchema,
} from "./qcrv1alphablock.js";
import {
  QcrV1alphaDocumentMetadata,
  QcrV1alphaDocumentMetadata$inboundSchema,
} from "./qcrv1alphadocumentmetadata.js";
import {
  QcrV1alphaSourceReference,
  QcrV1alphaSourceReference$inboundSchema,
} from "./qcrv1alphasourcereference.js";

/**
 * DocumentRecord is the QCR representation of an ingested document.
 *
 * @remarks
 *  Immutable once extracted. Source-format-agnostic.
 *
 *  Structure is a flat sequence of blocks. Sections provide optional grouping
 *  and can nest, but block-level elements (paragraphs, tables, etc.) are leaves
 *  — they do not contain other blocks. This constrains nesting to only what is
 *  semantically valid and gives every element a natural positional address.
 *
 *  Addressing convention: every element is addressable by its index path through
 *  the typed containment hierarchy. Examples:
 *    blocks[2]                        → third block
 *    blocks[2].section.blocks[0]      → first block inside a section
 *    blocks[4].table.rows[1].cells[0] → second row, first cell of a table
 *    blocks[3].list.items[2]          → third item of a list
 *
 *  These addresses are deterministic for a given record and are used by
 *  DocumentLayout to join layout data to semantic content.
 */
export type QcrV1alphaDocumentRecord = {
  blocks?: Array<QcrV1alphaBlock> | undefined;
  id?: string | undefined;
  metadata?: QcrV1alphaDocumentMetadata | undefined;
  /**
   * SourceReference links a record back to the source it was extracted from.
   *
   * @remarks
   *
   *  Three typed fields identify WHAT, WHERE, and WHEN. Everything else —
   *  format, content hash, storage location, checksums, external URLs — goes
   *  in the attributes bag, because the relevant metadata varies by source type.
   *
   *  Examples by source type:
   *
   *    File upload:
   *      source_id  = "intg_01j8k..."                    (upload channel instance)
   *      remote_id  = "req_01h2xcejqtf2nbrexx3vqjhp41"   (upload request ID)
   *      attributes = {format: "pdf", location: "uploads/.../original.pdf",
   *                    content_hash: "a1b2c3...", storage_etag: "\"abc\""}
   *
   *    Gmail integration:
   *      source_id  = "intg_01k9m..."                    (Gmail connector instance)
   *      remote_id  = "18abc123def"                       (Gmail message ID)
   *      attributes = {format: "eml", thread_id: "...",
   *                    external_url: "https://mail.google.com/..."}
   *
   *    Confluence sync:
   *      source_id  = "intg_01p3q..."                    (Confluence connector instance)
   *      remote_id  = "12345678"                          (Confluence page ID)
   *      attributes = {format: "html", space_key: "ENG",
   *                    external_url: "https://acme.atlassian.net/wiki/..."}
   */
  source?: QcrV1alphaSourceReference | undefined;
};

/** @internal */
export const QcrV1alphaDocumentRecord$inboundSchema: z.ZodMiniType<
  QcrV1alphaDocumentRecord,
  unknown
> = z.object({
  blocks: types.optional(z.array(QcrV1alphaBlock$inboundSchema)),
  id: types.optional(types.string()),
  metadata: types.optional(QcrV1alphaDocumentMetadata$inboundSchema),
  source: types.optional(QcrV1alphaSourceReference$inboundSchema),
});

export function qcrV1alphaDocumentRecordFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaDocumentRecord, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaDocumentRecord$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaDocumentRecord' from JSON`,
  );
}
