/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaOrientation,
  QcrV1alphaOrientation$inboundSchema,
} from "./qcrv1alphaorientation.js";
import {
  QcrV1alphaPhysicalDimensions,
  QcrV1alphaPhysicalDimensions$inboundSchema,
} from "./qcrv1alphaphysicaldimensions.js";

/**
 * Per-page geometry. Every page gets an entry (indexed by page_number).
 *
 * @remarks
 *  Pages that match defaults can omit dimensions/orientation and inherit.
 */
export type QcrV1alphaPageGeometry = {
  /**
   * Physical dimensions in millimeters.
   */
  dimensions?: QcrV1alphaPhysicalDimensions | undefined;
  orientation?: QcrV1alphaOrientation | undefined;
  /**
   * 0-indexed
   */
  pageNumber?: number | undefined;
};

/** @internal */
export const QcrV1alphaPageGeometry$inboundSchema: z.ZodMiniType<
  QcrV1alphaPageGeometry,
  unknown
> = z.pipe(
  z.object({
    dimensions: types.optional(QcrV1alphaPhysicalDimensions$inboundSchema),
    orientation: types.optional(QcrV1alphaOrientation$inboundSchema),
    page_number: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "page_number": "pageNumber",
    });
  }),
);

export function qcrV1alphaPageGeometryFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaPageGeometry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaPageGeometry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaPageGeometry' from JSON`,
  );
}
