/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type QcrV1alphaFootnoteData = {
  label?: string | undefined;
  text?: string | undefined;
};

/** @internal */
export const QcrV1alphaFootnoteData$inboundSchema: z.ZodMiniType<
  QcrV1alphaFootnoteData,
  unknown
> = z.object({
  label: types.optional(types.string()),
  text: types.optional(types.string()),
});

export function qcrV1alphaFootnoteDataFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaFootnoteData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaFootnoteData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaFootnoteData' from JSON`,
  );
}
