/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaDataCell,
  QcrV1alphaDataCell$inboundSchema,
} from "./qcrv1alphadatacell.js";
import { Value, Value$inboundSchema } from "./value.js";

/**
 * DataRow is a single record in a DataTable.
 *
 * @remarks
 *  cells are positional: cells[i] corresponds to columns[i].
 */
export type QcrV1alphaDataRow = {
  /**
   * `Struct` represents a structured data value, consisting of fields
   *
   * @remarks
   *  which map to dynamically typed values. In some languages, `Struct`
   *  might be supported by a native representation. For example, in
   *  scripting languages like JS a struct is represented as an
   *  object. The details of that representation are described together
   *  with the proto support for the language.
   *
   *  The JSON representation for `Struct` is JSON object.
   */
  attributes?: { [k: string]: Value | null } | undefined;
  cells?: Array<QcrV1alphaDataCell> | undefined;
};

/** @internal */
export const QcrV1alphaDataRow$inboundSchema: z.ZodMiniType<
  QcrV1alphaDataRow,
  unknown
> = z.object({
  attributes: types.optional(
    z.record(z.string(), types.nullable(Value$inboundSchema)),
  ),
  cells: types.optional(z.array(QcrV1alphaDataCell$inboundSchema)),
});

export function qcrV1alphaDataRowFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaDataRow, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaDataRow$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaDataRow' from JSON`,
  );
}
