/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaMimeType,
  QcrV1alphaMimeType$inboundSchema,
} from "./qcrv1alphamimetype.js";

export type StorageRef = {
  /**
   * S3 key, CDN URL, or other stable reference
   */
  storageRef: string;
  mimeType?: QcrV1alphaMimeType | undefined;
};

export type InlineData = {
  /**
   * raw bytes for small/embedded content
   */
  inlineData: string;
  mimeType?: QcrV1alphaMimeType | undefined;
};

/**
 * DataSource represents a media payload — either a stable external reference
 *
 * @remarks
 *  or inline bytes — paired with its MIME type.
 */
export type QcrV1alphaDataSource = InlineData | StorageRef;

/** @internal */
export const StorageRef$inboundSchema: z.ZodMiniType<StorageRef, unknown> = z
  .pipe(
    z.object({
      storage_ref: types.string(),
      mime_type: types.optional(QcrV1alphaMimeType$inboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        "storage_ref": "storageRef",
        "mime_type": "mimeType",
      });
    }),
  );

export function storageRefFromJSON(
  jsonString: string,
): SafeParseResult<StorageRef, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StorageRef$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StorageRef' from JSON`,
  );
}

/** @internal */
export const InlineData$inboundSchema: z.ZodMiniType<InlineData, unknown> = z
  .pipe(
    z.object({
      inline_data: types.string(),
      mime_type: types.optional(QcrV1alphaMimeType$inboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        "inline_data": "inlineData",
        "mime_type": "mimeType",
      });
    }),
  );

export function inlineDataFromJSON(
  jsonString: string,
): SafeParseResult<InlineData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InlineData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InlineData' from JSON`,
  );
}

/** @internal */
export const QcrV1alphaDataSource$inboundSchema: z.ZodMiniType<
  QcrV1alphaDataSource,
  unknown
> = smartUnion([
  z.lazy(() => InlineData$inboundSchema),
  z.lazy(() => StorageRef$inboundSchema),
]);

export function qcrV1alphaDataSourceFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaDataSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaDataSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaDataSource' from JSON`,
  );
}
