/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Value, Value$inboundSchema } from "./value.js";

export type QcrV1alphaDocumentMetadata = {
  /**
   * `Struct` represents a structured data value, consisting of fields
   *
   * @remarks
   *  which map to dynamically typed values. In some languages, `Struct`
   *  might be supported by a native representation. For example, in
   *  scripting languages like JS a struct is represented as an
   *  object. The details of that representation are described together
   *  with the proto support for the language.
   *
   *  The JSON representation for `Struct` is JSON object.
   */
  attributes?: { [k: string]: Value | null } | undefined;
  extractedAt?: Date | undefined;
  language?: string | undefined;
  title?: string | undefined;
};

/** @internal */
export const QcrV1alphaDocumentMetadata$inboundSchema: z.ZodMiniType<
  QcrV1alphaDocumentMetadata,
  unknown
> = z.pipe(
  z.object({
    attributes: types.optional(
      z.record(z.string(), types.nullable(Value$inboundSchema)),
    ),
    extracted_at: types.optional(types.date()),
    language: types.optional(types.string()),
    title: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "extracted_at": "extractedAt",
    });
  }),
);

export function qcrV1alphaDocumentMetadataFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaDocumentMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaDocumentMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaDocumentMetadata' from JSON`,
  );
}
