/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Explicit authorial boundary (e.g. markdown `---`). Leaf block, no children.
 */
export type QcrV1alphaThematicBreakData = {};

/** @internal */
export const QcrV1alphaThematicBreakData$inboundSchema: z.ZodMiniType<
  QcrV1alphaThematicBreakData,
  unknown
> = z.object({});

export function qcrV1alphaThematicBreakDataFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaThematicBreakData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaThematicBreakData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaThematicBreakData' from JSON`,
  );
}
