/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaLineSpacingValue,
  QcrV1alphaLineSpacingValue$inboundSchema,
} from "./qcrv1alphalinespacingvalue.js";

export type QcrV1alphaBlockSpacing = {
  afterMm?: number | undefined;
  beforeMm?: number | undefined;
  /**
   * Line spacing as mode + optional explicit value.
   *
   * @remarks
   *  Using a message instead of a bare enum avoids a future wire break when
   *  exact/at-least modes are added (they need a companion float value).
   */
  lineSpacing?: QcrV1alphaLineSpacingValue | undefined;
};

/** @internal */
export const QcrV1alphaBlockSpacing$inboundSchema: z.ZodMiniType<
  QcrV1alphaBlockSpacing,
  unknown
> = z.pipe(
  z.object({
    after_mm: types.optional(types.number()),
    before_mm: types.optional(types.number()),
    line_spacing: types.optional(QcrV1alphaLineSpacingValue$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "after_mm": "afterMm",
      "before_mm": "beforeMm",
      "line_spacing": "lineSpacing",
    });
  }),
);

export function qcrV1alphaBlockSpacingFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaBlockSpacing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaBlockSpacing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaBlockSpacing' from JSON`,
  );
}
