/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaDataSource,
  QcrV1alphaDataSource$inboundSchema,
} from "./qcrv1alphadatasource.js";

/**
 * RasterImageData represents a raster image (PNG, JPEG, WebP, etc.).
 */
export type QcrV1alphaRasterImageData = {
  altText?: string | undefined;
  /**
   * DataSource represents a media payload — either a stable external reference
   *
   * @remarks
   *  or inline bytes — paired with its MIME type.
   */
  source?: QcrV1alphaDataSource | undefined;
};

/** @internal */
export const QcrV1alphaRasterImageData$inboundSchema: z.ZodMiniType<
  QcrV1alphaRasterImageData,
  unknown
> = z.pipe(
  z.object({
    alt_text: types.optional(types.string()),
    source: types.optional(QcrV1alphaDataSource$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "alt_text": "altText",
    });
  }),
);

export function qcrV1alphaRasterImageDataFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaRasterImageData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaRasterImageData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaRasterImageData' from JSON`,
  );
}
