/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Rectangular merge region. All bounds 0-indexed and inclusive.
 */
export type QcrV1alphaMergedRegion = {
  endCol?: number | undefined;
  endRow?: number | undefined;
  startCol?: number | undefined;
  startRow?: number | undefined;
};

/** @internal */
export const QcrV1alphaMergedRegion$inboundSchema: z.ZodMiniType<
  QcrV1alphaMergedRegion,
  unknown
> = z.pipe(
  z.object({
    end_col: types.optional(types.number()),
    end_row: types.optional(types.number()),
    start_col: types.optional(types.number()),
    start_row: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "end_col": "endCol",
      "end_row": "endRow",
      "start_col": "startCol",
      "start_row": "startRow",
    });
  }),
);

export function qcrV1alphaMergedRegionFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaMergedRegion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaMergedRegion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaMergedRegion' from JSON`,
  );
}
