/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaLineSpacing,
  QcrV1alphaLineSpacing$inboundSchema,
} from "./qcrv1alphalinespacing.js";

/**
 * Line spacing as mode + optional explicit value.
 *
 * @remarks
 *  Using a message instead of a bare enum avoids a future wire break when
 *  exact/at-least modes are added (they need a companion float value).
 */
export type QcrV1alphaLineSpacingValue = {
  mode?: QcrV1alphaLineSpacing | undefined;
  /**
   * meaningful only for EXACT / AT_LEAST (future)
   */
  valueMm?: number | undefined;
};

/** @internal */
export const QcrV1alphaLineSpacingValue$inboundSchema: z.ZodMiniType<
  QcrV1alphaLineSpacingValue,
  unknown
> = z.pipe(
  z.object({
    mode: types.optional(QcrV1alphaLineSpacing$inboundSchema),
    value_mm: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "value_mm": "valueMm",
    });
  }),
);

export function qcrV1alphaLineSpacingValueFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaLineSpacingValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaLineSpacingValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaLineSpacingValue' from JSON`,
  );
}
