/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaBlockSpacing,
  QcrV1alphaBlockSpacing$inboundSchema,
} from "./qcrv1alphablockspacing.js";
import {
  QcrV1alphaIndentation,
  QcrV1alphaIndentation$inboundSchema,
} from "./qcrv1alphaindentation.js";
import {
  QcrV1alphaTextAlignment,
  QcrV1alphaTextAlignment$inboundSchema,
} from "./qcrv1alphatextalignment.js";

/**
 * Layout for block-level text elements (paragraphs, headings, list items, quotes).
 */
export type QcrV1alphaTextBlockLayout = {
  alignment?: QcrV1alphaTextAlignment | undefined;
  indentation?: QcrV1alphaIndentation | undefined;
  spacing?: QcrV1alphaBlockSpacing | undefined;
};

/** @internal */
export const QcrV1alphaTextBlockLayout$inboundSchema: z.ZodMiniType<
  QcrV1alphaTextBlockLayout,
  unknown
> = z.object({
  alignment: types.optional(QcrV1alphaTextAlignment$inboundSchema),
  indentation: types.optional(QcrV1alphaIndentation$inboundSchema),
  spacing: types.optional(QcrV1alphaBlockSpacing$inboundSchema),
});

export function qcrV1alphaTextBlockLayoutFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaTextBlockLayout, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaTextBlockLayout$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaTextBlockLayout' from JSON`,
  );
}
