/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaBlockPath,
  QcrV1alphaBlockPath$inboundSchema,
} from "./qcrv1alphablockpath.js";
import {
  QcrV1alphaLayoutFragment,
  QcrV1alphaLayoutFragment$inboundSchema,
} from "./qcrv1alphalayoutfragment.js";
import {
  QcrV1alphaTableCellLayout,
  QcrV1alphaTableCellLayout$inboundSchema,
} from "./qcrv1alphatablecelllayout.js";
import {
  QcrV1alphaTableLayout,
  QcrV1alphaTableLayout$inboundSchema,
} from "./qcrv1alphatablelayout.js";
import {
  QcrV1alphaTableRowLayout,
  QcrV1alphaTableRowLayout$inboundSchema,
} from "./qcrv1alphatablerowlayout.js";
import {
  QcrV1alphaTextBlockLayout,
  QcrV1alphaTextBlockLayout$inboundSchema,
} from "./qcrv1alphatextblocklayout.js";

export type TextBlock = {
  /**
   * Layout for block-level text elements (paragraphs, headings, list items, quotes).
   */
  textBlock: QcrV1alphaTextBlockLayout;
  /**
   * Spatial fragments — one per page the element appears on.
   *
   * @remarks
   *  A paragraph spanning pages 3–4 has two fragments.
   *  Order matches reading order (fragment 0 is the first appearance).
   */
  fragments?: Array<QcrV1alphaLayoutFragment> | undefined;
  /**
   * BlockPath addresses an element within the record's typed containment
   *
   * @remarks
   *  hierarchy. Each segment steps into a specific typed child collection.
   *
   *  Examples:
   *    [block(2)]                                → blocks[2]
   *    [block(2), block(0)]                      → blocks[2].section.blocks[0]
   *    [block(4), row(1), cell(0)]               → blocks[4].table.rows[1].cells[0]
   *    [block(3), item(2)]                       → blocks[3].list.items[2]
   *    [block(3), item(2), item(0)]              → nested sub-list item
   *
   *  The path is unambiguous because each segment type implies which child
   *  collection to descend into (blocks for sections, rows for tables, etc.).
   */
  path?: QcrV1alphaBlockPath | undefined;
};

export type TableRow = {
  tableRow: QcrV1alphaTableRowLayout;
  /**
   * Spatial fragments — one per page the element appears on.
   *
   * @remarks
   *  A paragraph spanning pages 3–4 has two fragments.
   *  Order matches reading order (fragment 0 is the first appearance).
   */
  fragments?: Array<QcrV1alphaLayoutFragment> | undefined;
  /**
   * BlockPath addresses an element within the record's typed containment
   *
   * @remarks
   *  hierarchy. Each segment steps into a specific typed child collection.
   *
   *  Examples:
   *    [block(2)]                                → blocks[2]
   *    [block(2), block(0)]                      → blocks[2].section.blocks[0]
   *    [block(4), row(1), cell(0)]               → blocks[4].table.rows[1].cells[0]
   *    [block(3), item(2)]                       → blocks[3].list.items[2]
   *    [block(3), item(2), item(0)]              → nested sub-list item
   *
   *  The path is unambiguous because each segment type implies which child
   *  collection to descend into (blocks for sections, rows for tables, etc.).
   */
  path?: QcrV1alphaBlockPath | undefined;
};

export type TableCell = {
  tableCell: QcrV1alphaTableCellLayout;
  /**
   * Spatial fragments — one per page the element appears on.
   *
   * @remarks
   *  A paragraph spanning pages 3–4 has two fragments.
   *  Order matches reading order (fragment 0 is the first appearance).
   */
  fragments?: Array<QcrV1alphaLayoutFragment> | undefined;
  /**
   * BlockPath addresses an element within the record's typed containment
   *
   * @remarks
   *  hierarchy. Each segment steps into a specific typed child collection.
   *
   *  Examples:
   *    [block(2)]                                → blocks[2]
   *    [block(2), block(0)]                      → blocks[2].section.blocks[0]
   *    [block(4), row(1), cell(0)]               → blocks[4].table.rows[1].cells[0]
   *    [block(3), item(2)]                       → blocks[3].list.items[2]
   *    [block(3), item(2), item(0)]              → nested sub-list item
   *
   *  The path is unambiguous because each segment type implies which child
   *  collection to descend into (blocks for sections, rows for tables, etc.).
   */
  path?: QcrV1alphaBlockPath | undefined;
};

export type QcrV1alphaLayoutBindingTable = {
  table: QcrV1alphaTableLayout;
  /**
   * Spatial fragments — one per page the element appears on.
   *
   * @remarks
   *  A paragraph spanning pages 3–4 has two fragments.
   *  Order matches reading order (fragment 0 is the first appearance).
   */
  fragments?: Array<QcrV1alphaLayoutFragment> | undefined;
  /**
   * BlockPath addresses an element within the record's typed containment
   *
   * @remarks
   *  hierarchy. Each segment steps into a specific typed child collection.
   *
   *  Examples:
   *    [block(2)]                                → blocks[2]
   *    [block(2), block(0)]                      → blocks[2].section.blocks[0]
   *    [block(4), row(1), cell(0)]               → blocks[4].table.rows[1].cells[0]
   *    [block(3), item(2)]                       → blocks[3].list.items[2]
   *    [block(3), item(2), item(0)]              → nested sub-list item
   *
   *  The path is unambiguous because each segment type implies which child
   *  collection to descend into (blocks for sections, rows for tables, etc.).
   */
  path?: QcrV1alphaBlockPath | undefined;
};

/**
 * LayoutBinding attaches layout data to a specific element in the record.
 *
 * @remarks
 *  One binding per addressable element. Elements without layout data have no
 *  binding entry (sparse).
 */
export type QcrV1alphaLayoutBinding =
  | QcrV1alphaLayoutBindingTable
  | TableCell
  | TableRow
  | TextBlock;

/** @internal */
export const TextBlock$inboundSchema: z.ZodMiniType<TextBlock, unknown> = z
  .pipe(
    z.object({
      text_block: QcrV1alphaTextBlockLayout$inboundSchema,
      fragments: types.optional(
        z.array(QcrV1alphaLayoutFragment$inboundSchema),
      ),
      path: types.optional(QcrV1alphaBlockPath$inboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        "text_block": "textBlock",
      });
    }),
  );

export function textBlockFromJSON(
  jsonString: string,
): SafeParseResult<TextBlock, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextBlock$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextBlock' from JSON`,
  );
}

/** @internal */
export const TableRow$inboundSchema: z.ZodMiniType<TableRow, unknown> = z.pipe(
  z.object({
    table_row: QcrV1alphaTableRowLayout$inboundSchema,
    fragments: types.optional(z.array(QcrV1alphaLayoutFragment$inboundSchema)),
    path: types.optional(QcrV1alphaBlockPath$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "table_row": "tableRow",
    });
  }),
);

export function tableRowFromJSON(
  jsonString: string,
): SafeParseResult<TableRow, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TableRow$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TableRow' from JSON`,
  );
}

/** @internal */
export const TableCell$inboundSchema: z.ZodMiniType<TableCell, unknown> = z
  .pipe(
    z.object({
      table_cell: QcrV1alphaTableCellLayout$inboundSchema,
      fragments: types.optional(
        z.array(QcrV1alphaLayoutFragment$inboundSchema),
      ),
      path: types.optional(QcrV1alphaBlockPath$inboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        "table_cell": "tableCell",
      });
    }),
  );

export function tableCellFromJSON(
  jsonString: string,
): SafeParseResult<TableCell, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TableCell$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TableCell' from JSON`,
  );
}

/** @internal */
export const QcrV1alphaLayoutBindingTable$inboundSchema: z.ZodMiniType<
  QcrV1alphaLayoutBindingTable,
  unknown
> = z.object({
  table: QcrV1alphaTableLayout$inboundSchema,
  fragments: types.optional(z.array(QcrV1alphaLayoutFragment$inboundSchema)),
  path: types.optional(QcrV1alphaBlockPath$inboundSchema),
});

export function qcrV1alphaLayoutBindingTableFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaLayoutBindingTable, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaLayoutBindingTable$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaLayoutBindingTable' from JSON`,
  );
}

/** @internal */
export const QcrV1alphaLayoutBinding$inboundSchema: z.ZodMiniType<
  QcrV1alphaLayoutBinding,
  unknown
> = smartUnion([
  z.lazy(() => QcrV1alphaLayoutBindingTable$inboundSchema),
  z.lazy(() => TableCell$inboundSchema),
  z.lazy(() => TableRow$inboundSchema),
  z.lazy(() => TextBlock$inboundSchema),
]);

export function qcrV1alphaLayoutBindingFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaLayoutBinding, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaLayoutBinding$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaLayoutBinding' from JSON`,
  );
}
