/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Directional spacing (padding, insets). Same shape as Margins but distinct
 *
 * @remarks
 *  semantic meaning — internal spacing rather than external.
 */
export type QcrV1alphaInsets = {
  bottomMm?: number | undefined;
  leftMm?: number | undefined;
  rightMm?: number | undefined;
  topMm?: number | undefined;
};

/** @internal */
export const QcrV1alphaInsets$inboundSchema: z.ZodMiniType<
  QcrV1alphaInsets,
  unknown
> = z.pipe(
  z.object({
    bottom_mm: types.optional(types.number()),
    left_mm: types.optional(types.number()),
    right_mm: types.optional(types.number()),
    top_mm: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "bottom_mm": "bottomMm",
      "left_mm": "leftMm",
      "right_mm": "rightMm",
      "top_mm": "topMm",
    });
  }),
);

export function qcrV1alphaInsetsFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaInsets, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaInsets$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaInsets' from JSON`,
  );
}
