/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaRasterImageData,
  QcrV1alphaRasterImageData$inboundSchema,
} from "./qcrv1alpharasterimagedata.js";

export type QcrV1alphaSheetImage = {
  anchorCol?: number | undefined;
  anchorRow?: number | undefined;
  heightMm?: number | undefined;
  /**
   * RasterImageData represents a raster image (PNG, JPEG, WebP, etc.).
   */
  image?: QcrV1alphaRasterImageData | undefined;
  /**
   * horizontal offset within anchor cell
   */
  offsetXMm?: number | undefined;
  /**
   * vertical offset within anchor cell
   */
  offsetYMm?: number | undefined;
  widthMm?: number | undefined;
};

/** @internal */
export const QcrV1alphaSheetImage$inboundSchema: z.ZodMiniType<
  QcrV1alphaSheetImage,
  unknown
> = z.pipe(
  z.object({
    anchor_col: types.optional(types.number()),
    anchor_row: types.optional(types.number()),
    height_mm: types.optional(types.number()),
    image: types.optional(QcrV1alphaRasterImageData$inboundSchema),
    offset_x_mm: types.optional(types.number()),
    offset_y_mm: types.optional(types.number()),
    width_mm: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "anchor_col": "anchorCol",
      "anchor_row": "anchorRow",
      "height_mm": "heightMm",
      "offset_x_mm": "offsetXMm",
      "offset_y_mm": "offsetYMm",
      "width_mm": "widthMm",
    });
  }),
);

export function qcrV1alphaSheetImageFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaSheetImage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaSheetImage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaSheetImage' from JSON`,
  );
}
