/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaLayoutBinding,
  QcrV1alphaLayoutBinding$inboundSchema,
} from "./qcrv1alphalayoutbinding.js";
import {
  QcrV1alphaLayoutDefaults,
  QcrV1alphaLayoutDefaults$inboundSchema,
} from "./qcrv1alphalayoutdefaults.js";
import {
  QcrV1alphaPageGeometry,
  QcrV1alphaPageGeometry$inboundSchema,
} from "./qcrv1alphapagegeometry.js";
import {
  QcrV1alphaSourceReference,
  QcrV1alphaSourceReference$inboundSchema,
} from "./qcrv1alphasourcereference.js";

/**
 * Top-level layout structure, joined to a DocumentRecord by record_id.
 *
 * @remarks
 *  Used with the Block-based record representation (DocumentRecord.blocks).
 */
export type QcrV1alphaDocumentLayout = {
  /**
   * sparse element → layout entries
   */
  bindings?: Array<QcrV1alphaLayoutBinding> | undefined;
  /**
   * Document-wide layout defaults.
   */
  defaults?: QcrV1alphaLayoutDefaults | undefined;
  extractedAt?: Date | undefined;
  /**
   * page-level geometry (all pages)
   */
  pages?: Array<QcrV1alphaPageGeometry> | undefined;
  /**
   * references DocumentRecord.id
   */
  recordId?: string | undefined;
  /**
   * SourceReference links a record back to the source it was extracted from.
   *
   * @remarks
   *
   *  Three typed fields identify WHAT, WHERE, and WHEN. Everything else —
   *  format, content hash, storage location, checksums, external URLs — goes
   *  in the attributes bag, because the relevant metadata varies by source type.
   *
   *  Examples by source type:
   *
   *    File upload:
   *      source_id  = "intg_01j8k..."                    (upload channel instance)
   *      remote_id  = "req_01h2xcejqtf2nbrexx3vqjhp41"   (upload request ID)
   *      attributes = {format: "pdf", location: "uploads/.../original.pdf",
   *                    content_hash: "a1b2c3...", storage_etag: "\"abc\""}
   *
   *    Gmail integration:
   *      source_id  = "intg_01k9m..."                    (Gmail connector instance)
   *      remote_id  = "18abc123def"                       (Gmail message ID)
   *      attributes = {format: "eml", thread_id: "...",
   *                    external_url: "https://mail.google.com/..."}
   *
   *    Confluence sync:
   *      source_id  = "intg_01p3q..."                    (Confluence connector instance)
   *      remote_id  = "12345678"                          (Confluence page ID)
   *      attributes = {format: "html", space_key: "ENG",
   *                    external_url: "https://acme.atlassian.net/wiki/..."}
   */
  source?: QcrV1alphaSourceReference | undefined;
};

/** @internal */
export const QcrV1alphaDocumentLayout$inboundSchema: z.ZodMiniType<
  QcrV1alphaDocumentLayout,
  unknown
> = z.pipe(
  z.object({
    bindings: types.optional(z.array(QcrV1alphaLayoutBinding$inboundSchema)),
    defaults: types.optional(QcrV1alphaLayoutDefaults$inboundSchema),
    extracted_at: types.optional(types.date()),
    pages: types.optional(z.array(QcrV1alphaPageGeometry$inboundSchema)),
    record_id: types.optional(types.string()),
    source: types.optional(QcrV1alphaSourceReference$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "extracted_at": "extractedAt",
      "record_id": "recordId",
    });
  }),
);

export function qcrV1alphaDocumentLayoutFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaDocumentLayout, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaDocumentLayout$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaDocumentLayout' from JSON`,
  );
}
