/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Value, Value$inboundSchema } from "./value.js";

export type QcrV1alphaNamedRange = {
  /**
   * `Struct` represents a structured data value, consisting of fields
   *
   * @remarks
   *  which map to dynamically typed values. In some languages, `Struct`
   *  might be supported by a native representation. For example, in
   *  scripting languages like JS a struct is represented as an
   *  object. The details of that representation are described together
   *  with the proto support for the language.
   *
   *  The JSON representation for `Struct` is JSON object.
   */
  attributes?: { [k: string]: Value | null } | undefined;
  name?: string | undefined;
  /**
   * A1-notation
   */
  rangeRef?: string | undefined;
  /**
   * empty = workbook-scoped
   */
  sheetName?: string | undefined;
};

/** @internal */
export const QcrV1alphaNamedRange$inboundSchema: z.ZodMiniType<
  QcrV1alphaNamedRange,
  unknown
> = z.pipe(
  z.object({
    attributes: types.optional(
      z.record(z.string(), types.nullable(Value$inboundSchema)),
    ),
    name: types.optional(types.string()),
    range_ref: types.optional(types.string()),
    sheet_name: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "range_ref": "rangeRef",
      "sheet_name": "sheetName",
    });
  }),
);

export function qcrV1alphaNamedRangeFromJSON(
  jsonString: string,
): SafeParseResult<QcrV1alphaNamedRange, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QcrV1alphaNamedRange$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QcrV1alphaNamedRange' from JSON`,
  );
}
