/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const RecipientType = {
  User: "user",
  Bot: "bot",
  Organization: "organization",
} as const;
export type RecipientType = OpenEnum<typeof RecipientType>;

/** @internal */
export const RecipientType$inboundSchema: z.ZodMiniType<
  RecipientType,
  unknown
> = openEnums.inboundSchema(RecipientType);
