/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  OrganizationInvite,
  OrganizationInvite$inboundSchema,
} from "./organizationinvite.js";

/**
 * ResendOrganizationInviteResponse contains the updated invitation.
 */
export type ResendOrganizationInviteResponse = {
  /**
   * OrganizationInvite represents an invitation to join an organization.
   *
   * @remarks
   * accepted_fields_consistency // accepted_at and accepted_by must both be set or both be unset
   */
  invite: OrganizationInvite;
};

/** @internal */
export const ResendOrganizationInviteResponse$inboundSchema: z.ZodMiniType<
  ResendOrganizationInviteResponse,
  unknown
> = z.object({
  invite: OrganizationInvite$inboundSchema,
});

export function resendOrganizationInviteResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResendOrganizationInviteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResendOrganizationInviteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResendOrganizationInviteResponse' from JSON`,
  );
}
