/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  GeneralAccessLevel,
  GeneralAccessLevel$inboundSchema,
} from "./generalaccesslevel.js";

/**
 * SetGeneralAccessResponse contains the updated general access level.
 */
export type SetGeneralAccessResponse = {
  /**
   * Document ID.
   */
  documentId?: string | undefined;
  generalAccessLevel?: GeneralAccessLevel | undefined;
};

/** @internal */
export const SetGeneralAccessResponse$inboundSchema: z.ZodMiniType<
  SetGeneralAccessResponse,
  unknown
> = z.pipe(
  z.object({
    document_id: types.optional(types.string()),
    general_access_level: types.optional(GeneralAccessLevel$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "document_id": "documentId",
      "general_access_level": "generalAccessLevel",
    });
  }),
);

export function setGeneralAccessResponseFromJSON(
  jsonString: string,
): SafeParseResult<SetGeneralAccessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetGeneralAccessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetGeneralAccessResponse' from JSON`,
  );
}
