/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { QuotaTier, QuotaTier$outboundSchema } from "./quotatier.js";

/**
 * SetOrganizationQuotaRequest is a request to set quota configuration.
 */
export type SetOrganizationQuotaRequest = {
  /**
   * Optional limit override. If not set, uses the configured tier default.
   *
   * @remarks
   *  Must be > 0 when set. Use a very high value (e.g., 999999999) for unlimited.
   */
  limit?: number | null | undefined;
  /**
   * The organization ID (required).
   */
  organizationId?: string | undefined;
  /**
   * QuotaTier represents the organization's quota tier.
   */
  tier?: QuotaTier | undefined;
};

/** @internal */
export type SetOrganizationQuotaRequest$Outbound = {
  limit?: number | null | undefined;
  organization_id?: string | undefined;
  tier?: string | undefined;
};

/** @internal */
export const SetOrganizationQuotaRequest$outboundSchema: z.ZodMiniType<
  SetOrganizationQuotaRequest$Outbound,
  SetOrganizationQuotaRequest
> = z.pipe(
  z.object({
    limit: z.optional(z.nullable(z.int())),
    organizationId: z.optional(z.string()),
    tier: z.optional(QuotaTier$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
    });
  }),
);

export function setOrganizationQuotaRequestToJSON(
  setOrganizationQuotaRequest: SetOrganizationQuotaRequest,
): string {
  return JSON.stringify(
    SetOrganizationQuotaRequest$outboundSchema.parse(
      setOrganizationQuotaRequest,
    ),
  );
}
