/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * ShareLink represents a shareable link for a document.
 */
export type ShareLink = {
  /**
   * When the link was created.
   */
  createdAt?: Date | undefined;
  /**
   * ID of the user who created this link.
   */
  creatorId?: string | undefined;
  /**
   * Document ID this link belongs to.
   */
  documentId?: string | undefined;
  /**
   * Share link ID.
   */
  id?: string | undefined;
};

/** @internal */
export const ShareLink$inboundSchema: z.ZodMiniType<ShareLink, unknown> = z
  .pipe(
    z.object({
      created_at: types.optional(types.date()),
      creator_id: types.optional(types.string()),
      document_id: types.optional(types.string()),
      id: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "created_at": "createdAt",
        "creator_id": "creatorId",
        "document_id": "documentId",
      });
    }),
  );

export function shareLinkFromJSON(
  jsonString: string,
): SafeParseResult<ShareLink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ShareLink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ShareLink' from JSON`,
  );
}
