/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  QcrV1alphaSpreadsheetLayout,
  QcrV1alphaSpreadsheetLayout$inboundSchema,
} from "./qcrv1alphaspreadsheetlayout.js";
import {
  QcrV1alphaSpreadsheetRecord,
  QcrV1alphaSpreadsheetRecord$inboundSchema,
} from "./qcrv1alphaspreadsheetrecord.js";

/**
 * SpreadsheetBundle groups a spreadsheet record with its optional grid layout.
 */
export type SpreadsheetBundle = {
  layout?: QcrV1alphaSpreadsheetLayout | undefined;
  /**
   * SpreadsheetRecord is the QCR representation of an ingested spreadsheet
   *
   * @remarks
   *  workbook (XLSX, CSV, Parquet). Immutable once extracted. Source-format-agnostic.
   *
   *  Hierarchy: SpreadsheetRecord 1:M Sheet 1:M DataTable/SheetImage/SheetChart.
   *  The semantic core is DataTable: named, typed columns applied to ordered rows.
   *  The extractor identifies headers and schemas so consumers don't have to.
   */
  record?: QcrV1alphaSpreadsheetRecord | undefined;
};

/** @internal */
export const SpreadsheetBundle$inboundSchema: z.ZodMiniType<
  SpreadsheetBundle,
  unknown
> = z.object({
  layout: types.optional(QcrV1alphaSpreadsheetLayout$inboundSchema),
  record: types.optional(QcrV1alphaSpreadsheetRecord$inboundSchema),
});

export function spreadsheetBundleFromJSON(
  jsonString: string,
): SafeParseResult<SpreadsheetBundle, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SpreadsheetBundle$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SpreadsheetBundle' from JSON`,
  );
}
