/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { SubjectType, SubjectType$inboundSchema } from "./subjecttype.js";

/**
 * Subject is a lightweight reference to either a user or a bot.
 *
 * @remarks
 *  Used in embedded fields like created_by.
 *  For full details, call GetUser or GetBot with the subject's id.
 * subject_type_matches_id_prefix // id prefix must match type (user_ for user, bot_ for bot)
 */
export type Subject = {
  /**
   * Unique ID. user_xxx for users, bot_xxx for bots.
   */
  id: string;
  /**
   * Display name of the user or bot.
   */
  name: string;
  type: SubjectType;
};

/** @internal */
export const Subject$inboundSchema: z.ZodMiniType<Subject, unknown> = z.object({
  id: types.string(),
  name: types.string(),
  type: SubjectType$inboundSchema,
});

export function subjectFromJSON(
  jsonString: string,
): SafeParseResult<Subject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Subject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Subject' from JSON`,
  );
}
