/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TimelineEventType,
  TimelineEventType$inboundSchema,
} from "./timelineeventtype.js";
import { Value, Value$inboundSchema } from "./value.js";

export type TimelineEvent = {
  eventId?: string | undefined;
  eventType?: TimelineEventType | undefined;
  occurredAt?: Date | undefined;
  /**
   * `Struct` represents a structured data value, consisting of fields
   *
   * @remarks
   *  which map to dynamically typed values. In some languages, `Struct`
   *  might be supported by a native representation. For example, in
   *  scripting languages like JS a struct is represented as an
   *  object. The details of that representation are described together
   *  with the proto support for the language.
   *
   *  The JSON representation for `Struct` is JSON object.
   */
  payload?: { [k: string]: Value | null } | undefined;
};

/** @internal */
export const TimelineEvent$inboundSchema: z.ZodMiniType<
  TimelineEvent,
  unknown
> = z.pipe(
  z.object({
    event_id: types.optional(types.string()),
    event_type: types.optional(TimelineEventType$inboundSchema),
    occurred_at: types.optional(types.date()),
    payload: types.optional(
      z.record(z.string(), types.nullable(Value$inboundSchema)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_id": "eventId",
      "event_type": "eventType",
      "occurred_at": "occurredAt",
    });
  }),
);

export function timelineEventFromJSON(
  jsonString: string,
): SafeParseResult<TimelineEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TimelineEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TimelineEvent' from JSON`,
  );
}
