/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * TransferDocumentOwnershipResponse confirms the transfer.
 */
export type TransferDocumentOwnershipResponse = {
  /**
   * Document ID that was transferred.
   */
  documentId?: string | undefined;
  /**
   * User ID of the new owner.
   */
  newOwnerId?: string | undefined;
};

/** @internal */
export const TransferDocumentOwnershipResponse$inboundSchema: z.ZodMiniType<
  TransferDocumentOwnershipResponse,
  unknown
> = z.pipe(
  z.object({
    document_id: types.optional(types.string()),
    new_owner_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "document_id": "documentId",
      "new_owner_id": "newOwnerId",
    });
  }),
);

export function transferDocumentOwnershipResponseFromJSON(
  jsonString: string,
): SafeParseResult<TransferDocumentOwnershipResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransferDocumentOwnershipResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransferDocumentOwnershipResponse' from JSON`,
  );
}
