/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Document, Document$inboundSchema } from "./document.js";

/**
 * UpdateDocumentResponse contains the updated document.
 */
export type UpdateDocumentResponse = {
  /**
   * Document represents a Factify document.
   */
  document?: Document | undefined;
};

/** @internal */
export const UpdateDocumentResponse$inboundSchema: z.ZodMiniType<
  UpdateDocumentResponse,
  unknown
> = z.object({
  document: types.optional(Document$inboundSchema),
});

export function updateDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateDocumentResponse' from JSON`,
  );
}
