/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * User represents a human user account.
 *
 * @remarks
 *  Returned by GetUser (endpoint deferred).
 */
export type User = {
  email: string;
  /**
   * Family name (last name) of the user.
   */
  familyName?: string | null | undefined;
  /**
   * Given name (first name) of the user.
   */
  givenName?: string | null | undefined;
  id: string;
  /**
   * Display name of the user.
   */
  name: string;
  /**
   * URL of the user's profile image.
   */
  profileImageUrl?: string | null | undefined;
};

/** @internal */
export const User$inboundSchema: z.ZodMiniType<User, unknown> = z.pipe(
  z.object({
    email: types.string(),
    family_name: z.optional(z.nullable(types.string())),
    given_name: z.optional(z.nullable(types.string())),
    id: types.string(),
    name: types.string(),
    profile_image_url: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "family_name": "familyName",
      "given_name": "givenName",
      "profile_image_url": "profileImageUrl",
    });
  }),
);

export function userFromJSON(
  jsonString: string,
): SafeParseResult<User, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => User$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'User' from JSON`,
  );
}
