/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const UserType = {
  UserAccount: "user_account",
  ServiceAccount: "service_account",
} as const;
export type UserType = OpenEnum<typeof UserType>;

/** @internal */
export const UserType$inboundSchema: z.ZodMiniType<UserType, unknown> =
  openEnums.inboundSchema(UserType);
