/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { UserType, UserType$inboundSchema } from "./usertype.js";

/**
 * User represents a user or service account.
 */
export type User = {
  /**
   * Unique ID for the user or service account.
   *
   * @remarks
   *  Pattern: user_[0-9a-hjkmnp-tv-z]{26} for users, svc_[0-9a-hjkmnp-tv-z]{26} for service accounts
   */
  id: string;
  /**
   * Display name of the user or service account.
   */
  name: string;
  type: UserType;
};

/** @internal */
export const User$inboundSchema: z.ZodMiniType<User, unknown> = z.object({
  id: types.string(),
  name: types.string(),
  type: UserType$inboundSchema,
});

export function userFromJSON(
  jsonString: string,
): SafeParseResult<User, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => User$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'User' from JSON`,
  );
}
