/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * `Value` represents a dynamically typed value which can be either
 *
 * @remarks
 *  null, a number, a string, a boolean, a recursive struct value, or a
 *  list of values. A producer of value is expected to set one of these
 *  variants. Absence of any variant indicates an error.
 *
 *  The JSON representation for `Value` is JSON value.
 */
export type Value = number | string | boolean | Array<any> | {
  [k: string]: any;
};

/** @internal */
export const Value$inboundSchema: z.ZodMiniType<Value, unknown> = smartUnion([
  types.number(),
  types.string(),
  types.boolean(),
  z.array(z.any()),
  z.record(z.string(), z.any()),
]);

export function valueFromJSON(
  jsonString: string,
): SafeParseResult<Value, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Value$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Value' from JSON`,
  );
}
