/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ProcessingStatus,
  ProcessingStatus$inboundSchema,
} from "./processingstatus.js";
import { Subject, Subject$inboundSchema } from "./subject.js";

/**
 * Version represents a document version.
 */
export type Version = {
  /**
   * Timestamp when version was created.
   */
  createdAt: Date;
  /**
   * Subject is a lightweight reference to either a user or a bot.
   *
   * @remarks
   *  Used in embedded fields like created_by.
   *  For full details, call GetUser or GetBot with the subject's id.
   * subject_type_matches_id_prefix // id prefix must match type (user_ for user, bot_ for bot)
   */
  createdBy: Subject;
  /**
   * Description of changes in this version.
   */
  description?: string | null | undefined;
  /**
   * Parent document ID.
   *
   * @remarks
   *  Pattern: doc_[0-9a-hjkmnp-tv-z]{26}
   */
  documentId: string;
  /**
   * Unique ID for the version.
   *
   * @remarks
   *  Pattern: ver_[0-9a-hjkmnp-tv-z]{26}
   */
  id: string;
  processingStatus: ProcessingStatus;
  /**
   * Optional version title.
   */
  title?: string | null | undefined;
  /**
   * URL for accessing this version on Factify.
   */
  url: string;
};

/** @internal */
export const Version$inboundSchema: z.ZodMiniType<Version, unknown> = z.pipe(
  z.object({
    created_at: types.date(),
    created_by: Subject$inboundSchema,
    description: z.optional(z.nullable(types.string())),
    document_id: types.string(),
    id: types.string(),
    processing_status: ProcessingStatus$inboundSchema,
    title: z.optional(z.nullable(types.string())),
    url: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "created_by": "createdBy",
      "document_id": "documentId",
      "processing_status": "processingStatus",
    });
  }),
);

export function versionFromJSON(
  jsonString: string,
): SafeParseResult<Version, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Version$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Version' from JSON`,
  );
}
